export interface BlogPost { slug: string; title: string; seoTitle: string; description: string; keywords: string[]; date: string; author: string; category: string; image: string; content: string; suggestedLinks: { label: string; href: string }[]; }
export const blogPosts: BlogPost[] = [
  {
    slug: "carpet-tiles-vs-broadloom-commercial-projects",
    title: "Carpet Tiles vs Broadloom: Which Commercial Carpet Is Better for Your Project?",
    seoTitle: "Carpet Tiles vs Broadloom | Visfurn",
    description: "Compare modular tiles and rolls for B2B flooring.",
    keywords: ["carpet tiles", "broadloom"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/blog-material-comparison.jpg",
    content: "Detailed analysis of carpet tiles and broadloom for commercial fit-outs. Carpet tiles are modular pieces, commonly supplied in square formats such as 50x50 cm or 24x24 inches. They are widely used in offices, retail spaces, schools, airports, and flexible commercial interiors. Broadloom carpet is supplied in rolls and creates a more seamless surface. It is often preferred for hotels, guest rooms, corridors, ballrooms, luxury retail, and hospitality projects.",
    suggestedLinks: [{ label: "Commercial Tiles", href: "/products/carpet-tiles" }]
  },
  {
    slug: "50x50-carpet-tiles-buying-guide",
    title: "50x50 Carpet Tiles Buying Guide",
    seoTitle: "50x50 Tiles Guide | Visfurn",
    description: "Standardized sourcing for contractors.",
    keywords: ["50x50", "carpet tiles"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/carpet-tile-premium.jpg",
    content: "Standard 50x50cm tiles offer the best balance of logistics and installation speed. They are easy to transport, flexible to install, and simple to replace after installation. For buyers managing office, hotel, school, or public-area projects, this size offers a practical balance between design flexibility and site efficiency.",
    suggestedLinks: [{ label: "Technical Specs", href: "/products/carpet-tiles/nylon-tiles-elite" }]
  },
  {
    slug: "fire-rated-commercial-carpet-guide",
    title: "Fire-Rated Commercial Carpet Guide",
    seoTitle: "Technical Standards | Visfurn",
    description: "ASTM E648 and Class I compliance.",
    keywords: ["fire rated", "ASTM E648"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Technical",
    image: "/images/blog-installation-maintenance.jpg",
    content: "Fire rating is one of the most important checks in commercial carpet procurement. For hotels, offices, and public buildings, flooring must meet project safety requirements. Common standards include ASTM E648 and EN 13501-1.",
    suggestedLinks: [{ label: "Contact Factory", href: "/contact" }]
  },
  {
    slug: "hotel-carpet-buying-guide",
    title: "Hotel Carpet Buying Guide",
    seoTitle: "Hospitality Solutions | Visfurn",
    description: "Luxury and durability for guest rooms.",
    keywords: ["hotel carpet", "broadloom"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Hospitality",
    image: "/images/blog-hotel-carpet.jpg",
    content: "Hotel carpet must handle guest traffic, luggage wheels, and fire safety requirements. Guest rooms usually need comfort, while corridors need denser pile for durability.",
    suggestedLinks: [{ label: "Hotel Collections", href: "/products/wall-to-wall" }]
  },
  {
    slug: "custom-carpet-design-process-b2b",
    title: "Custom Carpet Design Process for B2B Projects",
    seoTitle: "Bespoke Carpet Guide | Visfurn",
    description: "Custom patterns and Pantone matching.",
    keywords: ["custom carpet", "design"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Design",
    image: "/images/blog-design-trends.jpg",
    content: "From pattern reference to strike-off samples. We provide fully customized hospitality flooring solutions for guest rooms, corridors, ballrooms and meeting spaces.",
    suggestedLinks: [{ label: "Custom Solutions", href: "/contact" }]
  },
  {
    slug: "carpet-sample-swatches-before-bulk-order",
    title: "Why Carpet Samples Matter Before Bulk Orders",
    seoTitle: "Carpet Samples Guide | Visfurn",
    description: "Quality verification for contractors.",
    keywords: ["carpet samples", "swatches"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/samples-box.jpg",
    content: "Samples are a risk-control step. A physical sample shows pile texture, density, backing strength and edge quality that photos cannot capture.",
    suggestedLinks: [{ label: "Request Samples", href: "/contact" }]
  },
  {
    slug: "low-voc-commercial-carpet-guide",
    title: "Low-VOC Commercial Carpet Guide",
    seoTitle: "Sustainability Standards | Visfurn",
    description: "Indoor air quality for B2B projects.",
    keywords: ["low VOC", "CRI Green Label"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Technical",
    image: "/images/about-quality-control.jpg",
    content: "Indoor air quality (IAQ) is critical for office and hotel projects. CRI Green Label Plus certification ensures low emissions for occupant comfort.",
    suggestedLinks: [{ label: "Technical Docs", href: "/about-us" }]
  },
  {
    slug: "hotel-corridor-carpet-selection",
    title: "Hotel Corridor Carpet Selection Guide",
    seoTitle: "Hotel Corridor Carpet | Visfurn",
    description: "Durability for high-traffic zones.",
    keywords: ["corridor carpet", "hotel"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/blog-hotel-carpet.jpg",
    content: "Corridors need high-density patterns to hide traffic lanes and withstand heavy luggage movement. Nylon and wool-nylon blends are common choices.",
    suggestedLinks: [{ label: "Corridor Solutions", href: "/products/wall-to-wall" }]
  },
  {
    slug: "stair-carpet-commercial-buying-guide",
    title: "Stair Carpet Buying Guide for Commercial Buildings",
    seoTitle: "Commercial Stair Carpet | Visfurn",
    description: "Safety and durability for staircases.",
    keywords: ["stair carpet", "safety"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/blog-installation-maintenance.jpg",
    content: "Stair edges receive concentrated pressure. Durable nylon construction with high pile recovery is essential for commercial staircase longevity.",
    suggestedLinks: [{ label: "Consult Factory", href: "/contact" }]
  },
  {
    slug: "exhibition-carpet-flooring-guide",
    title: "Exhibition Carpet Flooring Selection Guide",
    seoTitle: "Exhibition Carpet | Visfurn",
    description: "Flooring for trade shows and events.",
    keywords: ["exhibition carpet", "event"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/blog-design-trends.jpg",
    content: "Speed of installation and cost control are priorities for events. We provide reusable and temporary carpet rolls for booths and event halls.",
    suggestedLinks: [{ label: "Event Solutions", href: "/products/public-area" }]
  },
  {
    slug: "commercial-carpet-installation-maintenance-guide",
    title: "Commercial Carpet Installation & Maintenance",
    seoTitle: "Maintenance Guide | Visfurn",
    description: "Maximize lifespan of B2B flooring.",
    keywords: ["installation", "maintenance"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Maintenance",
    image: "/images/blog-installation-maintenance.jpg",
    content: "Proper subfloor preparation and planned cleaning cycles extend carpet life. Modular tiles allow for selective replacement of damaged areas.",
    suggestedLinks: [{ label: "Installation Guide", href: "/faq" }]
  },
  {
    slug: "office-carpet-tiles-selection-guide",
    title: "Office Carpet Tiles Selection Guide",
    seoTitle: "Office Carpet Tiles | Visfurn",
    description: "Best modular flooring for offices.",
    keywords: ["office carpet", "tiles"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/blog-office-carpet.jpg",
    content: "Office carpets must handle rolling chairs and layout changes. Solution-dyed nylon tiles offer the best balance of performance and aesthetics.",
    suggestedLinks: [{ label: "Office Collections", href: "/products/carpet-tiles" }]
  },
  {
    slug: "wall-to-wall-carpet-commercial-guide",
    title: "Wall-to-Wall Carpet for Commercial Projects",
    seoTitle: "Broadloom Guide | Visfurn",
    description: "Continuous surface solutions for B2B.",
    keywords: ["wall to wall", "broadloom"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/category-broadloom.jpg",
    content: "Visual continuity for grand spaces. Broadloom supports large-scale pattern development for hotel ballrooms and luxury lounges.",
    suggestedLinks: [{ label: "Broadloom Solutions", href: "/products/wall-to-wall" }]
  },
  {
    slug: "commercial-carpet-moq-pricing-guide",
    title: "Commercial Carpet MOQ & Pricing Guide",
    seoTitle: "Pricing Guide | Visfurn",
    description: "Budget planning for B2B procurement.",
    keywords: ["MOQ", "price"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/blog-material-comparison.jpg",
    content: "Pricing is driven by material, quantity and customization. Standard carpet tiles have lower MOQs compared to custom jacquard broadloom.",
    suggestedLinks: [{ label: "Get Quote", href: "/contact" }]
  },
  {
    slug: "commercial-carpet-shipping-lead-time",
    title: "Commercial Carpet Shipping & Lead Time Guide",
    seoTitle: "Logistics Guide | Visfurn",
    description: "Planning overseas B2B orders.",
    keywords: ["shipping", "lead time"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Logistics",
    image: "/images/blog-office-carpet.jpg",
    content: "Coordinate production with construction progress. We support DDP shipping and provide accurate timelines for international projects.",
    suggestedLinks: [{ label: "Logistics Info", href: "/about-us" }]
  }
];
