export interface BlogPost { slug: string; title: string; seoTitle: string; description: string; keywords: string[]; date: string; author: string; category: string; image: string; content: string; suggestedLinks: { label: string; href: string }[]; }
export const blogPosts: BlogPost[] = [
  {
    slug: "carpet-tiles-vs-broadloom-commercial-projects",
    title: "Carpet Tiles vs Broadloom: Which Commercial Carpet Is Better for Your Project?",
    seoTitle: "Comparison Guide | Visfurn",
    description: "Modular tiles vs rolls analysis.",
    keywords: ["carpet tiles", "broadloom"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/blog-material-comparison.jpg",
    content: "Detailed analysis of carpet tiles and broadloom for commercial fit-outs. Carpet tiles are modular pieces, commonly supplied in square formats such as 50x50 cm. Their biggest advantage is selective replacement. Broadloom carpet is supplied in rolls and creates a more seamless surface. It is often preferred for hotels and corridors.",
    suggestedLinks: [{ label: "Commercial Tiles", href: "/products/carpet-tiles" }]
  },
  {
    slug: "50x50-carpet-tiles-buying-guide",
    title: "50x50 Carpet Tiles Buying Guide",
    seoTitle: "Office Sourcing | Visfurn",
    description: "Guide for office fit-outs.",
    keywords: ["50x50", "carpet tiles"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/carpet-tile-premium.jpg",
    content: "Standard 50x50cm tiles offer the best balance of logistics and installation speed. They are easy to transport, flexible to install, and simple to replace. Solution-dyed nylon is usually the best choice for high-traffic areas.",
    suggestedLinks: [{ label: "Technical Specs", href: "/products/carpet-tiles/nylon-tiles-elite" }]
  },
  {
    slug: "fire-rated-commercial-carpet-guide",
    title: "Fire-Rated Commercial Carpet Guide",
    seoTitle: "Technical Standards | Visfurn",
    description: "ASTM E648 compliance.",
    keywords: ["fire rated", "ASTM E648"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Technical",
    image: "/images/blog-installation-maintenance.jpg",
    content: "Fire rating is one of the most important checks in commercial carpet procurement. Our ranges meet project safety requirements like ASTM E648 Class I.",
    suggestedLinks: [{ label: "Technical Inquiry", href: "/contact" }]
  },
  {
    slug: "hotel-carpet-buying-guide",
    title: "Hotel Carpet Buying Guide",
    seoTitle: "Hospitality | Visfurn",
    description: "Luxury guest room flooring.",
    keywords: ["hotel carpet", "broadloom"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Hospitality",
    image: "/images/blog-hotel-carpet.jpg",
    content: "Hotel carpet must handle guest traffic and luggage wheels. Corridors need high-density patterns to hide traffic lanes.",
    suggestedLinks: [{ label: "Hotel Collections", href: "/products/wall-to-wall" }]
  },
  {
    slug: "custom-carpet-design-process-b2b",
    title: "Custom Carpet Design Process for B2B Projects",
    seoTitle: "Bespoke Design | Visfurn",
    description: "Design matching for hotels.",
    keywords: ["custom", "design"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Design",
    image: "/images/blog-design-trends.jpg",
    content: "From pattern reference to strike-off samples. We provide fully customized hospitality flooring solutions.",
    suggestedLinks: [{ label: "Custom Solutions", href: "/contact" }]
  },
  {
    slug: "carpet-sample-swatches-before-bulk-order",
    title: "Why Carpet Samples Matter Before Bulk Orders",
    seoTitle: "Sourcing Guide | Visfurn",
    description: "Risk-control for contractors.",
    keywords: ["samples", "swatches"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/samples-box.jpg",
    content: "Physical samples allow designers to compare real color and texture under project lighting.",
    suggestedLinks: [{ label: "Request Samples", href: "/contact" }]
  },
  {
    slug: "low-voc-commercial-carpet-guide",
    title: "Low-VOC Commercial Carpet Guide",
    seoTitle: "Sustainability | Visfurn",
    description: "Indoor air quality standards.",
    keywords: ["low VOC", "CRI Green Label"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Technical",
    image: "/images/about-quality-control.jpg",
    content: "Indoor air quality is critical for office and hotel projects. CRI Green Label Plus certification ensures low emissions.",
    suggestedLinks: [{ label: "Technical Docs", href: "/about-us" }]
  },
  {
    slug: "hotel-corridor-carpet-selection",
    title: "Hotel Corridor Carpet Selection Guide",
    seoTitle: "Corridor Guide | Visfurn",
    description: "Durability for hospitality.",
    keywords: ["corridor", "hotel"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Hospitality",
    image: "/images/blog-hotel-carpet.jpg",
    content: "Corridors receive constant foot traffic and housekeeping carts. Denser pile and stronger backing are essential.",
    suggestedLinks: [{ label: "Corridor Solutions", href: "/products/wall-to-wall" }]
  },
  {
    slug: "stair-carpet-commercial-buying-guide",
    title: "Stair Carpet Buying Guide",
    seoTitle: "Safety | Visfurn",
    description: "Staircase durability.",
    keywords: ["stair", "safety"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/blog-installation-maintenance.jpg",
    content: "Stair edges receive concentrated pressure. Durable nylon with high pile recovery is essential.",
    suggestedLinks: [{ label: "Consult Factory", href: "/contact" }]
  },
  {
    slug: "exhibition-carpet-flooring-guide",
    title: "Exhibition Carpet Flooring Selection Guide",
    seoTitle: "Event Flooring | Visfurn",
    description: "Trade show carpet tips.",
    keywords: ["exhibition", "event"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/blog-design-trends.jpg",
    content: "Speed of installation and cost control are priorities for events.",
    suggestedLinks: [{ label: "Event Solutions", href: "/products/public-area" }]
  },
  {
    slug: "commercial-carpet-installation-maintenance-guide",
    title: "Commercial Carpet Maintenance Guide",
    seoTitle: "Maintenance | Visfurn",
    description: "Long-term performance.",
    keywords: ["maintenance", "installation"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Maintenance",
    image: "/images/blog-installation-maintenance.jpg",
    content: "Planned cleaning cycles extend carpet life. Modular tiles allow for selective replacement.",
    suggestedLinks: [{ label: "Technical Support", href: "/contact" }]
  },
  {
    slug: "office-carpet-tiles-selection-guide",
    title: "Office Carpet Tiles Selection Guide",
    seoTitle: "Office Guide | Visfurn",
    description: "Workplace flooring solutions.",
    keywords: ["office", "tiles"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/blog-office-carpet.jpg",
    content: "Office carpets must handle rolling chairs and layout changes.",
    suggestedLinks: [{ label: "Office Tiles", href: "/products/carpet-tiles" }]
  },
  {
    slug: "wall-to-wall-carpet-commercial-guide",
    title: "Wall-to-Wall Carpet Guide",
    seoTitle: "Broadloom | Visfurn",
    description: "Project surface solutions.",
    keywords: ["wall-to-wall", "rolls"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Product",
    image: "/images/category-broadloom.jpg",
    content: "Visual continuity for grand spaces like ballrooms.",
    suggestedLinks: [{ label: "Broadloom Rolls", href: "/products/wall-to-wall" }]
  },
  {
    slug: "commercial-carpet-moq-pricing-guide",
    title: "Commercial Carpet Pricing Guide",
    seoTitle: "B2B Pricing | Visfurn",
    description: "Bulk order budget tips.",
    keywords: ["MOQ", "price"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Buying Guide",
    image: "/images/blog-material-comparison.jpg",
    content: "Pricing is driven by material and quantity. Nylon costs more but performs better.",
    suggestedLinks: [{ label: "Request Quote", href: "/contact" }]
  },
  {
    slug: "commercial-carpet-shipping-lead-time",
    title: "Shipping & Lead Time Guide",
    seoTitle: "Logistics | Visfurn",
    description: "Importing carpet from China.",
    keywords: ["shipping", "lead-time"],
    date: "2026-06-19",
    author: "Carpet Expert",
    category: "Logistics",
    image: "/images/blog-office-carpet.jpg",
    content: "Standard items ship in 10 days. Custom orders need 30 days.",
    suggestedLinks: [{ label: "Global Logistics", href: "/about-us" }]
  }
];
