export type CountryMarketPageKind = "commercial" | "gold";

export interface CountryMarketPage {
  market: string;
  slug: string;
  path: string;
  kind: CountryMarketPageKind;
  language: string;
  hreflang: string;
  openGraphLocale: string;
  countryName: string;
  countryNameLocal: string;
  title: string;
  metadataTitle: string;
  metadataDescription: string;
  directAnswer: string;
  marketContext: string;
  environmentNote: string;
  deliveryNote: string;
  applications: string[];
  localTerms: string[];
  primaryProductId: string;
  productIds: string[];
}

function commercialPage(
  page: Omit<CountryMarketPage, "kind" | "path" | "primaryProductId" | "productIds"> & {
    productSet?: "humid" | "hospitality" | "office" | "cold" | "casino";
  },
): CountryMarketPage {
  const productSets = {
    humid: ["ecocore-pe-backing-carpet-tiles", "luxury-hotel-broadloom", "public-area-heavy-duty"],
    hospitality: ["3d-printed-hotel-carpet", "luxury-hotel-broadloom", "commercial-nylon-tiles"],
    office: ["nylon-office-carpet-tile", "commercial-nylon-tiles", "public-area-heavy-duty"],
    cold: ["nylon-office-carpet-tile", "luxury-hotel-broadloom", "public-area-heavy-duty"],
    casino: ["singapore-casino-carpet", "3d-printed-banquet-hall-carpet", "glitter-hotel-corridor-broadloom-carpet"],
  } as const;
  const productIds = [...productSets[page.productSet ?? "office"]];

  return {
    ...page,
    kind: "commercial",
    path: `/${page.market}/${page.slug}`,
    primaryProductId: productIds[0],
    productIds,
  };
}

function goldPage(
  page: Omit<CountryMarketPage, "kind" | "path" | "primaryProductId" | "productIds">,
): CountryMarketPage {
  return {
    ...page,
    kind: "gold",
    path: `/${page.market}/${page.slug}`,
    primaryProductId: "gold-mining-carpet-mat",
    productIds: ["gold-mining-carpet-mat"],
  };
}

export const countryMarketPages: CountryMarketPage[] = [
  commercialPage({
    market: "ph",
    slug: "commercial-carpet-supplier-philippines",
    language: "en",
    hreflang: "en-PH",
    openGraphLocale: "en_PH",
    countryName: "Philippines",
    countryNameLocal: "Philippines",
    title: "Commercial Carpet Supplier for the Philippines",
    metadataTitle: "Commercial Carpet Supplier Philippines | VISHOME",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Philippine offices, hotels and public projects. Compare specifications, samples, MOQ and project supply.",
    directAnswer: "A commercial carpet supplier for the Philippines should help buyers compare moisture-tolerant backing, heavy-traffic performance, sample approval, installation conditions and consolidated delivery. VISHOME supplies carpet tiles, hotel broadloom and public-area carpet for project inquiries, with final specifications confirmed against the site environment and tender requirements.",
    marketContext: "Projects in Metro Manila, Cebu and Davao often combine hotels, offices, retail interiors and mixed-use developments. Buyers should separate visual approval from technical approval so color, backing, fire documents and maintenance planning are reviewed before production.",
    environmentNote: "Warm and humid conditions make slab moisture testing, product acclimation, adhesive selection and dry storage especially important before installation.",
    deliveryNote: "Ask for packing dimensions, pallet count, gross weight and destination details before choosing sea freight or a consolidated sample shipment.",
    applications: ["Hotels and resorts", "Corporate offices", "Retail and mixed-use interiors", "Airports and public corridors"],
    localTerms: ["commercial carpet Philippines", "hotel carpet supplier Philippines", "office carpet tiles Philippines"],
    productSet: "humid",
  }),
  commercialPage({
    market: "au",
    slug: "commercial-carpet-supplier-australia",
    language: "en",
    hreflang: "en-AU",
    openGraphLocale: "en_AU",
    countryName: "Australia",
    countryNameLocal: "Australia",
    title: "Commercial Carpet Supplier for Australia",
    metadataTitle: "Commercial Carpet Supplier Australia | VISHOME",
    metadataDescription: "Commercial carpet tiles and hospitality broadloom for Australian projects. Review samples, technical documents, MOQ, packing and project quotation.",
    directAnswer: "Australian commercial carpet buyers should shortlist products by traffic class, fire and acoustic requirements, backing construction, replacement strategy and installation conditions. VISHOME supports project-based carpet tile and broadloom sourcing, but the nominated product and supporting documents must be checked against the project specification before ordering.",
    marketContext: "Australian procurement teams frequently need clear documentation for offices, education, hospitality and multi-site refurbishment. A useful RFQ should identify the city, floor area, installation pattern, expected traffic and required document list.",
    environmentNote: "Large temperature differences between regions and conditioned interiors make delivery storage and product acclimation part of installation planning.",
    deliveryNote: "For Sydney, Melbourne, Brisbane and other destinations, compare full-container and consolidated shipping using the final roll or pallet plan rather than square metres alone.",
    applications: ["Office fit-outs", "Hotels and serviced apartments", "Education projects", "Public and transport interiors"],
    localTerms: ["commercial carpet supplier Australia", "carpet tiles Australia wholesale", "hotel carpet manufacturer Australia"],
    productSet: "office",
  }),
  commercialPage({
    market: "bg",
    slug: "commercial-carpet-supplier-bulgaria",
    language: "en",
    hreflang: "en-BG",
    openGraphLocale: "en_BG",
    countryName: "Bulgaria",
    countryNameLocal: "Bulgaria",
    title: "Commercial Carpet Supplier for Bulgaria Projects",
    metadataTitle: "Commercial Carpet Supplier Bulgaria | Vishomecarpet",
    metadataDescription: "Commercial carpet tiles and hotel carpet for Bulgaria projects. Compare office fit-out options, samples, MOQ, TDS, packing and export quotation inputs.",
    directAnswer: "A commercial carpet supplier for Bulgaria should help project buyers compare office carpet tiles, hospitality broadloom, backing options, spare stock, sample approval and export packing before order confirmation. Vishomecarpet supports Bulgaria project inquiries from China, while final suitability must be checked against the buyer's tender, local contractor and installation conditions.",
    marketContext: "Sofia, Plovdiv and Varna projects can include office fit-outs, hotels, retail interiors and public corridors. Buyers usually get a better quotation when they separate workstation areas, corridors, reception zones and hospitality spaces instead of sending only one total floor area.",
    environmentNote: "Seasonal temperature changes and winter delivery make dry storage, acclimation and subfloor moisture checks important before installation.",
    deliveryNote: "Request the carton or roll plan, gross weight, pallet dimensions, destination city and Incoterm before comparing freight and local delivery timing.",
    applications: ["Office fit-outs", "Hotel corridors and guestrooms", "Retail and commercial interiors", "Public corridors and reception areas"],
    localTerms: ["commercial carpet Bulgaria", "office carpet tiles Bulgaria", "hotel carpet supplier Bulgaria"],
    productSet: "office",
  }),
  commercialPage({
    market: "ca",
    slug: "commercial-carpet-supplier-canada",
    language: "en",
    hreflang: "en-CA",
    openGraphLocale: "en_CA",
    countryName: "Canada",
    countryNameLocal: "Canada",
    title: "Commercial Carpet Supplier for Canada Projects",
    metadataTitle: "Commercial Carpet Supplier Canada | Vishomecarpet",
    metadataDescription: "Commercial carpet tiles and hotel carpet for Canada projects. Review snow, salt, chair-wheel wear, samples, MOQ, TDS, packing and quotation inputs.",
    directAnswer: "A commercial carpet supplier for Canada should help buyers plan moisture, snow and salt exposure, chair-wheel wear, phased renovation, spare stock and technical document review before the quotation is approved. Vishomecarpet can support carpet tile and hospitality carpet sourcing from China, but the final construction must match the building specification and local installation conditions.",
    marketContext: "Toronto, Vancouver, Calgary, Montreal and other Canadian project locations can require different logistics, winter delivery and maintenance planning. Office buyers should provide floor plans by zone, while hospitality buyers should separate guestrooms, corridors and public areas.",
    environmentNote: "Winter moisture, salt carry-in and heated indoor conditions make entrance zoning, dry storage and product acclimation especially important.",
    deliveryNote: "Confirm packing, pallet count, delivery city, seasonal receiving constraints and target installation window before comparing freight options.",
    applications: ["Office renovations", "Corporate corridors", "Hotel guestrooms and corridors", "Public and commercial interiors"],
    localTerms: ["commercial carpet Canada", "office carpet tiles Canada", "hotel carpet supplier Canada"],
    productSet: "cold",
  }),
  commercialPage({
    market: "pl",
    slug: "dostawca-wykladzin-komercyjnych",
    language: "pl",
    hreflang: "pl-PL",
    openGraphLocale: "pl_PL",
    countryName: "Poland",
    countryNameLocal: "Polska",
    title: "Dostawca wykładzin komercyjnych do projektów w Polsce",
    metadataTitle: "Dostawca wykładzin komercyjnych Polska | VISHOME",
    metadataDescription: "Płytki dywanowe i wykładziny hotelowe do projektów w Polsce. Porównaj parametry, próbki, MOQ, dokumentację i plan dostawy.",
    directAnswer: "Dostawca wykładzin komercyjnych dla Polski powinien umożliwić porównanie konstrukcji włókna, podkładu, klasy użytkowej, dokumentów projektowych i sposobu wymiany zużytych stref. VISHOME przygotowuje próbki i wyceny projektowe, natomiast końcową zgodność należy potwierdzić z wymaganiami inwestora i lokalnymi przepisami.",
    marketContext: "Office, hotel and public-space projects in Warsaw, Kraków and Wrocław benefit from a specification-led process that separates design selection, technical approval and commercial quotation.",
    environmentNote: "Winter transport and heated interiors require dry storage and sufficient acclimation before installation; substrate moisture remains a separate site check.",
    deliveryNote: "Request carton or roll dimensions, pallet configuration, gross weight and Incoterm options before comparing road, rail or sea-linked delivery routes.",
    applications: ["Biura i centra biznesowe", "Hotele i korytarze", "Obiekty edukacyjne", "Przestrzenie handlowe i publiczne"],
    localTerms: ["wykładziny komercyjne", "płytki dywanowe do biura", "wykładzina hotelowa producent"],
    productSet: "cold",
  }),
  commercialPage({
    market: "ro",
    slug: "furnizor-mocheta-comerciala",
    language: "ro",
    hreflang: "ro-RO",
    openGraphLocale: "ro_RO",
    countryName: "Romania",
    countryNameLocal: "România",
    title: "Furnizor de mochetă comercială pentru proiecte din România",
    metadataTitle: "Furnizor mochetă comercială România | VISHOME",
    metadataDescription: "Dale de mochetă și mochetă hotelieră pentru proiecte din România. Mostre, specificații, MOQ, documente și ofertă de proiect.",
    directAnswer: "Un furnizor de mochetă comercială pentru România trebuie evaluat după material, suport, trafic, întreținere, mostre și documentația solicitată de proiect. VISHOME poate pregăti opțiuni pentru birouri, hoteluri și zone publice, iar specificația finală se confirmă înaintea comenzii.",
    marketContext: "Projects in Bucharest, Cluj-Napoca and Timișoara often involve phased office fit-outs, hospitality refurbishment and public interiors. Send room schedules and finish references early to reduce later sample revisions.",
    environmentNote: "Seasonal temperature changes mean rolls and tiles should be protected from moisture and acclimated in the conditioned installation area.",
    deliveryNote: "Compare delivery scenarios using the final packing list and destination, not an assumed freight rate based only on area.",
    applications: ["Birouri", "Hoteluri și coridoare", "Spații comerciale", "Clădiri publice"],
    localTerms: ["mochetă comercială", "dale mochetă birou", "mochetă hotelieră furnizor"],
    productSet: "office",
  }),
  commercialPage({
    market: "mx",
    slug: "proveedor-alfombras-comerciales",
    language: "es",
    hreflang: "es-MX",
    openGraphLocale: "es_MX",
    countryName: "Mexico",
    countryNameLocal: "México",
    title: "Proveedor de alfombras comerciales para proyectos en México",
    metadataTitle: "Proveedor de alfombras comerciales México | VISHOME",
    metadataDescription: "Losetas de alfombra y alfombra hotelera para México. Compare muestras, especificaciones, MOQ, empaque y cotización de proyecto.",
    directAnswer: "Un proveedor de alfombras comerciales para México debe confirmar uso, tráfico, soporte, mantenimiento, muestra aprobada y condiciones de instalación antes de producir. VISHOME suministra losetas modulares, alfombra hotelera y soluciones para áreas públicas con cotización basada en el proyecto.",
    marketContext: "Hotel, corporate and retail projects in Ciudad de México, Monterrey and Guadalajara benefit from a room-by-room quantity schedule, approved color reference and clear documentation list.",
    environmentNote: "Climate and site conditions vary widely by region, so slab moisture, acclimation and adhesive selection must be checked at the actual project location.",
    deliveryNote: "Include destination city, port preference, roll or pallet plan and required Incoterm when requesting freight options.",
    applications: ["Hoteles y resorts", "Oficinas corporativas", "Centros comerciales", "Pasillos y áreas públicas"],
    localTerms: ["alfombra comercial México", "losetas de alfombra oficina", "proveedor alfombra hotelera"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "dk",
    slug: "leverandor-erhvervstaepper",
    language: "da",
    hreflang: "da-DK",
    openGraphLocale: "da_DK",
    countryName: "Denmark",
    countryNameLocal: "Danmark",
    title: "Leverandør af erhvervstæpper til projekter i Danmark",
    metadataTitle: "Leverandør af erhvervstæpper Danmark | VISHOME",
    metadataDescription: "Tæppefliser og hotelgulvtæpper til danske projekter. Sammenlign prøver, dokumentation, MOQ, akustik og projektlevering.",
    directAnswer: "En leverandør af erhvervstæpper til Danmark bør kunne dokumentere konstruktion, slidklasse, akustiske egenskaber, vedligeholdelse og prøveproces. VISHOME tilbyder projektbaseret sourcing, men alle dokumentkrav og den endelige gulvopbygning skal godkendes til det konkrete projekt.",
    marketContext: "Danish office and hospitality interiors often prioritise calm design, acoustic comfort, replaceable modules and transparent material documentation.",
    environmentNote: "Cold-season transport and controlled indoor environments require dry storage and acclimation before installation.",
    deliveryNote: "For Copenhagen, Aarhus and Odense, compare logistics after confirming carton count, roll length, pallet footprint and delivery access.",
    applications: ["Kontorer", "Hoteller", "Undervisningsmiljøer", "Offentlige fællesarealer"],
    localTerms: ["erhvervstæpper", "tæppefliser kontor", "hotelgulvtæppe leverandør"],
    productSet: "cold",
  }),
  commercialPage({
    market: "uz",
    slug: "tijorat-gilam-yetkazib-beruvchi",
    language: "uz",
    hreflang: "uz-UZ",
    openGraphLocale: "uz_UZ",
    countryName: "Uzbekistan",
    countryNameLocal: "O‘zbekiston",
    title: "O‘zbekiston uchun tijorat gilam yetkazib beruvchi",
    metadataTitle: "Tijorat gilam yetkazib beruvchi O‘zbekiston | VISHOME",
    metadataDescription: "O‘zbekiston mehmonxona, ofis va jamoat loyihalari uchun gilam plitka va rulon gilam. Namuna, MOQ va loyiha taklifi.",
    directAnswer: "O‘zbekistondagi tijorat gilam loyihasi uchun mahsulot turi, trafik darajasi, asos materiali, namuna tasdig‘i va yetkazib berish rejasi birgalikda tekshirilishi kerak. VISHOME loyiha talabi bo‘yicha gilam plitka va mehmonxona gilamini taklif qiladi.",
    marketContext: "Hotel, office and retail projects in Tashkent, Samarkand and Bukhara need clear sample approval, room schedules and packaging data before transport is booked.",
    environmentNote: "Dry and dusty conditions increase the importance of entrance-zone planning, cleaning access and sealed storage before installation.",
    deliveryNote: "Land and multimodal routes should be compared using final pallet dimensions, weight and destination rather than an estimated square-metre rate.",
    applications: ["Mehmonxonalar", "Ofislar", "Savdo maydonlari", "Konferensiya va jamoat zallari"],
    localTerms: ["tijorat gilam", "ofis gilam plitkasi", "mehmonxona gilami"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "am",
    slug: "commercial-carpet-supplier-armenia",
    language: "hy",
    hreflang: "hy-AM",
    openGraphLocale: "hy_AM",
    countryName: "Armenia",
    countryNameLocal: "Հայաստան",
    title: "Առևտրային գորգերի մատակարար Հայաստանի նախագծերի համար",
    metadataTitle: "Առևտրային գորգերի մատակարար Հայաստան | VISHOME",
    metadataDescription: "Գորգային սալիկներ և հյուրանոցային գորգեր Հայաստանի նախագծերի համար։ Նմուշներ, MOQ, տեխնիկական տվյալներ և առաջարկ։",
    directAnswer: "Հայաստանում առևտրային գորգ ընտրելիս պետք է համեմատել նյութը, հիմքը, ծանրաբեռնվածությունը, սպասարկումը, նմուշը և առաքման պայմանները։ VISHOME-ը տրամադրում է նախագծային առաջարկներ, իսկ վերջնական բնութագիրը հաստատվում է կոնկրետ օբյեկտի պահանջներով։",
    marketContext: "Projects in Yerevan, Gyumri and Vanadzor can range from boutique hospitality to offices and public interiors, so quantities and technical requirements should be separated by area.",
    environmentNote: "Mountain climate and winter delivery make dry storage, acclimation and conditioned installation spaces important.",
    deliveryNote: "Request a project packing list and compare consolidated and full-load transport after samples and quantities are approved.",
    applications: ["Հյուրանոցներ", "Գրասենյակներ", "Ռեստորաններ և սրահներ", "Հանրային տարածքներ"],
    localTerms: ["առևտրային գորգ", "գորգային սալիկներ", "հյուրանոցային գորգ"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "hr",
    slug: "dobavljac-komercijalnih-tepiha",
    language: "hr",
    hreflang: "hr-HR",
    openGraphLocale: "hr_HR",
    countryName: "Croatia",
    countryNameLocal: "Hrvatska",
    title: "Dobavljač komercijalnih tepiha za projekte u Hrvatskoj",
    metadataTitle: "Dobavljač komercijalnih tepiha Hrvatska | VISHOME",
    metadataDescription: "Tepih ploče i hotelski tepisi za projekte u Hrvatskoj. Uzorci, specifikacije, MOQ, pakiranje i projektna ponuda.",
    directAnswer: "Dobavljač komercijalnih tepiha za Hrvatsku treba potvrditi namjenu prostora, intenzitet prometa, podlogu, održavanje, uzorak i uvjete ugradnje. VISHOME priprema projektne opcije za hotele, urede i javne prostore, uz konačnu provjeru specifikacije prije narudžbe.",
    marketContext: "Hospitality projects in Zagreb, Split and coastal destinations often work to seasonal opening dates, making early sample and production approval important.",
    environmentNote: "Coastal humidity and inland seasonal changes require site-specific moisture checks and correct acclimation.",
    deliveryNote: "Confirm delivery access, roll lengths, pallet quantities and phased handover needs before selecting the transport plan.",
    applications: ["Hoteli i resorti", "Uredi", "Restorani i dvorane", "Javni hodnici"],
    localTerms: ["komercijalni tepih", "tepih ploče ured", "hotelski tepih dobavljač"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "hu",
    slug: "kereskedelmi-szonyeg-beszallito",
    language: "hu",
    hreflang: "hu-HU",
    openGraphLocale: "hu_HU",
    countryName: "Hungary",
    countryNameLocal: "Magyarország",
    title: "Kereskedelmi szőnyeg beszállító magyarországi projektekhez",
    metadataTitle: "Kereskedelmi szőnyeg beszállító Magyarország | VISHOME",
    metadataDescription: "Modulszőnyeg és szállodai padlószőnyeg magyar projektekhez. Minták, műszaki adatok, MOQ és projektárajánlat.",
    directAnswer: "Magyarországi kereskedelmi szőnyegprojektnél a használati osztályt, anyagot, hátoldalt, karbantartást, mintát és beépítési feltételeket együtt kell értékelni. A VISHOME projektalapú ajánlatot készít, a végleges megfelelőséget pedig a konkrét kiírás alapján kell ellenőrizni.",
    marketContext: "Budapest, Debrecen and Szeged projects may involve hotel renovation, office fit-out or public interiors with phased handover and replacement planning.",
    environmentNote: "Seasonal temperature variation requires protected transport, dry storage and acclimation in the final indoor conditions.",
    deliveryNote: "Use the approved roll and pallet schedule to compare transport costs and installation sequencing.",
    applications: ["Irodák", "Szállodák", "Konferencia- és rendezvényterek", "Közösségi terek"],
    localTerms: ["kereskedelmi szőnyeg", "modulszőnyeg iroda", "szállodai padlószőnyeg"],
    productSet: "office",
  }),
  commercialPage({
    market: "kg",
    slug: "commercial-carpet-supplier-kyrgyzstan",
    language: "ru",
    hreflang: "ru-KG",
    openGraphLocale: "ru_KG",
    countryName: "Kyrgyzstan",
    countryNameLocal: "Кыргызстан",
    title: "Поставщик коммерческого ковролина для проектов в Кыргызстане",
    metadataTitle: "Коммерческий ковролин Кыргызстан | VISHOME",
    metadataDescription: "Ковровая плитка и гостиничный ковролин для проектов в Кыргызстане. Образцы, MOQ, параметры, упаковка и расчет поставки.",
    directAnswer: "Для проекта в Кыргызстане коммерческий ковролин следует выбирать по назначению, нагрузке, основе, обслуживанию, образцу и условиям монтажа. VISHOME готовит проектный расчет, а окончательные параметры подтверждаются после проверки требований объекта.",
    marketContext: "Projects in Bishkek, Osh and Jalal-Abad often require practical sample consolidation and clear separation between standard and custom production.",
    environmentNote: "Mountain climate and winter transport make protected storage and acclimation especially relevant before installation.",
    deliveryNote: "Compare land routes after confirming pallet size, weight, destination and whether the project needs one or several delivery stages.",
    applications: ["Гостиницы", "Офисы", "Торговые помещения", "Общественные залы"],
    localTerms: ["коммерческий ковролин Кыргызстан", "ковровая плитка Бишкек", "гостиничный ковролин"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "kz",
    slug: "kommerciyalyk-kilem-zhetkizushi",
    language: "kk",
    hreflang: "kk-KZ",
    openGraphLocale: "kk_KZ",
    countryName: "Kazakhstan",
    countryNameLocal: "Қазақстан",
    title: "Қазақстан жобаларына арналған коммерциялық кілем жеткізуші",
    metadataTitle: "Коммерциялық кілем жеткізуші Қазақстан | VISHOME",
    metadataDescription: "Қазақстандағы қонақүй, кеңсе және қоғамдық жобаларға кілем плиткасы мен рулон кілем. Үлгі, MOQ және жоба есебі.",
    directAnswer: "Қазақстандағы коммерциялық кілем жобасында материал, негіз, қозғалыс жүктемесі, үлгі, қызмет көрсету және жеткізу кезеңдері бірге тексерілуі керек. VISHOME жоба бойынша ұсыныс береді, ал соңғы сипаттама нысан талаптарына сай расталады.",
    marketContext: "Almaty, Astana and Shymkent projects may span long internal distances, so city-level destination and staged quantities should be defined in the RFQ.",
    environmentNote: "Cold winter transport requires protected packing, dry storage and adequate acclimation before installation.",
    deliveryNote: "Rail, road and multimodal options should be compared only after final pallet dimensions, weights and destination handling are known.",
    applications: ["Қонақүйлер", "Кеңселер", "Сауда орталықтары", "Қоғамдық дәліздер"],
    localTerms: ["коммерциялық кілем", "кілем плиткасы", "қонақүй кілемі"],
    productSet: "cold",
  }),
  commercialPage({
    market: "rs",
    slug: "dobavljac-komercijalnih-tepiha",
    language: "sr",
    hreflang: "sr-RS",
    openGraphLocale: "sr_RS",
    countryName: "Serbia",
    countryNameLocal: "Srbija",
    title: "Dobavljač komercijalnih tepiha za projekte u Srbiji",
    metadataTitle: "Dobavljač komercijalnih tepiha Srbija | VISHOME",
    metadataDescription: "Tepih ploče i hotelski tepisi za projekte u Srbiji. Uzorci, specifikacije, MOQ, pakovanje i projektna ponuda.",
    directAnswer: "Za komercijalni tepih u Srbiji kupci treba da provere namenu, opterećenje, vlakno, podlogu, održavanje, uzorak i uslove ugradnje. VISHOME priprema projektne opcije, dok se konačna specifikacija potvrđuje prema zahtevima objekta.",
    marketContext: "Belgrade, Novi Sad and Niš projects often combine office, hospitality and public-space requirements, making room schedules and phased quantities useful at quotation stage.",
    environmentNote: "Seasonal transport and indoor heating require protected storage and acclimation before adhesive installation.",
    deliveryNote: "Confirm customs documents, pallet or roll plan and destination access before comparing transport quotations.",
    applications: ["Kancelarije", "Hoteli", "Restorani i sale", "Javni prostori"],
    localTerms: ["komercijalni tepih", "tepih ploče kancelarija", "hotelski tepih dobavljač"],
    productSet: "office",
  }),
  commercialPage({
    market: "no",
    slug: "leverandor-kommersielle-tepper",
    language: "nb",
    hreflang: "nb-NO",
    openGraphLocale: "nb_NO",
    countryName: "Norway",
    countryNameLocal: "Norge",
    title: "Leverandør av kommersielle tepper til prosjekter i Norge",
    metadataTitle: "Leverandør kommersielle tepper Norge | VISHOME",
    metadataDescription: "Teppefliser og hotelltepper for norske prosjekter. Sammenlign prøver, akustikk, dokumentasjon, MOQ og prosjektlevering.",
    directAnswer: "En leverandør av kommersielle tepper til Norge bør kunne beskrive fiber, bakside, bruksklasse, akustikk, vedlikehold og dokumentasjon uten å anta at én løsning passer alle bygg. VISHOME tilbyr prosjektbaserte alternativer som må kontrolleres mot den aktuelle beskrivelsen.",
    marketContext: "Norwegian office, hospitality and public projects commonly prioritise acoustic comfort, replaceable zones and transparent technical documentation.",
    environmentNote: "Winter transport and heated interiors require dry storage and acclimation in stable room conditions before installation.",
    deliveryNote: "For Oslo, Bergen and Trondheim, use the final pallet and roll schedule to evaluate delivery access and freight alternatives.",
    applications: ["Kontorer", "Hoteller", "Undervisningsbygg", "Offentlige fellesarealer"],
    localTerms: ["kommersielle tepper", "teppefliser kontor", "hotellteppe leverandør"],
    productSet: "cold",
  }),
  commercialPage({
    market: "cz",
    slug: "dodavatel-komercnich-kobercu",
    language: "cs",
    hreflang: "cs-CZ",
    openGraphLocale: "cs_CZ",
    countryName: "Czech Republic",
    countryNameLocal: "Česko",
    title: "Dodavatel komerčních koberců pro projekty v Česku",
    metadataTitle: "Dodavatel komerčních koberců Česko | VISHOME",
    metadataDescription: "Kobercové čtverce a hotelové koberce pro české projekty. Vzorky, parametry, MOQ, dokumentace a projektová nabídka.",
    directAnswer: "Dodavatel komerčních koberců pro český projekt by měl doložit konstrukci, zátěž, podklad, údržbu, vzorky a požadované dokumenty. VISHOME připravuje projektové varianty, které je nutné před objednávkou porovnat s konkrétní specifikací.",
    marketContext: "Prague, Brno and Ostrava projects often include office refurbishment, hotels and public interiors with phased access and replacement planning.",
    environmentNote: "Seasonal transport requires dry storage and acclimation; substrate moisture must still be measured at the project site.",
    deliveryNote: "Compare freight using approved carton, pallet and roll data together with the final delivery address.",
    applications: ["Kanceláře", "Hotely", "Školy a univerzity", "Veřejné prostory"],
    localTerms: ["komerční koberce", "kobercové čtverce kancelář", "hotelový koberec dodavatel"],
    productSet: "office",
  }),
  commercialPage({
    market: "sk",
    slug: "dodavatel-komercnych-kobercov",
    language: "sk",
    hreflang: "sk-SK",
    openGraphLocale: "sk_SK",
    countryName: "Slovakia",
    countryNameLocal: "Slovensko",
    title: "Dodávateľ komerčných kobercov pre projekty na Slovensku",
    metadataTitle: "Dodávateľ komerčných kobercov Slovensko | VISHOME",
    metadataDescription: "Kobercové štvorce a hotelové koberce pre slovenské projekty. Vzorky, parametre, MOQ a projektová ponuka.",
    directAnswer: "Pri komerčnom koberci na Slovensku treba porovnať materiál, podklad, záťaž, údržbu, vzorku a podmienky montáže. VISHOME pripravuje projektové možnosti, pričom konečná špecifikácia sa potvrdzuje podľa požiadaviek konkrétnej stavby.",
    marketContext: "Bratislava, Košice and Žilina projects can involve office, hotel and public-space refurbishment with phased installation.",
    environmentNote: "Cold-season delivery requires protected storage and sufficient acclimation before installation.",
    deliveryNote: "Use the final packing list and destination to compare road, rail-linked or consolidated freight options.",
    applications: ["Kancelárie", "Hotely", "Vzdelávacie priestory", "Verejné chodby"],
    localTerms: ["komerčné koberce", "kobercové štvorce kancelária", "hotelový koberec dodávateľ"],
    productSet: "office",
  }),
  commercialPage({
    market: "si",
    slug: "dobavitelj-poslovnih-preprog",
    language: "sl",
    hreflang: "sl-SI",
    openGraphLocale: "sl_SI",
    countryName: "Slovenia",
    countryNameLocal: "Slovenija",
    title: "Dobavitelj poslovnih preprog za projekte v Sloveniji",
    metadataTitle: "Dobavitelj poslovnih preprog Slovenija | VISHOME",
    metadataDescription: "Tekstilne talne plošče in hotelske preproge za slovenske projekte. Vzorci, specifikacije, MOQ in projektna ponudba.",
    directAnswer: "Pri izbiri poslovne preproge v Sloveniji je treba preveriti uporabo, obremenitev, vlakno, podlago, vzdrževanje, vzorec in pogoje vgradnje. VISHOME pripravi projektne možnosti, končna specifikacija pa se potrdi glede na zahteve objekta.",
    marketContext: "Ljubljana, Maribor and Koper projects often include boutique hospitality, offices and public interiors where smaller phased quantities may matter.",
    environmentNote: "Coastal and inland conditions differ, so moisture testing and acclimation should follow the actual project environment.",
    deliveryNote: "Confirm roll lengths, pallet count, delivery access and installation sequence before selecting transport.",
    applications: ["Pisarne", "Hoteli", "Restavracije in dvorane", "Javni prostori"],
    localTerms: ["poslovne preproge", "tekstilne talne plošče", "hotelska preproga dobavitelj"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "sg",
    slug: "commercial-carpet-supplier-singapore",
    language: "en",
    hreflang: "en-SG",
    openGraphLocale: "en_SG",
    countryName: "Singapore",
    countryNameLocal: "Singapore",
    title: "Commercial Carpet Supplier for Singapore Projects",
    metadataTitle: "Commercial Carpet Supplier Singapore | Vishomecarpet",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Singapore offices, hotels and public interiors. Samples, MOQ and project quotation.",
    directAnswer: "Singapore commercial carpet projects should evaluate traffic, backing, fire-document requirements, maintenance access, indoor humidity and replacement strategy before approval. Vishomecarpet supplies project carpet options with samples and specification records, while final compliance must be confirmed for the nominated building and installation system.",
    marketContext: "High-rise offices, hotels and public interiors need clear lift access, delivery staging, room schedules and replacement planning before production quantities are fixed.",
    environmentNote: "Tropical humidity makes substrate testing, conditioned storage, acclimation and compatible adhesive selection critical site responsibilities.",
    deliveryNote: "Include delivery floor, loading access, pallet restrictions and phased handover dates when requesting the project quotation.",
    applications: ["High-rise offices", "Hotels and serviced apartments", "Retail interiors", "Airports and public buildings"],
    localTerms: ["commercial carpet supplier Singapore", "office carpet tiles Singapore", "hotel carpet supplier Singapore"],
    productSet: "humid",
  }),
  commercialPage({
    market: "sg",
    slug: "singapore-casino-carpet-supplier",
    language: "en",
    hreflang: "en-SG",
    openGraphLocale: "en_SG",
    countryName: "Singapore",
    countryNameLocal: "Singapore",
    title: "Singapore Casino Carpet Supplier for Oriental Flower Gaming Floors",
    metadataTitle: "Singapore Casino Carpet Supplier | Oriental Flower Carpet | Vishomecarpet",
    metadataDescription: "Custom oriental flower luxury casino carpet for Singapore gaming floors, VIP rooms, clubs and hotel entertainment areas. Review samples, MOQ, backing, shipping and quote.",
    directAnswer: "A Singapore casino carpet supplier should help buyers confirm price per SQM, sample timing, traffic level, oriental flower or custom pattern approval, visual soil control, backing stability, cleaning access, fire-document requirements and staged delivery before production. Vishomecarpet supplies custom luxury casino carpet options with high-density loop pile appearance, non-slip backing options, OEM design support, samples and quotation support for gaming floors, VIP rooms and hotel entertainment zones.",
    marketContext: "Singapore casino, hotel and entertainment projects often combine gaming floors, VIP rooms, clubs, lift lobbies and corridors in one procurement package. High-quality B2B buyers usually need sample speed, price basis, MOQ, exact quantity planning, distributor support, installation-team coordination, packing data, freight clarity and pattern approval before an internal purchasing decision can move forward.",
    environmentNote: "Indoor humidity, high air-conditioning use, heavy foot traffic, gaming chairs, service carts and frequent cleaning make backing selection, product acclimation, substrate checks and maintenance planning important before installation.",
    deliveryNote: "Send the Singapore site address, delivery floor, loading access, contact phone, project phase, roll or pallet restrictions, required sample date and target installation date when requesting a casino carpet quotation.",
    applications: ["Casino gaming floors", "VIP rooms and clubs", "Hotel entertainment zones", "Lift lobbies and gaming corridors"],
    localTerms: ["Singapore casino carpet", "casino carpet supplier Singapore", "custom gaming floor carpet Singapore", "oriental flower casino carpet", "hotel casino carpet Singapore", "casino carpet sample Singapore"],
    productSet: "casino",
  }),
  commercialPage({
    market: "ge",
    slug: "commercial-carpet-supplier-georgia",
    language: "ka",
    hreflang: "ka-GE",
    openGraphLocale: "ka_GE",
    countryName: "Georgia",
    countryNameLocal: "საქართველო",
    title: "კომერციული ხალიჩის მომწოდებელი საქართველოს პროექტებისთვის",
    metadataTitle: "კომერციული ხალიჩის მომწოდებელი საქართველო | VISHOME",
    metadataDescription: "ხალიჩის ფილები და სასტუმროს ხალიჩა საქართველოს პროექტებისთვის. ნიმუშები, MOQ, ტექნიკური მონაცემები და შეთავაზება.",
    directAnswer: "საქართველოში კომერციული ხალიჩის არჩევისას საჭიროა გამოყენების, დატვირთვის, საფუძვლის, მოვლის, ნიმუშისა და მონტაჟის პირობების ერთად შეფასება. VISHOME ამზადებს პროექტულ ვარიანტებს, ხოლო საბოლოო სპეციფიკაცია ობიექტის მოთხოვნებით დასტურდება.",
    marketContext: "Tbilisi, Batumi and Kutaisi projects range from urban offices to coastal hospitality, so the same carpet construction should not be assumed for every location.",
    environmentNote: "Coastal humidity and inland seasonal conditions require site-specific moisture checks and acclimation.",
    deliveryNote: "Define destination, packing plan and phased quantities before comparing Black Sea-linked and land transport options.",
    applications: ["სასტუმროები", "ოფისები", "რესტორნები და დარბაზები", "საჯარო სივრცეები"],
    localTerms: ["კომერციული ხალიჩა", "ხალიჩის ფილები", "სასტუმროს ხალიჩა"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "se",
    slug: "leverantor-kommersiella-mattor",
    language: "sv",
    hreflang: "sv-SE",
    openGraphLocale: "sv_SE",
    countryName: "Sweden",
    countryNameLocal: "Sverige",
    title: "Leverantör av kommersiella mattor för projekt i Sverige",
    metadataTitle: "Leverantör kommersiella mattor Sverige | VISHOME",
    metadataDescription: "Textilplattor och hotellmattor för svenska projekt. Jämför prover, akustik, dokumentation, MOQ och projektleverans.",
    directAnswer: "En leverantör av kommersiella mattor till Sverige bör kunna redovisa material, baksida, belastning, akustik, underhåll och dokumentation. VISHOME erbjuder projektbaserade alternativ, men slutlig produkt och dokumentation måste kontrolleras mot den aktuella kravspecifikationen.",
    marketContext: "Stockholm, Gothenburg and Malmö projects often prioritise acoustic comfort, replaceable modules and restrained design for offices, hotels and public interiors.",
    environmentNote: "Cold-season transport and heated buildings require dry storage and acclimation before installation.",
    deliveryNote: "Evaluate freight and site access after the approved carton, pallet and roll plan is available.",
    applications: ["Kontor", "Hotell", "Utbildningsmiljöer", "Offentliga lokaler"],
    localTerms: ["kommersiella mattor", "textilplattor kontor", "hotellmatta leverantör"],
    productSet: "cold",
  }),
  commercialPage({
    market: "by",
    slug: "postavshchik-kommercheskogo-kovrolina",
    language: "ru",
    hreflang: "ru-BY",
    openGraphLocale: "ru_BY",
    countryName: "Belarus",
    countryNameLocal: "Беларусь",
    title: "Поставщик коммерческого ковролина для проектов в Беларуси",
    metadataTitle: "Коммерческий ковролин Беларусь | VISHOME",
    metadataDescription: "Ковровая плитка и гостиничный ковролин для проектов в Беларуси. Образцы, MOQ, параметры и индивидуальный расчет поставки.",
    directAnswer: "Для проектов в Беларуси коммерческий ковролин нужно сравнивать по назначению, нагрузке, основе, обслуживанию, образцу и монтажной системе. VISHOME готовит проектные предложения, а доступность маршрута, оплаты и документов подтверждается отдельно для каждого заказа.",
    marketContext: "Minsk, Gomel and Brest projects may involve offices, hotels or public areas with different replacement and maintenance strategies.",
    environmentNote: "Cold-season transport requires protected packing, dry storage and adequate acclimation before installation.",
    deliveryNote: "Shipping, payment and document availability can change; confirm the destination and transaction route before relying on a preliminary quotation.",
    applications: ["Офисы", "Гостиницы", "Торговые помещения", "Общественные пространства"],
    localTerms: ["коммерческий ковролин Беларусь", "ковровая плитка Минск", "гостиничный ковролин"],
    productSet: "cold",
  }),
  commercialPage({
    market: "fi",
    slug: "kaupallisten-mattojen-toimittaja",
    language: "fi",
    hreflang: "fi-FI",
    openGraphLocale: "fi_FI",
    countryName: "Finland",
    countryNameLocal: "Suomi",
    title: "Kaupallisten mattojen toimittaja Suomen projekteihin",
    metadataTitle: "Kaupallisten mattojen toimittaja Suomi | VISHOME",
    metadataDescription: "Tekstiililaatat ja hotellimatot suomalaisiin projekteihin. Näytteet, akustiikka, asiakirjat, MOQ ja projektitoimitus.",
    directAnswer: "Suomen kaupallisissa mattoprojekteissa tulee vertailla materiaalia, taustarakennetta, käyttöluokkaa, akustiikkaa, huoltoa ja asiakirjoja. VISHOME tarjoaa projektikohtaisia vaihtoehtoja, jotka on tarkistettava kohteen lopullista määrittelyä vasten.",
    marketContext: "Helsinki, Tampere and Turku projects often value acoustic comfort, modular replacement and clear maintenance planning.",
    environmentNote: "Winter transport and heated interiors require dry storage and sufficient acclimation before installation.",
    deliveryNote: "Use approved packing dimensions and final site access information when comparing delivery options.",
    applications: ["Toimistot", "Hotellit", "Oppilaitokset", "Julkiset tilat"],
    localTerms: ["kaupalliset matot", "tekstiililaatat toimisto", "hotellimatto toimittaja"],
    productSet: "cold",
  }),
  commercialPage({
    market: "az",
    slug: "kommersiya-xalca-techizatcisi",
    language: "az",
    hreflang: "az-AZ",
    openGraphLocale: "az_AZ",
    countryName: "Azerbaijan",
    countryNameLocal: "Azərbaycan",
    title: "Azərbaycan layihələri üçün kommersiya xalça təchizatçısı",
    metadataTitle: "Kommersiya xalça təchizatçısı Azərbaycan | VISHOME",
    metadataDescription: "Azərbaycan otel, ofis və ictimai layihələri üçün xalça plitəsi və rulon xalça. Nümunə, MOQ və layihə təklifi.",
    directAnswer: "Azərbaycanda kommersiya xalçası seçərkən istifadə sahəsi, trafik, əsas, qulluq, nümunə və quraşdırma şərtləri birlikdə qiymətləndirilməlidir. VISHOME layihə üzrə variantlar hazırlayır, yekun xüsusiyyətlər isə obyekt tələblərinə əsasən təsdiqlənir.",
    marketContext: "Baku, Ganja and Sumqayit projects may include hotels, offices and event spaces where design approval and technical approval should be recorded separately.",
    environmentNote: "Warm conditions and different site environments require actual substrate testing, protected storage and product acclimation.",
    deliveryNote: "Confirm destination, pallet or roll plan, customs document needs and project stages before comparing freight options.",
    applications: ["Otellər", "Ofislər", "Restoran və tədbir zalları", "İctimai məkanlar"],
    localTerms: ["kommersiya xalçası", "ofis xalça plitəsi", "otel xalçası təchizatçısı"],
    productSet: "hospitality",
  }),
  goldPage({
    market: "pe",
    slug: "alfombra-mineria-oro-peru",
    language: "es",
    hreflang: "es-PE",
    openGraphLocale: "es_PE",
    countryName: "Peru",
    countryNameLocal: "Perú",
    title: "Alfombra para minería de oro y canaletas en Perú",
    metadataTitle: "Alfombra para minería de oro Perú | VISHOME",
    metadataDescription: "Alfombra PVC tipo miners moss para canaletas, plantas de lavado y recuperación aluvial en Perú. Muestras, espesores y rollos OEM.",
    directAnswer: "La alfombra para minería de oro en Perú debe seleccionarse según el ancho de la canaleta, altura disponible, clasificación previa del material, caudal y método de limpieza. VISHOME suministra rollos de PVC tipo miners moss en varios espesores; ninguna alfombra garantiza por sí sola una tasa de recuperación, por lo que se recomienda validar una muestra en el equipo real.",
    marketContext: "Compradores en Lima, Arequipa y regiones mineras pueden usar el material en canaletas, concentradores, trommels y plantas de lavado, siempre que la geometría del sistema sea compatible.",
    environmentNote: "El rendimiento depende del diseño de riffles, distribución del agua, granulometría y limpieza. La alfombra no sustituye las pruebas operativas del equipo.",
    deliveryNote: "Indique ancho útil, longitud, espesor, cantidad de rollos, color y destino para calcular empaque y transporte sin asumir dimensiones estándar incorrectas.",
    applications: ["Canaletas de lavado", "Plantas aluviales", "Trommels y concentradores", "Fabricantes de equipos mineros"],
    localTerms: ["alfombra minería de oro Perú", "miners moss Perú", "alfombra para canaleta de oro"],
  }),
  goldPage({
    market: "co",
    slug: "alfombra-mineria-oro-colombia",
    language: "es",
    hreflang: "es-CO",
    openGraphLocale: "es_CO",
    countryName: "Colombia",
    countryNameLocal: "Colombia",
    title: "Alfombra para minería de oro y canaletas en Colombia",
    metadataTitle: "Alfombra para minería de oro Colombia | VISHOME",
    metadataDescription: "Alfombra PVC tipo miners moss para canaletas y recuperación aluvial en Colombia. Compare muestra, espesor, rollo, limpieza y OEM.",
    directAnswer: "Para seleccionar alfombra de minería de oro en Colombia, el comprador debe confirmar ancho de canaleta, espesor disponible, caudal, tamaño de alimentación y frecuencia de limpieza. VISHOME ofrece PVC tipo miners moss y muestras de prueba, pero la recuperación final depende del conjunto completo del equipo y de las condiciones operativas.",
    marketContext: "Proyectos y distribuidores en Bogotá, Medellín, Cali y zonas de operación pueden requerir rollos estándar o medidas adaptadas para canaletas, dragas, trommels y módulos de concentración.",
    environmentNote: "La humedad y el material arcilloso pueden cambiar la limpieza y el flujo; pruebe la configuración con material representativo antes de definir una compra mayor.",
    deliveryNote: "Incluya cantidad, espesor, ancho, longitud, color, tipo de respaldo y ciudad de entrega en la solicitud de cotización.",
    applications: ["Canaletas de recuperación", "Lavado aluvial", "Trommels y dragas", "Distribuidores de equipos"],
    localTerms: ["alfombra minería de oro Colombia", "miners moss Colombia", "tapete para canaleta de oro"],
  }),
];

export const countryMarketPageMap = Object.fromEntries(
  countryMarketPages.map((page) => [`${page.market}/${page.slug}`, page]),
) as Record<string, CountryMarketPage>;

export const countryMarketLanguages = Object.fromEntries(
  countryMarketPages.map((page) => [page.market, page.language]),
) as Record<string, string>;

export function getCountryMarketLanguage(pathname: string) {
  const [market, slug] = pathname.split("/").filter(Boolean);
  if (!market || !slug || !countryMarketPageMap[`${market}/${slug}`]) return null;
  return countryMarketLanguages[market] ?? null;
}
