export type CountryMarketPageKind = "commercial" | "gold";

export interface CountryMarketPage {
  market: string;
  slug: string;
  path: string;
  kind: CountryMarketPageKind;
  language: string;
  hreflang: string;
  openGraphLocale: string;
  countryName: string;
  countryNameLocal: string;
  title: string;
  metadataTitle: string;
  metadataDescription: string;
  directAnswer: string;
  marketContext: string;
  environmentNote: string;
  deliveryNote: string;
  applications: string[];
  localTerms: string[];
  heroImage?: string;
  heroImageAlt?: string;
  localIntentSections?: CountryMarketIntentSection[];
  primaryProductId: string;
  productIds: string[];
}

export interface CountryMarketIntentSection {
  title: string;
  summary: string;
  points: string[];
}

function commercialPage(
  page: Omit<CountryMarketPage, "kind" | "path" | "primaryProductId" | "productIds"> & {
    productSet?: "humid" | "hospitality" | "office" | "cold" | "casino";
  },
): CountryMarketPage {
  const productSets = {
    humid: ["ecocore-pe-backing-carpet-tiles", "luxury-hotel-broadloom", "public-area-heavy-duty"],
    hospitality: ["3d-printed-hotel-carpet", "luxury-hotel-broadloom", "commercial-nylon-tiles"],
    office: ["nylon-office-carpet-tile", "commercial-nylon-tiles", "public-area-heavy-duty"],
    cold: ["nylon-office-carpet-tile", "luxury-hotel-broadloom", "public-area-heavy-duty"],
    casino: ["singapore-casino-carpet", "3d-printed-banquet-hall-carpet", "glitter-hotel-corridor-broadloom-carpet"],
  } as const;
  const productIds = [...productSets[page.productSet ?? "office"]];

  return {
    ...page,
    kind: "commercial",
    path: `/${page.market}/${page.slug}`,
    primaryProductId: productIds[0],
    productIds,
  };
}

function goldPage(
  page: Omit<CountryMarketPage, "kind" | "path" | "primaryProductId" | "productIds">,
): CountryMarketPage {
  return {
    ...page,
    kind: "gold",
    path: `/${page.market}/${page.slug}`,
    primaryProductId: "gold-mining-carpet-mat",
    productIds: ["gold-mining-carpet-mat"],
  };
}

function defaultCommercialLocalIntentSections(page: CountryMarketPage): CountryMarketIntentSection[] {
  return [
    {
      title: `Local procurement trigger in ${page.countryName}`,
      summary: `These notes reflect how project buyers in ${page.countryName} usually move from first search to a ready-to-send RFQ.`,
      points: [
        page.marketContext,
        `Project teams in ${page.countryName} typically define city, application, area and handover phase before they compare colour or decoration details.`,
        `The first supplier filter usually checks whether the product category, backing, traffic level and maintenance path fit ${page.countryName} project conditions.`,
      ],
    },
    {
      title: "Local approval factors",
      summary: "These are the checks that usually happen before the buyer moves from interest to quotation comparison.",
      points: [
        page.environmentNote,
        "Sample approval should confirm colour, construction and backing together; a visual sample alone is not enough for project sign-off.",
        `Delivery planning should follow the real project route, packing format and access conditions mentioned in the quotation request for ${page.countryName}.`,
      ],
    },
    {
      title: "Search wording buyers actually use",
      summary: "Reuse these phrases in headings, FAQs and internal links so the page mirrors real buyer language.",
      points: page.localTerms.map((term) => `${term} — use this phrase when the buyer is looking for a project supplier, not retail stock.`),
    },
    {
      title: "What to include in a local RFQ",
      summary: "A complete RFQ keeps the quotation aligned with the real project instead of a generic area-only estimate.",
      points: [
        `Project type and end use, such as ${page.applications[0]} or ${page.applications[1] ?? page.applications[0]}.`,
        "Estimated area, installation phase and delivery city so freight and packing can be checked together.",
        `Required documents, including sample approval, backing confirmation and any project fire or performance records that apply to ${page.countryName} tenders.`,
      ],
    },
  ];
}

function defaultGoldLocalIntentSections(page: CountryMarketPage): CountryMarketIntentSection[] {
  return [
    {
      title: `Intención local de compra en ${page.countryNameLocal}`,
      summary: "Estos puntos resumen cómo suelen pasar de la búsqueda inicial al RFQ los compradores de este mercado.",
      points: [
        page.marketContext,
        "El disparador de compra suele ser el ancho de la canaleta, el espesor disponible, el caudal y el tipo de equipo antes de hablar de color o empaque.",
        "La aprobación comercial suele depender de muestra o rollo de prueba, cantidad, ciudad de entrega y condiciones de empaque.",
      ],
    },
    {
      title: "Revisión técnica y de operación",
      summary: "La compra no se valida solo por el material; también depende del equipo y de las condiciones reales de lavado.",
      points: [
        "La revisión técnica suele comprobar la estructura, el respaldo, la limpieza y el comportamiento con material húmedo o arcilloso.",
        page.environmentNote,
        "La muestra debe probarse en el sistema real antes de una compra mayor, porque el resultado depende de todo el conjunto operativo.",
      ],
    },
    {
      title: "Términos que usa el comprador local",
      summary: "Replica estas frases en títulos, FAQ e interlinks para que la página suene como una búsqueda real del mercado.",
      points: page.localTerms.map((term) => `${term} — úselo cuando el comprador busca un proveedor de proyecto o una solución para canaleta.`),
    },
    {
      title: "Datos que debe traer la solicitud",
      summary: "Un RFQ completo evita cotizar solo por metros y mantiene el precio ligado a la configuración real.",
      points: [
        "Dimensiones de la canaleta o del equipo, cantidad requerida y ciudad de entrega.",
        "Espesor, color, respaldo y tipo de empaque si la compra incluye muestra, rollo de prueba u OEM.",
        "Tipo de material alimentado, frecuencia de limpieza y cualquier condición especial de operación.",
      ],
    },
  ];
}

export function defaultLocalIntentSections(page: CountryMarketPage): CountryMarketIntentSection[] {
  if (page.localIntentSections?.length) return page.localIntentSections;
  return page.kind === "gold" ? defaultGoldLocalIntentSections(page) : defaultCommercialLocalIntentSections(page);
}

export const countryMarketPages: CountryMarketPage[] = [
  commercialPage({
    market: "ph",
    slug: "commercial-carpet-supplier-philippines",
    language: "en",
    hreflang: "en-PH",
    openGraphLocale: "en_PH",
    countryName: "Philippines",
    countryNameLocal: "Philippines",
    title: "Commercial Carpet Supplier for the Philippines",
    metadataTitle: "Commercial Carpet Supplier Philippines | VISHOME",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Philippine offices, hotels and public projects. Compare specifications, samples, MOQ and project supply.",
    directAnswer: "A commercial carpet supplier for the Philippines should help buyers compare moisture-tolerant backing, heavy-traffic performance, sample approval, installation conditions and consolidated delivery. VISHOME supplies carpet tiles, hotel broadloom and public-area carpet for project inquiries, with final specifications confirmed against the site environment and tender requirements.",
    marketContext: "Projects in Metro Manila, Cebu and Davao often combine hotels, offices, retail interiors and mixed-use developments. Buyers should separate visual approval from technical approval so color, backing, fire documents and maintenance planning are reviewed before production.",
    environmentNote: "Warm and humid conditions make slab moisture testing, product acclimation, adhesive selection and dry storage especially important before installation.",
    deliveryNote: "Ask for packing dimensions, pallet count, gross weight and destination details before choosing sea freight or a consolidated sample shipment.",
    applications: ["Hotels and resorts", "Corporate offices", "Retail and mixed-use interiors", "Airports and public corridors"],
    localTerms: ["commercial carpet Philippines", "hotel carpet supplier Philippines", "office carpet tiles Philippines"],
    heroImage: "/images/markets/generated/philippines-hotel-carpet-hero.webp",
    heroImageAlt: "Philippines commercial carpet supplier samples for hotel and office projects",
    productSet: "humid",
  }),
  commercialPage({
    market: "au",
    slug: "commercial-carpet-supplier-australia",
    language: "en",
    hreflang: "en-AU",
    openGraphLocale: "en_AU",
    countryName: "Australia",
    countryNameLocal: "Australia",
    title: "Commercial Carpet Supplier for Australia",
    metadataTitle: "Commercial Carpet Supplier Australia | VISHOME",
    metadataDescription: "Commercial carpet tiles and hospitality broadloom for Australian projects. Review samples, technical documents, MOQ, packing and project quotation.",
    directAnswer: "Australian commercial carpet buyers should shortlist products by traffic class, fire and acoustic requirements, backing construction, replacement strategy and installation conditions. VISHOME supports project-based carpet tile and broadloom sourcing, but the nominated product and supporting documents must be checked against the project specification before ordering.",
    marketContext: "Australian procurement teams frequently need clear documentation for offices, education, hospitality and multi-site refurbishment. A useful RFQ should identify the city, floor area, installation pattern, expected traffic and required document list.",
    environmentNote: "Large temperature differences between regions and conditioned interiors make delivery storage and product acclimation part of installation planning.",
    deliveryNote: "For Sydney, Melbourne, Brisbane and other destinations, compare full-container and consolidated shipping using the final roll or pallet plan rather than square metres alone.",
    applications: ["Office fit-outs", "Hotels and serviced apartments", "Education projects", "Public and transport interiors"],
    localTerms: ["commercial carpet supplier Australia", "carpet tiles Australia wholesale", "hotel carpet manufacturer Australia"],
    heroImage: "/images/markets/generated/australia-hotel-carpet-hero.webp",
    heroImageAlt: "Australia commercial carpet supplier for hospitality and office refurbishment",
    productSet: "office",
  }),
  commercialPage({
    market: "bg",
    slug: "commercial-carpet-supplier-bulgaria",
    language: "en",
    hreflang: "en-BG",
    openGraphLocale: "en_BG",
    countryName: "Bulgaria",
    countryNameLocal: "Bulgaria",
    title: "Commercial Carpet Supplier for Bulgaria Projects",
    metadataTitle: "Commercial Carpet Supplier Bulgaria | Vishomecarpet",
    metadataDescription: "Commercial carpet tiles and hotel carpet for Bulgaria projects. Compare office fit-out options, samples, MOQ, TDS, packing and export quotation inputs.",
    directAnswer: "A commercial carpet supplier for Bulgaria should help project buyers compare office carpet tiles, hospitality broadloom, backing options, spare stock, sample approval and export packing before order confirmation. Vishomecarpet supports Bulgaria project inquiries from China, while final suitability must be checked against the buyer's tender, local contractor and installation conditions.",
    marketContext: "Sofia, Plovdiv and Varna projects can include office fit-outs, hotels, retail interiors and public corridors. Buyers usually get a better quotation when they separate workstation areas, corridors, reception zones and hospitality spaces instead of sending only one total floor area.",
    environmentNote: "Seasonal temperature changes and winter delivery make dry storage, acclimation and subfloor moisture checks important before installation.",
    deliveryNote: "Request the carton or roll plan, gross weight, pallet dimensions, destination city and Incoterm before comparing freight and local delivery timing.",
    applications: ["Office fit-outs", "Hotel corridors and guestrooms", "Retail and commercial interiors", "Public corridors and reception areas"],
    localTerms: ["commercial carpet Bulgaria", "office carpet tiles Bulgaria", "hotel carpet supplier Bulgaria"],
    productSet: "office",
  }),
  commercialPage({
    market: "ca",
    slug: "commercial-carpet-supplier-canada",
    language: "en",
    hreflang: "en-CA",
    openGraphLocale: "en_CA",
    countryName: "Canada",
    countryNameLocal: "Canada",
    title: "Commercial Carpet Supplier for Canada Projects",
    metadataTitle: "Commercial Carpet Supplier Canada | Vishomecarpet",
    metadataDescription: "Commercial carpet tiles and hotel carpet for Canada projects. Review snow, salt, chair-wheel wear, samples, MOQ, TDS, packing and quotation inputs.",
    directAnswer: "A commercial carpet supplier for Canada should help buyers plan moisture, snow and salt exposure, chair-wheel wear, phased renovation, spare stock and technical document review before the quotation is approved. Vishomecarpet can support carpet tile and hospitality carpet sourcing from China, but the final construction must match the building specification and local installation conditions.",
    marketContext: "Toronto, Vancouver, Calgary, Montreal and other Canadian project locations can require different logistics, winter delivery and maintenance planning. Office buyers should provide floor plans by zone, while hospitality buyers should separate guestrooms, corridors and public areas.",
    environmentNote: "Winter moisture, salt carry-in and heated indoor conditions make entrance zoning, dry storage and product acclimation especially important.",
    deliveryNote: "Confirm packing, pallet count, delivery city, seasonal receiving constraints and target installation window before comparing freight options.",
    applications: ["Office renovations", "Corporate corridors", "Hotel guestrooms and corridors", "Public and commercial interiors"],
    localTerms: ["commercial carpet Canada", "office carpet tiles Canada", "hotel carpet supplier Canada"],
    heroImage: "/images/markets/generated/canada-office-carpet-tiles-hero.webp",
    heroImageAlt: "Canada commercial carpet supplier for office tile and project flooring",
    productSet: "cold",
  }),
  commercialPage({
    market: "ro",
    slug: "commercial-carpet-supplier-romania",
    language: "en",
    hreflang: "en-RO",
    openGraphLocale: "en_RO",
    countryName: "Romania",
    countryNameLocal: "România",
    title: "Commercial Carpet Supplier for Romania Projects",
    metadataTitle: "Commercial Carpet Supplier Romania | VISHOME",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Romania projects. Compare samples, TDS, MOQ, replacement planning and project quotation inputs.",
    directAnswer: "A commercial carpet supplier for Romania should help buyers compare chair-wheel wear, phased replacement, TDS review, sample approval and freight planning before the order is placed. Vishomecarpet supplies project-based carpet tiles, hotel broadloom and public-area carpet from China, while the final specification must still be checked against the tender and site conditions.",
    marketContext: "Projects in Bucharest, Cluj-Napoca and Timișoara often combine office refurbishment, hotel corridors and public interiors. Buyers should send floor plans, room schedules and required documents early so samples and technical submittals can be coordinated without rework.",
    environmentNote: "Seasonal temperature changes mean rolls and tiles should be protected from moisture and acclimated in the conditioned installation area before installation.",
    deliveryNote: "Compare freight, packing and delivery timing only after the roll or pallet plan, gross weight, destination city and Incoterm are known.",
    applications: ["Office renovations", "Hotel corridors", "Commercial interiors", "Public and mixed-use spaces"],
    localTerms: ["commercial carpet Romania", "office carpet supplier Romania", "hotel carpet supplier Romania"],
    heroImage: "/images/markets/generated/romania-commercial-carpet-supplier-hub.webp",
    heroImageAlt: "Romania commercial carpet supplier sample review for B2B projects",
    productSet: "cold",
  }),
  commercialPage({
    market: "pl",
    slug: "dostawca-wykladzin-komercyjnych",
    language: "pl",
    hreflang: "pl-PL",
    openGraphLocale: "pl_PL",
    countryName: "Poland",
    countryNameLocal: "Polska",
    title: "Dostawca wykładzin komercyjnych do projektów w Polsce",
    metadataTitle: "Dostawca wykładzin komercyjnych Polska | VISHOME",
    metadataDescription: "Płytki dywanowe i wykładziny hotelowe do projektów w Polsce. Porównaj parametry, próbki, MOQ, dokumentację i plan dostawy.",
    directAnswer: "Dostawca wykładzin komercyjnych dla Polski powinien umożliwić porównanie konstrukcji włókna, podkładu, klasy użytkowej, dokumentów projektowych i sposobu wymiany zużytych stref. VISHOME przygotowuje próbki i wyceny projektowe, natomiast końcową zgodność należy potwierdzić z wymaganiami inwestora i lokalnymi przepisami.",
    marketContext: "Office, hotel and public-space projects in Warsaw, Kraków and Wrocław benefit from a specification-led process that separates design selection, technical approval and commercial quotation.",
    environmentNote: "Winter transport and heated interiors require dry storage and sufficient acclimation before installation; substrate moisture remains a separate site check.",
    deliveryNote: "Request carton or roll dimensions, pallet configuration, gross weight and Incoterm options before comparing road, rail or sea-linked delivery routes.",
    applications: ["Biura i centra biznesowe", "Hotele i korytarze", "Obiekty edukacyjne", "Przestrzenie handlowe i publiczne"],
    localTerms: ["wykładziny komercyjne", "płytki dywanowe do biura", "wykładzina hotelowa producent"],
    localIntentSections: [
      {
        title: "Wstępny sygnał zakupowy w Polsce",
        summary: "Kupujący w Polsce zwykle zaczynają od lokalizacji projektu, zakresu prac i trybu wymiany stref, a dopiero potem porównują wzór i cenę.",
        points: [
          "Warszawa, Kraków i Wrocław często wymagają oddzielnej oceny biur, hoteli i przestrzeni publicznych, ponieważ każdy typ obiektu ma inną logikę użytkową.",
          "Zimą ważne są suche warunki składowania, aklimatyzacja i kontrola wilgotności podłoża przed montażem.",
          "Do RFQ warto dołączyć plan pomieszczeń, zakres powierzchni, etap realizacji i wymagane dokumenty techniczne, aby oferta nie była wyłącznie orientacyjna.",
        ],
      },
      {
        title: "Frazy, których używają kupujący",
        summary: "Te sformułowania pomagają dopasować nagłówki, FAQ i linki wewnętrzne do lokalnego sposobu wyszukiwania.",
        points: [
          "wykładziny komercyjne — użyj tej frazy, gdy klient szuka dostawcy projektu, a nie oferty detalicznej.",
          "płytki dywanowe do biura — użyj tej frazy przy zapytaniach o fit-out biurowy i wymianę stref.",
          "wykładzina hotelowa producent — użyj tej frazy, gdy projekt obejmuje hotel, korytarz lub strefę publiczną.",
        ],
      },
      {
        title: "Co powinno znaleźć się w lokalnym RFQ",
        summary: "Pełny zestaw danych pozwala porównać ofertę z realnymi warunkami inwestycji.",
        points: [
          "Miasto inwestycji, typ obiektu i planowany termin montażu.",
          "Ilość, format, podkład, klasa użytkowa oraz potwierdzenie próbki.",
          "Dane logistyczne: wymiary kartonu lub rolki, palety, waga brutto i warunki dostawy.",
        ],
      },
    ],
    productSet: "cold",
  }),
  commercialPage({
    market: "pl",
    slug: "commercial-carpet-supplier-poland",
    language: "en",
    hreflang: "en-PL",
    openGraphLocale: "en_PL",
    countryName: "Poland",
    countryNameLocal: "Polska",
    title: "Commercial Carpet Supplier for Poland Projects",
    metadataTitle: "Commercial Carpet Supplier Poland | VISHOME",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Poland projects. Review samples, technical files, MOQ, packing and project quotation needs.",
    directAnswer: "A commercial carpet supplier for Poland should help buyers evaluate fiber construction, backing, traffic class, maintenance needs and project documents before a quotation is approved. Vishomecarpet can prepare project options for offices, hotels and public interiors, but the nominated specification must still be checked by the buyer or consultant.",
    marketContext: "Projects in Warsaw, Kraków and Wrocław often need phased office refurbishment, corridor planning and replacement coordination across occupied floors.",
    environmentNote: "Cold-weather delivery and conditioned interiors make dry storage and acclimation important before installation.",
    deliveryNote: "Confirm pallet count, roll length, delivery city and target installation window before comparing freight choices.",
    applications: ["Office spaces", "Hotel corridors", "Education facilities", "Retail and public interiors"],
    localTerms: ["commercial carpet Poland", "office carpet supplier Poland", "hotel carpet supplier Poland"],
    heroImage: "/images/markets/generated/poland-commercial-carpet-supplier-hub.webp",
    heroImageAlt: "Poland commercial carpet supplier sample review for B2B projects",
    productSet: "cold",
  }),
  commercialPage({
    market: "ro",
    slug: "furnizor-mocheta-comerciala",
    language: "ro",
    hreflang: "ro-RO",
    openGraphLocale: "ro_RO",
    countryName: "Romania",
    countryNameLocal: "România",
    title: "Furnizor de mochetă comercială pentru proiecte din România",
    metadataTitle: "Furnizor mochetă comercială România | VISHOME",
    metadataDescription: "Dale de mochetă și mochetă hotelieră pentru proiecte din România. Mostre, specificații, MOQ, documente și ofertă de proiect.",
    directAnswer: "Un furnizor de mochetă comercială pentru România trebuie evaluat după material, suport, trafic, întreținere, mostre și documentația solicitată de proiect. VISHOME poate pregăti opțiuni pentru birouri, hoteluri și zone publice, iar specificația finală se confirmă înaintea comenzii.",
    marketContext: "Projects in Bucharest, Cluj-Napoca and Timișoara often involve phased office fit-outs, hospitality refurbishment and public interiors. Send room schedules and finish references early to reduce later sample revisions.",
    environmentNote: "Seasonal temperature changes mean rolls and tiles should be protected from moisture and acclimated in the conditioned installation area.",
    deliveryNote: "Compare delivery scenarios using the final packing list and destination, not an assumed freight rate based only on area.",
    applications: ["Birouri", "Hoteluri și coridoare", "Spații comerciale", "Clădiri publice"],
    localTerms: ["mochetă comercială", "dale mochetă birou", "mochetă hotelieră furnizor"],
    localIntentSections: [
      {
        title: "Semnalul de achiziție local în România",
        summary: "În România, cumpărătorii pornesc de obicei de la oraș, tipul clădirii și ritmul de implementare înainte de a aproba culoarea.",
        points: [
          "București, Cluj-Napoca și Timișoara includ frecvent proiecte de birouri, hoteluri și spații publice cu livrare eșalonată.",
          "Mostra, suportul și documentele tehnice trebuie aliniate din timp, altfel apar revizii suplimentare înainte de comandă.",
          "Pentru proiectele cu montaj în sezon rece trebuie verificate depozitarea uscată și aclimatizarea în spațiul final.",
        ],
      },
      {
        title: "Termeni de căutare și selecție",
        summary: "Folosește expresiile reale ale cumpărătorilor în titluri, FAQ și interlinking intern.",
        points: [
          "mochetă comercială — folosește această expresie când clientul caută un furnizor pentru proiect, nu stoc retail.",
          "dale mochetă birou — folosește-o la proiecte de birouri și înlocuiri pe zone.",
          "mochetă hotelieră furnizor — folosește-o pentru hoteluri, coridoare și zone publice.",
        ],
      },
      {
        title: "Ce trebuie să conțină RFQ-ul",
        summary: "O cerere completă de ofertă reduce riscul de preț orientativ și compară oferte pe aceeași bază.",
        points: [
          "Orașul proiectului, tipul de spațiu și suprafața estimată.",
          "Confirmarea mostrei, construcției, suportului și cerințelor de documentație.",
          "Detalii de livrare: listă de ambalare, greutate brută și adresă finală de descărcare.",
        ],
      },
    ],
    productSet: "office",
  }),
  commercialPage({
    market: "mx",
    slug: "proveedor-alfombras-comerciales",
    language: "es",
    hreflang: "es-MX",
    openGraphLocale: "es_MX",
    countryName: "Mexico",
    countryNameLocal: "México",
    title: "Proveedor de alfombras comerciales para proyectos en México",
    metadataTitle: "Proveedor de alfombras comerciales México | VISHOME",
    metadataDescription: "Losetas de alfombra y alfombra hotelera para México. Compare muestras, especificaciones, MOQ, empaque y cotización de proyecto.",
    directAnswer: "Un proveedor de alfombras comerciales para México debe confirmar uso, tráfico, soporte, mantenimiento, muestra aprobada y condiciones de instalación antes de producir. VISHOME suministra losetas modulares, alfombra hotelera y soluciones para áreas públicas con cotización basada en el proyecto.",
    marketContext: "Hotel, corporate and retail projects in Ciudad de México, Monterrey and Guadalajara benefit from a room-by-room quantity schedule, approved color reference and clear documentation list.",
    environmentNote: "Climate and site conditions vary widely by region, so slab moisture, acclimation and adhesive selection must be checked at the actual project location.",
    deliveryNote: "Include destination city, port preference, roll or pallet plan and required Incoterm when requesting freight options.",
    applications: ["Hoteles y resorts", "Oficinas corporativas", "Centros comerciales", "Pasillos y áreas públicas"],
    localTerms: ["alfombra comercial México", "losetas de alfombra oficina", "proveedor alfombra hotelera"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "dk",
    slug: "leverandor-erhvervstaepper",
    language: "da",
    hreflang: "da-DK",
    openGraphLocale: "da_DK",
    countryName: "Denmark",
    countryNameLocal: "Danmark",
    title: "Leverandør af erhvervstæpper til projekter i Danmark",
    metadataTitle: "Leverandør af erhvervstæpper Danmark | VISHOME",
    metadataDescription: "Tæppefliser og hotelgulvtæpper til danske projekter. Sammenlign prøver, dokumentation, MOQ, akustik og projektlevering.",
    directAnswer: "En leverandør af erhvervstæpper til Danmark bør kunne dokumentere konstruktion, slidklasse, akustiske egenskaber, vedligeholdelse og prøveproces. VISHOME tilbyder projektbaseret sourcing, men alle dokumentkrav og den endelige gulvopbygning skal godkendes til det konkrete projekt.",
    marketContext: "Danish office and hospitality interiors often prioritise calm design, acoustic comfort, replaceable modules and transparent material documentation.",
    environmentNote: "Cold-season transport and controlled indoor environments require dry storage and acclimation before installation.",
    deliveryNote: "For Copenhagen, Aarhus and Odense, compare logistics after confirming carton count, roll length, pallet footprint and delivery access.",
    applications: ["Kontorer", "Hoteller", "Undervisningsmiljøer", "Offentlige fællesarealer"],
    localTerms: ["erhvervstæpper", "tæppefliser kontor", "hotelgulvtæppe leverandør"],
    productSet: "cold",
  }),
  commercialPage({
    market: "uz",
    slug: "tijorat-gilam-yetkazib-beruvchi",
    language: "uz",
    hreflang: "uz-UZ",
    openGraphLocale: "uz_UZ",
    countryName: "Uzbekistan",
    countryNameLocal: "O‘zbekiston",
    title: "O‘zbekiston uchun tijorat gilam yetkazib beruvchi",
    metadataTitle: "Tijorat gilam yetkazib beruvchi O‘zbekiston | VISHOME",
    metadataDescription: "O‘zbekiston mehmonxona, ofis va jamoat loyihalari uchun gilam plitka va rulon gilam. Namuna, MOQ va loyiha taklifi.",
    directAnswer: "O‘zbekistondagi tijorat gilam loyihasi uchun mahsulot turi, trafik darajasi, asos materiali, namuna tasdig‘i va yetkazib berish rejasi birgalikda tekshirilishi kerak. VISHOME loyiha talabi bo‘yicha gilam plitka va mehmonxona gilamini taklif qiladi.",
    marketContext: "Hotel, office and retail projects in Tashkent, Samarkand and Bukhara need clear sample approval, room schedules and packaging data before transport is booked.",
    environmentNote: "Dry and dusty conditions increase the importance of entrance-zone planning, cleaning access and sealed storage before installation.",
    deliveryNote: "Land and multimodal routes should be compared using final pallet dimensions, weight and destination rather than an estimated square-metre rate.",
    applications: ["Mehmonxonalar", "Ofislar", "Savdo maydonlari", "Konferensiya va jamoat zallari"],
    localTerms: ["tijorat gilam", "ofis gilam plitkasi", "mehmonxona gilami"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "am",
    slug: "commercial-carpet-supplier-armenia",
    language: "hy",
    hreflang: "hy-AM",
    openGraphLocale: "hy_AM",
    countryName: "Armenia",
    countryNameLocal: "Հայաստան",
    title: "Առևտրային գորգերի մատակարար Հայաստանի նախագծերի համար",
    metadataTitle: "Առևտրային գորգերի մատակարար Հայաստան | VISHOME",
    metadataDescription: "Գորգային սալիկներ և հյուրանոցային գորգեր Հայաստանի նախագծերի համար։ Նմուշներ, MOQ, տեխնիկական տվյալներ և առաջարկ։",
    directAnswer: "Հայաստանում առևտրային գորգ ընտրելիս պետք է համեմատել նյութը, հիմքը, ծանրաբեռնվածությունը, սպասարկումը, նմուշը և առաքման պայմանները։ VISHOME-ը տրամադրում է նախագծային առաջարկներ, իսկ վերջնական բնութագիրը հաստատվում է կոնկրետ օբյեկտի պահանջներով։",
    marketContext: "Projects in Yerevan, Gyumri and Vanadzor can range from boutique hospitality to offices and public interiors, so quantities and technical requirements should be separated by area.",
    environmentNote: "Mountain climate and winter delivery make dry storage, acclimation and conditioned installation spaces important.",
    deliveryNote: "Request a project packing list and compare consolidated and full-load transport after samples and quantities are approved.",
    applications: ["Հյուրանոցներ", "Գրասենյակներ", "Ռեստորաններ և սրահներ", "Հանրային տարածքներ"],
    localTerms: ["առևտրային գորգ", "գորգային սալիկներ", "հյուրանոցային գորգ"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "hr",
    slug: "dobavljac-komercijalnih-tepiha",
    language: "hr",
    hreflang: "hr-HR",
    openGraphLocale: "hr_HR",
    countryName: "Croatia",
    countryNameLocal: "Hrvatska",
    title: "Dobavljač komercijalnih tepiha za projekte u Hrvatskoj",
    metadataTitle: "Dobavljač komercijalnih tepiha Hrvatska | VISHOME",
    metadataDescription: "Tepih ploče i hotelski tepisi za projekte u Hrvatskoj. Uzorci, specifikacije, MOQ, pakiranje i projektna ponuda.",
    directAnswer: "Dobavljač komercijalnih tepiha za Hrvatsku treba potvrditi namjenu prostora, intenzitet prometa, podlogu, održavanje, uzorak i uvjete ugradnje. VISHOME priprema projektne opcije za hotele, urede i javne prostore, uz konačnu provjeru specifikacije prije narudžbe.",
    marketContext: "Hospitality projects in Zagreb, Split and coastal destinations often work to seasonal opening dates, making early sample and production approval important.",
    environmentNote: "Coastal humidity and inland seasonal changes require site-specific moisture checks and correct acclimation.",
    deliveryNote: "Confirm delivery access, roll lengths, pallet quantities and phased handover needs before selecting the transport plan.",
    applications: ["Hoteli i resorti", "Uredi", "Restorani i dvorane", "Javni hodnici"],
    localTerms: ["komercijalni tepih", "tepih ploče ured", "hotelski tepih dobavljač"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "hu",
    slug: "kereskedelmi-szonyeg-beszallito",
    language: "hu",
    hreflang: "hu-HU",
    openGraphLocale: "hu_HU",
    countryName: "Hungary",
    countryNameLocal: "Magyarország",
    title: "Kereskedelmi szőnyeg beszállító magyarországi projektekhez",
    metadataTitle: "Kereskedelmi szőnyeg beszállító Magyarország | VISHOME",
    metadataDescription: "Modulszőnyeg és szállodai padlószőnyeg magyar projektekhez. Minták, műszaki adatok, MOQ és projektárajánlat.",
    directAnswer: "Magyarországi kereskedelmi szőnyegprojektnél a használati osztályt, anyagot, hátoldalt, karbantartást, mintát és beépítési feltételeket együtt kell értékelni. A VISHOME projektalapú ajánlatot készít, a végleges megfelelőséget pedig a konkrét kiírás alapján kell ellenőrizni.",
    marketContext: "Budapest, Debrecen and Szeged projects may involve hotel renovation, office fit-out or public interiors with phased handover and replacement planning.",
    environmentNote: "Seasonal temperature variation requires protected transport, dry storage and acclimation in the final indoor conditions.",
    deliveryNote: "Use the approved roll and pallet schedule to compare transport costs and installation sequencing.",
    applications: ["Irodák", "Szállodák", "Konferencia- és rendezvényterek", "Közösségi terek"],
    localTerms: ["kereskedelmi szőnyeg", "modulszőnyeg iroda", "szállodai padlószőnyeg"],
    localIntentSections: [
      {
        title: "Helyi beszerzési szándék Magyarországon",
        summary: "A magyar projektvevők általában a használati osztályt, a beépítés ütemezését és a dokumentumokat egyeztetik először.",
        points: [
          "Budapest, Debrecen és Szeged projektjeinél gyakori a szállodai felújítás, az irodai fit-out és a közösségi terek szakaszos átadása.",
          "A végső jóváhagyás előtt érdemes együtt ellenőrizni a mintát, a hátoldalt, a karbantartási igényt és a használati osztályt.",
          "Téli szállításnál a száraz tárolás és az akklimatizáció külön pont legyen a projektlistán.",
        ],
      },
      {
        title: "A vevők által használt keresési kifejezések",
        summary: "Ezeket a kifejezéseket érdemes címsorokban, FAQ-ban és belső linkekben is visszahozni.",
        points: [
          "kereskedelmi szőnyeg — akkor használd, amikor a vevő projektbeszállítót keres, nem lakossági terméket.",
          "modulszőnyeg iroda — irodai fit-out és szakaszos csere keresésekhez.",
          "szállodai padlószőnyeg — szállodákhoz, konferenciaterekhez és közösségi terekhez.",
        ],
      },
      {
        title: "Mit kell tartalmaznia a helyi RFQ-nak",
        summary: "A pontos ajánlatot az adja, ha a helyszín, a mennyiség és a csomagolás is együtt érkezik.",
        points: [
          "A projekt városa, az épület típusa és az érintett funkciók.",
          "Mintaelvárás, szerkezet, hátoldal és a szükséges dokumentumok listája.",
          "Pontos szállítási adatok: tekercshossz, raklapszám, bruttó súly és átadás helye.",
        ],
      },
    ],
    productSet: "office",
  }),
  commercialPage({
    market: "cz",
    slug: "commercial-carpet-supplier-czech-republic",
    language: "en",
    hreflang: "en-CZ",
    openGraphLocale: "en_CZ",
    countryName: "Czech Republic",
    countryNameLocal: "Česko",
    title: "Commercial Carpet Supplier for Czech Republic Projects",
    metadataTitle: "Commercial Carpet Supplier Czech Republic | VISHOME",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Czech Republic projects. Review samples, technical data, MOQ, delivery and quotation inputs.",
    directAnswer: "A commercial carpet supplier for Czech Republic projects should help buyers compare fiber construction, backing, traffic class, maintenance and document requirements before the specification is frozen. Vishomecarpet supports project RFQs for offices, hotels and public interiors, but the final product selection must match the building specification.",
    marketContext: "Prague, Brno and Ostrava projects often require phased office fit-outs, hospitality refurbishment and clear replacement planning.",
    environmentNote: "Winter transport and heated interiors require dry storage and acclimation; subfloor moisture still needs to be checked on site.",
    deliveryNote: "Use confirmed carton, roll and pallet data together with the final delivery address when comparing freight options.",
    applications: ["Offices", "Hotels", "Education projects", "Public and shared areas"],
    localTerms: ["commercial carpet Czech Republic", "office carpet tiles Czech Republic", "hotel carpet supplier Czech Republic"],
    heroImage: "/images/markets/generated/central-europe-commercial-carpet-supplier-hub.webp",
    heroImageAlt: "Central Europe commercial carpet supplier sample review for office and hotel projects",
    productSet: "cold",
  }),
  commercialPage({
    market: "hu",
    slug: "commercial-carpet-supplier-hungary",
    language: "en",
    hreflang: "en-HU",
    openGraphLocale: "en_HU",
    countryName: "Hungary",
    countryNameLocal: "Magyarország",
    title: "Commercial Carpet Supplier for Hungary Projects",
    metadataTitle: "Commercial Carpet Supplier Hungary | VISHOME",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Hungary projects. Compare samples, technical files, MOQ, packing and project quotation needs.",
    directAnswer: "A commercial carpet supplier for Hungary should help buyers evaluate product construction, backing, traffic performance, maintenance needs and project documents before a quotation is approved. Vishomecarpet can prepare project options for offices, hotels and public interiors, but the nominated specification must still be checked by the buyer or consultant.",
    marketContext: "Budapest, Debrecen and Szeged projects often combine office refurbishment, hotel corridors and mixed-use interiors that need phased execution and replacement planning.",
    environmentNote: "Cold-weather delivery and conditioned interiors make dry storage and acclimation important before installation.",
    deliveryNote: "Confirm pallet count, roll length, delivery city and target installation window before comparing freight choices.",
    applications: ["Offices", "Hotels", "Corporate corridors", "Public interiors"],
    localTerms: ["commercial carpet Hungary", "office carpet tiles Hungary", "hotel carpet supplier Hungary"],
    heroImage: "/images/markets/generated/central-europe-commercial-carpet-supplier-hub.webp",
    heroImageAlt: "Central Europe commercial carpet supplier sample review for office and hotel projects",
    productSet: "cold",
  }),
  commercialPage({
    market: "kg",
    slug: "commercial-carpet-supplier-kyrgyzstan",
    language: "ru",
    hreflang: "ru-KG",
    openGraphLocale: "ru_KG",
    countryName: "Kyrgyzstan",
    countryNameLocal: "Кыргызстан",
    title: "Поставщик коммерческого ковролина для проектов в Кыргызстане",
    metadataTitle: "Коммерческий ковролин Кыргызстан | VISHOME",
    metadataDescription: "Ковровая плитка и гостиничный ковролин для проектов в Кыргызстане. Образцы, MOQ, параметры, упаковка и расчет поставки.",
    directAnswer: "Для проекта в Кыргызстане коммерческий ковролин следует выбирать по назначению, нагрузке, основе, обслуживанию, образцу и условиям монтажа. VISHOME готовит проектный расчет, а окончательные параметры подтверждаются после проверки требований объекта.",
    marketContext: "Projects in Bishkek, Osh and Jalal-Abad often require practical sample consolidation and clear separation between standard and custom production.",
    environmentNote: "Mountain climate and winter transport make protected storage and acclimation especially relevant before installation.",
    deliveryNote: "Compare land routes after confirming pallet size, weight, destination and whether the project needs one or several delivery stages.",
    applications: ["Гостиницы", "Офисы", "Торговые помещения", "Общественные залы"],
    localTerms: ["коммерческий ковролин Кыргызстан", "ковровая плитка Бишкек", "гостиничный ковролин"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "kz",
    slug: "kommerciyalyk-kilem-zhetkizushi",
    language: "kk",
    hreflang: "kk-KZ",
    openGraphLocale: "kk_KZ",
    countryName: "Kazakhstan",
    countryNameLocal: "Қазақстан",
    title: "Қазақстан жобаларына арналған коммерциялық кілем жеткізуші",
    metadataTitle: "Коммерциялық кілем жеткізуші Қазақстан | VISHOME",
    metadataDescription: "Қазақстандағы қонақүй, кеңсе және қоғамдық жобаларға кілем плиткасы мен рулон кілем. Үлгі, MOQ және жоба есебі.",
    directAnswer: "Қазақстандағы коммерциялық кілем жобасында материал, негіз, қозғалыс жүктемесі, үлгі, қызмет көрсету және жеткізу кезеңдері бірге тексерілуі керек. VISHOME жоба бойынша ұсыныс береді, ал соңғы сипаттама нысан талаптарына сай расталады.",
    marketContext: "Almaty, Astana and Shymkent projects may span long internal distances, so city-level destination and staged quantities should be defined in the RFQ.",
    environmentNote: "Cold winter transport requires protected packing, dry storage and adequate acclimation before installation.",
    deliveryNote: "Rail, road and multimodal options should be compared only after final pallet dimensions, weights and destination handling are known.",
    applications: ["Қонақүйлер", "Кеңселер", "Сауда орталықтары", "Қоғамдық дәліздер"],
    localTerms: ["коммерциялық кілем", "кілем плиткасы", "қонақүй кілемі"],
    productSet: "cold",
  }),
  commercialPage({
    market: "rs",
    slug: "dobavljac-komercijalnih-tepiha",
    language: "sr",
    hreflang: "sr-RS",
    openGraphLocale: "sr_RS",
    countryName: "Serbia",
    countryNameLocal: "Srbija",
    title: "Dobavljač komercijalnih tepiha za projekte u Srbiji",
    metadataTitle: "Dobavljač komercijalnih tepiha Srbija | VISHOME",
    metadataDescription: "Tepih ploče i hotelski tepisi za projekte u Srbiji. Uzorci, specifikacije, MOQ, pakovanje i projektna ponuda.",
    directAnswer: "Za komercijalni tepih u Srbiji kupci treba da provere namenu, opterećenje, vlakno, podlogu, održavanje, uzorak i uslove ugradnje. VISHOME priprema projektne opcije, dok se konačna specifikacija potvrđuje prema zahtevima objekta.",
    marketContext: "Belgrade, Novi Sad and Niš projects often combine office, hospitality and public-space requirements, making room schedules and phased quantities useful at quotation stage.",
    environmentNote: "Seasonal transport and indoor heating require protected storage and acclimation before adhesive installation.",
    deliveryNote: "Confirm customs documents, pallet or roll plan and destination access before comparing transport quotations.",
    applications: ["Kancelarije", "Hoteli", "Restorani i sale", "Javni prostori"],
    localTerms: ["komercijalni tepih", "tepih ploče kancelarija", "hotelski tepih dobavljač"],
    productSet: "office",
  }),
  commercialPage({
    market: "no",
    slug: "leverandor-kommersielle-tepper",
    language: "nb",
    hreflang: "nb-NO",
    openGraphLocale: "nb_NO",
    countryName: "Norway",
    countryNameLocal: "Norge",
    title: "Leverandør av kommersielle tepper til prosjekter i Norge",
    metadataTitle: "Leverandør kommersielle tepper Norge | VISHOME",
    metadataDescription: "Teppefliser og hotelltepper for norske prosjekter. Sammenlign prøver, akustikk, dokumentasjon, MOQ og prosjektlevering.",
    directAnswer: "En leverandør av kommersielle tepper til Norge bør kunne beskrive fiber, bakside, bruksklasse, akustikk, vedlikehold og dokumentasjon uten å anta at én løsning passer alle bygg. VISHOME tilbyr prosjektbaserte alternativer som må kontrolleres mot den aktuelle beskrivelsen.",
    marketContext: "Norwegian office, hospitality and public projects commonly prioritise acoustic comfort, replaceable zones and transparent technical documentation.",
    environmentNote: "Winter transport and heated interiors require dry storage and acclimation in stable room conditions before installation.",
    deliveryNote: "For Oslo, Bergen and Trondheim, use the final pallet and roll schedule to evaluate delivery access and freight alternatives.",
    applications: ["Kontorer", "Hoteller", "Undervisningsbygg", "Offentlige fellesarealer"],
    localTerms: ["kommersielle tepper", "teppefliser kontor", "hotellteppe leverandør"],
    productSet: "cold",
  }),
  commercialPage({
    market: "cz",
    slug: "dodavatel-komercnich-kobercu",
    language: "cs",
    hreflang: "cs-CZ",
    openGraphLocale: "cs_CZ",
    countryName: "Czech Republic",
    countryNameLocal: "Česko",
    title: "Dodavatel komerčních koberců pro projekty v Česku",
    metadataTitle: "Dodavatel komerčních koberců Česko | VISHOME",
    metadataDescription: "Kobercové čtverce a hotelové koberce pro české projekty. Vzorky, parametry, MOQ, dokumentace a projektová nabídka.",
    directAnswer: "Dodavatel komerčních koberců pro český projekt by měl doložit konstrukci, zátěž, podklad, údržbu, vzorky a požadované dokumenty. VISHOME připravuje projektové varianty, které je nutné před objednávkou porovnat s konkrétní specifikací.",
    marketContext: "Prague, Brno and Ostrava projects often include office refurbishment, hotels and public interiors with phased access and replacement planning.",
    environmentNote: "Seasonal transport requires dry storage and acclimation; substrate moisture must still be measured at the project site.",
    deliveryNote: "Compare freight using approved carton, pallet and roll data together with the final delivery address.",
    applications: ["Kanceláře", "Hotely", "Školy a univerzity", "Veřejné prostory"],
    localTerms: ["komerční koberce", "kobercové čtverce kancelář", "hotelový koberec dodavatel"],
    localIntentSections: [
      {
        title: "Lokální nákupní záměr v Česku",
        summary: "Čeští kupující obvykle začínají typem objektu, etapami přístupu na stavbu a požadovanými dokumenty.",
        points: [
          "Praha, Brno a Ostrava často řeší renovace kanceláří, hotely i veřejné interiéry s postupným předáváním.",
          "Před objednávkou je nutné sladit vzorek, konstrukci, podklad a seznam dokumentů s konkrétní specifikací projektu.",
          "U zimních dodávek je potřeba hlídat suché skladování a aklimatizaci před montáží.",
        ],
      },
      {
        title: "Výrazy, které používají kupující",
        summary: "Doplňte tyto fráze do nadpisů, FAQ i interních odkazů, aby text odpovídal reálnému vyhledávání.",
        points: [
          "komerční koberce — použijte, když zákazník hledá projektového dodavatele, ne retailovou nabídku.",
          "kobercové čtverce kancelář — použijte pro kancelářské fit-outy a výměnu zón.",
          "hotelový koberec dodavatel — použijte pro hotely, chodby a veřejné prostory.",
        ],
      },
      {
        title: "Co má obsahovat lokální RFQ",
        summary: "Kompletní RFQ pomůže porovnat nabídky podle stejného technického podkladu.",
        points: [
          "Město projektu, typ objektu a očekávané termíny montáže.",
          "Potvrzení vzorku, podkladu, provozní zátěže a požadovaných dokumentů.",
          "Údaje k logistice: balení, palety, hmotnost a finální dodací adresa.",
        ],
      },
    ],
    productSet: "office",
  }),
  commercialPage({
    market: "sk",
    slug: "dodavatel-komercnych-kobercov",
    language: "sk",
    hreflang: "sk-SK",
    openGraphLocale: "sk_SK",
    countryName: "Slovakia",
    countryNameLocal: "Slovensko",
    title: "Dodávateľ komerčných kobercov pre projekty na Slovensku",
    metadataTitle: "Dodávateľ komerčných kobercov Slovensko | VISHOME",
    metadataDescription: "Kobercové štvorce a hotelové koberce pre slovenské projekty. Vzorky, parametre, MOQ a projektová ponuka.",
    directAnswer: "Pri komerčnom koberci na Slovensku treba porovnať materiál, podklad, záťaž, údržbu, vzorku a podmienky montáže. VISHOME pripravuje projektové možnosti, pričom konečná špecifikácia sa potvrdzuje podľa požiadaviek konkrétnej stavby.",
    marketContext: "Bratislava, Košice and Žilina projects can involve office, hotel and public-space refurbishment with phased installation.",
    environmentNote: "Cold-season delivery requires protected storage and sufficient acclimation before installation.",
    deliveryNote: "Use the final packing list and destination to compare road, rail-linked or consolidated freight options.",
    applications: ["Kancelárie", "Hotely", "Vzdelávacie priestory", "Verejné chodby"],
    localTerms: ["komerčné koberce", "kobercové štvorce kancelária", "hotelový koberec dodávateľ"],
    productSet: "office",
  }),
  commercialPage({
    market: "si",
    slug: "dobavitelj-poslovnih-preprog",
    language: "sl",
    hreflang: "sl-SI",
    openGraphLocale: "sl_SI",
    countryName: "Slovenia",
    countryNameLocal: "Slovenija",
    title: "Dobavitelj poslovnih preprog za projekte v Sloveniji",
    metadataTitle: "Dobavitelj poslovnih preprog Slovenija | VISHOME",
    metadataDescription: "Tekstilne talne plošče in hotelske preproge za slovenske projekte. Vzorci, specifikacije, MOQ in projektna ponudba.",
    directAnswer: "Pri izbiri poslovne preproge v Sloveniji je treba preveriti uporabo, obremenitev, vlakno, podlago, vzdrževanje, vzorec in pogoje vgradnje. VISHOME pripravi projektne možnosti, končna specifikacija pa se potrdi glede na zahteve objekta.",
    marketContext: "Ljubljana, Maribor and Koper projects often include boutique hospitality, offices and public interiors where smaller phased quantities may matter.",
    environmentNote: "Coastal and inland conditions differ, so moisture testing and acclimation should follow the actual project environment.",
    deliveryNote: "Confirm roll lengths, pallet count, delivery access and installation sequence before selecting transport.",
    applications: ["Pisarne", "Hoteli", "Restavracije in dvorane", "Javni prostori"],
    localTerms: ["poslovne preproge", "tekstilne talne plošče", "hotelska preproga dobavitelj"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "sg",
    slug: "commercial-carpet-supplier-singapore",
    language: "en",
    hreflang: "en-SG",
    openGraphLocale: "en_SG",
    countryName: "Singapore",
    countryNameLocal: "Singapore",
    title: "Commercial Carpet Supplier for Singapore Projects",
    metadataTitle: "Commercial Carpet Supplier Singapore | Vishomecarpet",
    metadataDescription: "Commercial carpet tiles and hotel broadloom for Singapore offices, hotels and public interiors. Samples, MOQ and project quotation.",
    directAnswer: "Singapore commercial carpet projects should evaluate traffic, backing, fire-document requirements, maintenance access, indoor humidity and replacement strategy before approval. Vishomecarpet supplies project carpet options with samples and specification records, while final compliance must be confirmed for the nominated building and installation system.",
    marketContext: "High-rise offices, hotels and public interiors need clear lift access, delivery staging, room schedules and replacement planning before production quantities are fixed.",
    environmentNote: "Tropical humidity makes substrate testing, conditioned storage, acclimation and compatible adhesive selection critical site responsibilities.",
    deliveryNote: "Include delivery floor, loading access, pallet restrictions and phased handover dates when requesting the project quotation.",
    applications: ["High-rise offices", "Hotels and serviced apartments", "Retail interiors", "Airports and public buildings"],
    localTerms: ["commercial carpet supplier Singapore", "office carpet tiles Singapore", "hotel carpet supplier Singapore"],
    heroImage: "/images/markets/generated/singapore-casino-carpet-hero.webp",
    heroImageAlt: "Singapore commercial carpet supplier for casino and hospitality projects",
    localIntentSections: [
      {
        title: "Local procurement intent in Singapore",
        summary: "Singapore buyers usually move from compliance and access planning to sample approval before they lock production quantities.",
        points: [
          "High-rise offices, hotels and public interiors need lift booking, loading-bay access and floor-by-floor delivery planning.",
          "Fire-document requirements, indoor humidity, maintenance access and replacement strategy are usually checked before approval.",
          "A good RFQ should include delivery floor, project hours, pallet restrictions and the exact installation system.",
        ],
      },
      {
        title: "Search wording buyers actually use",
        summary: "Keep these phrases visible in headings, FAQ blocks and internal links so the page mirrors market language.",
        points: [
          "commercial carpet supplier Singapore — use this phrase when the buyer is looking for a project supplier, not a retail listing.",
          "office carpet tiles Singapore — use this phrase for office fit-out and phased replacement searches.",
          "hotel carpet supplier Singapore — use this phrase for hotel, serviced-apartment and public-interior projects.",
        ],
      },
      {
        title: "What to include in a Singapore RFQ",
        summary: "The more the quotation matches the site conditions, the easier it is to compare suppliers fairly.",
        points: [
          "Project type, delivery floor, lift access and loading sequence.",
          "Sample approval, fire documents, humidity control and replacement scope.",
          "Area, product format, packing plan and final handover timing.",
        ],
      },
    ],
    productSet: "humid",
  }),
  commercialPage({
    market: "sg",
    slug: "singapore-casino-carpet-supplier",
    language: "en",
    hreflang: "en-SG",
    openGraphLocale: "en_SG",
    countryName: "Singapore",
    countryNameLocal: "Singapore",
    title: "Singapore Casino Carpet Supplier for Oriental Flower Gaming Floors",
    metadataTitle: "Singapore Casino Carpet Supplier | Oriental Flower Carpet | Vishomecarpet",
    metadataDescription: "Custom oriental flower luxury casino carpet for Singapore gaming floors, VIP rooms, clubs and hotel entertainment areas. Review samples, MOQ, backing, shipping and quote.",
    directAnswer: "A Singapore casino carpet supplier should help buyers confirm price per SQM, sample timing, traffic level, oriental flower or custom pattern approval, visual soil control, backing stability, cleaning access, fire-document requirements and staged delivery before production. Vishomecarpet supplies custom luxury casino carpet options with high-density loop pile appearance, non-slip backing options, OEM design support, samples and quotation support for gaming floors, VIP rooms and hotel entertainment zones.",
    marketContext: "Singapore casino, hotel and entertainment projects often combine gaming floors, VIP rooms, clubs, lift lobbies and corridors in one procurement package. High-quality B2B buyers usually need sample speed, price basis, MOQ, exact quantity planning, distributor support, installation-team coordination, packing data, freight clarity and pattern approval before an internal purchasing decision can move forward.",
    environmentNote: "Indoor humidity, high air-conditioning use, heavy foot traffic, gaming chairs, service carts and frequent cleaning make backing selection, product acclimation, substrate checks and maintenance planning important before installation.",
    deliveryNote: "Send the Singapore site address, delivery floor, loading access, contact phone, project phase, roll or pallet restrictions, required sample date and target installation date when requesting a casino carpet quotation.",
    applications: ["Casino gaming floors", "VIP rooms and clubs", "Hotel entertainment zones", "Lift lobbies and gaming corridors"],
    localTerms: ["Singapore casino carpet", "casino carpet supplier Singapore", "custom gaming floor carpet Singapore", "oriental flower casino carpet", "hotel casino carpet Singapore", "casino carpet sample Singapore"],
    heroImage: "/images/markets/generated/singapore-casino-carpet-hero.webp",
    heroImageAlt: "Singapore casino carpet supplier for gaming floor and VIP hospitality zones",
    productSet: "casino",
  }),
  commercialPage({
    market: "ge",
    slug: "commercial-carpet-supplier-georgia",
    language: "ka",
    hreflang: "ka-GE",
    openGraphLocale: "ka_GE",
    countryName: "Georgia",
    countryNameLocal: "საქართველო",
    title: "კომერციული ხალიჩის მომწოდებელი საქართველოს პროექტებისთვის",
    metadataTitle: "კომერციული ხალიჩის მომწოდებელი საქართველო | VISHOME",
    metadataDescription: "ხალიჩის ფილები და სასტუმროს ხალიჩა საქართველოს პროექტებისთვის. ნიმუშები, MOQ, ტექნიკური მონაცემები და შეთავაზება.",
    directAnswer: "საქართველოში კომერციული ხალიჩის არჩევისას საჭიროა გამოყენების, დატვირთვის, საფუძვლის, მოვლის, ნიმუშისა და მონტაჟის პირობების ერთად შეფასება. VISHOME ამზადებს პროექტულ ვარიანტებს, ხოლო საბოლოო სპეციფიკაცია ობიექტის მოთხოვნებით დასტურდება.",
    marketContext: "Tbilisi, Batumi and Kutaisi projects range from urban offices to coastal hospitality, so the same carpet construction should not be assumed for every location.",
    environmentNote: "Coastal humidity and inland seasonal conditions require site-specific moisture checks and acclimation.",
    deliveryNote: "Define destination, packing plan and phased quantities before comparing Black Sea-linked and land transport options.",
    applications: ["სასტუმროები", "ოფისები", "რესტორნები და დარბაზები", "საჯარო სივრცეები"],
    localTerms: ["კომერციული ხალიჩა", "ხალიჩის ფილები", "სასტუმროს ხალიჩა"],
    productSet: "hospitality",
  }),
  commercialPage({
    market: "se",
    slug: "leverantor-kommersiella-mattor",
    language: "sv",
    hreflang: "sv-SE",
    openGraphLocale: "sv_SE",
    countryName: "Sweden",
    countryNameLocal: "Sverige",
    title: "Leverantör av kommersiella mattor för projekt i Sverige",
    metadataTitle: "Leverantör kommersiella mattor Sverige | VISHOME",
    metadataDescription: "Textilplattor och hotellmattor för svenska projekt. Jämför prover, akustik, dokumentation, MOQ och projektleverans.",
    directAnswer: "En leverantör av kommersiella mattor till Sverige bör kunna redovisa material, baksida, belastning, akustik, underhåll och dokumentation. VISHOME erbjuder projektbaserade alternativ, men slutlig produkt och dokumentation måste kontrolleras mot den aktuella kravspecifikationen.",
    marketContext: "Stockholm, Gothenburg and Malmö projects often prioritise acoustic comfort, replaceable modules and restrained design for offices, hotels and public interiors.",
    environmentNote: "Cold-season transport and heated buildings require dry storage and acclimation before installation.",
    deliveryNote: "Evaluate freight and site access after the approved carton, pallet and roll plan is available.",
    applications: ["Kontor", "Hotell", "Utbildningsmiljöer", "Offentliga lokaler"],
    localTerms: ["kommersiella mattor", "textilplattor kontor", "hotellmatta leverantör"],
    productSet: "cold",
  }),
  commercialPage({
    market: "by",
    slug: "postavshchik-kommercheskogo-kovrolina",
    language: "ru",
    hreflang: "ru-BY",
    openGraphLocale: "ru_BY",
    countryName: "Belarus",
    countryNameLocal: "Беларусь",
    title: "Поставщик коммерческого ковролина для проектов в Беларуси",
    metadataTitle: "Коммерческий ковролин Беларусь | VISHOME",
    metadataDescription: "Ковровая плитка и гостиничный ковролин для проектов в Беларуси. Образцы, MOQ, параметры и индивидуальный расчет поставки.",
    directAnswer: "Для проектов в Беларуси коммерческий ковролин нужно сравнивать по назначению, нагрузке, основе, обслуживанию, образцу и монтажной системе. VISHOME готовит проектные предложения, а доступность маршрута, оплаты и документов подтверждается отдельно для каждого заказа.",
    marketContext: "Minsk, Gomel and Brest projects may involve offices, hotels or public areas with different replacement and maintenance strategies.",
    environmentNote: "Cold-season transport requires protected packing, dry storage and adequate acclimation before installation.",
    deliveryNote: "Shipping, payment and document availability can change; confirm the destination and transaction route before relying on a preliminary quotation.",
    applications: ["Офисы", "Гостиницы", "Торговые помещения", "Общественные пространства"],
    localTerms: ["коммерческий ковролин Беларусь", "ковровая плитка Минск", "гостиничный ковролин"],
    productSet: "cold",
  }),
  commercialPage({
    market: "fi",
    slug: "kaupallisten-mattojen-toimittaja",
    language: "fi",
    hreflang: "fi-FI",
    openGraphLocale: "fi_FI",
    countryName: "Finland",
    countryNameLocal: "Suomi",
    title: "Kaupallisten mattojen toimittaja Suomen projekteihin",
    metadataTitle: "Kaupallisten mattojen toimittaja Suomi | VISHOME",
    metadataDescription: "Tekstiililaatat ja hotellimatot suomalaisiin projekteihin. Näytteet, akustiikka, asiakirjat, MOQ ja projektitoimitus.",
    directAnswer: "Suomen kaupallisissa mattoprojekteissa tulee vertailla materiaalia, taustarakennetta, käyttöluokkaa, akustiikkaa, huoltoa ja asiakirjoja. VISHOME tarjoaa projektikohtaisia vaihtoehtoja, jotka on tarkistettava kohteen lopullista määrittelyä vasten.",
    marketContext: "Helsinki, Tampere and Turku projects often value acoustic comfort, modular replacement and clear maintenance planning.",
    environmentNote: "Winter transport and heated interiors require dry storage and sufficient acclimation before installation.",
    deliveryNote: "Use approved packing dimensions and final site access information when comparing delivery options.",
    applications: ["Toimistot", "Hotellit", "Oppilaitokset", "Julkiset tilat"],
    localTerms: ["kaupalliset matot", "tekstiililaatat toimisto", "hotellimatto toimittaja"],
    productSet: "cold",
  }),
  commercialPage({
    market: "az",
    slug: "kommersiya-xalca-techizatcisi",
    language: "az",
    hreflang: "az-AZ",
    openGraphLocale: "az_AZ",
    countryName: "Azerbaijan",
    countryNameLocal: "Azərbaycan",
    title: "Azərbaycan layihələri üçün kommersiya xalça təchizatçısı",
    metadataTitle: "Kommersiya xalça təchizatçısı Azərbaycan | VISHOME",
    metadataDescription: "Azərbaycan otel, ofis və ictimai layihələri üçün xalça plitəsi və rulon xalça. Nümunə, MOQ və layihə təklifi.",
    directAnswer: "Azərbaycanda kommersiya xalçası seçərkən istifadə sahəsi, trafik, əsas, qulluq, nümunə və quraşdırma şərtləri birlikdə qiymətləndirilməlidir. VISHOME layihə üzrə variantlar hazırlayır, yekun xüsusiyyətlər isə obyekt tələblərinə əsasən təsdiqlənir.",
    marketContext: "Baku, Ganja and Sumqayit projects may include hotels, offices and event spaces where design approval and technical approval should be recorded separately.",
    environmentNote: "Warm conditions and different site environments require actual substrate testing, protected storage and product acclimation.",
    deliveryNote: "Confirm destination, pallet or roll plan, customs document needs and project stages before comparing freight options.",
    applications: ["Otellər", "Ofislər", "Restoran və tədbir zalları", "İctimai məkanlar"],
    localTerms: ["kommersiya xalçası", "ofis xalça plitəsi", "otel xalçası təchizatçısı"],
    productSet: "hospitality",
  }),
  goldPage({
    market: "pe",
    slug: "alfombra-mineria-oro-peru",
    language: "es",
    hreflang: "es-PE",
    openGraphLocale: "es_PE",
    countryName: "Peru",
    countryNameLocal: "Perú",
    title: "Alfombra para minería de oro y canaletas en Perú",
    metadataTitle: "Alfombra para minería de oro Perú | VISHOME",
    metadataDescription: "Alfombra PVC tipo miners moss para canaletas, plantas de lavado y recuperación aluvial en Perú. Muestras, espesores y rollos OEM.",
    directAnswer: "La alfombra para minería de oro en Perú debe seleccionarse según el ancho de la canaleta, altura disponible, clasificación previa del material, caudal y método de limpieza. VISHOME suministra rollos de PVC tipo miners moss en varios espesores; ninguna alfombra garantiza por sí sola una tasa de recuperación, por lo que se recomienda validar una muestra en el equipo real.",
    marketContext: "Compradores en Lima, Arequipa y regiones mineras pueden usar el material en canaletas, concentradores, trommels y plantas de lavado, siempre que la geometría del sistema sea compatible.",
    environmentNote: "El rendimiento depende del diseño de riffles, distribución del agua, granulometría y limpieza. La alfombra no sustituye las pruebas operativas del equipo.",
    deliveryNote: "Indique ancho útil, longitud, espesor, cantidad de rollos, color y destino para calcular empaque y transporte sin asumir dimensiones estándar incorrectas.",
    applications: ["Canaletas de lavado", "Plantas aluviales", "Trommels y concentradores", "Fabricantes de equipos mineros"],
    heroImage: "/images/markets/generated/peru-gold-mining-carpet-hero.webp",
    heroImageAlt: "Alfombra para mineria de oro en Peru con prueba de canaleta",
    localTerms: ["alfombra minería de oro Perú", "miners moss Perú", "alfombra para canaleta de oro"],
  }),
  goldPage({
    market: "co",
    slug: "alfombra-mineria-oro-colombia",
    language: "es",
    hreflang: "es-CO",
    openGraphLocale: "es_CO",
    countryName: "Colombia",
    countryNameLocal: "Colombia",
    title: "Alfombra para minería de oro y canaletas en Colombia",
    metadataTitle: "Alfombra para minería de oro Colombia | VISHOME",
    metadataDescription: "Alfombra PVC tipo miners moss para canaletas y recuperación aluvial en Colombia. Compare muestra, espesor, rollo, limpieza y OEM.",
    directAnswer: "Para seleccionar alfombra de minería de oro en Colombia, el comprador debe confirmar ancho de canaleta, espesor disponible, caudal, tamaño de alimentación y frecuencia de limpieza. VISHOME ofrece PVC tipo miners moss y muestras de prueba, pero la recuperación final depende del conjunto completo del equipo y de las condiciones operativas.",
    marketContext: "Proyectos y distribuidores en Bogotá, Medellín, Cali y zonas de operación pueden requerir rollos estándar o medidas adaptadas para canaletas, dragas, trommels y módulos de concentración.",
    environmentNote: "La humedad y el material arcilloso pueden cambiar la limpieza y el flujo; pruebe la configuración con material representativo antes de definir una compra mayor.",
    deliveryNote: "Incluya cantidad, espesor, ancho, longitud, color, tipo de respaldo y ciudad de entrega en la solicitud de cotización.",
    applications: ["Canaletas de recuperación", "Lavado aluvial", "Trommels y dragas", "Distribuidores de equipos"],
    heroImage: "/images/markets/generated/colombia-gold-mining-carpet-hero.webp",
    heroImageAlt: "Alfombra para mineria de oro en Colombia con rollos y canaleta",
    localTerms: ["alfombra minería de oro Colombia", "miners moss Colombia", "tapete para canaleta de oro"],
  }),
];

export const countryMarketPageMap = Object.fromEntries(
  countryMarketPages.map((page) => [`${page.market}/${page.slug}`, page]),
) as Record<string, CountryMarketPage>;

export const countryMarketLanguages = Object.fromEntries(
  countryMarketPages.map((page) => [page.path, page.language]),
) as Record<string, string>;

export function getCountryMarketLanguage(pathname: string) {
  const [market, slug] = pathname.split("/").filter(Boolean);
  if (!market || !slug || !countryMarketPageMap[`${market}/${slug}`]) return null;
  return countryMarketLanguages[`/${market}/${slug}`] ?? null;
}
