export type LandingLocale = "fr" | "es" | "ar" | "de" | "pt" | "ru" | "ja" | "ko";

export interface LocalizedLandingLabels {
  productsEyebrow: string;
  productsHeading: string;
  productDetails: string;
  moq: string;
  leadTime: string;
  price: string;
  benefitsHeading: string;
  applicationsHeading: string;
  processHeading: string;
  faqHeading: string;
  quoteButton: string;
  emailButton: string;
  targetMarkets: string;
}

export interface LocalizedLanding {
  locale: LandingLocale;
  slug: string;
  path: string;
  direction: "ltr" | "rtl";
  openGraphLocale: string;
  metadataTitle: string;
  metadataDescription: string;
  keywords: string[];
  alternates: Record<string, string>;
  eyebrow: string;
  title: string;
  introduction: string;
  targetMarkets: string;
  primaryProductId: string;
  heroAlt: string;
  quoteProduct: string;
  emailSubject: string;
  stats: { value: string; label: string }[];
  productsIntro: string;
  productCards: { id: string; name: string; description: string }[];
  benefits: { title: string; description: string }[];
  applications: string[];
  process: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
  finalTitle: string;
  finalText: string;
}

export const localizedLandingLabels: Record<LandingLocale, LocalizedLandingLabels> = {
  fr: {
    productsEyebrow: "Solutions recommandées",
    productsHeading: "Produits adaptés à votre projet",
    productDetails: "Voir la fiche technique",
    moq: "Commande minimum",
    leadTime: "Délai de production",
    price: "Prix FOB indicatif",
    benefitsHeading: "Une spécification claire avant la commande",
    applicationsHeading: "Applications",
    processHeading: "Du plan au chantier",
    faqHeading: "Questions fréquentes",
    quoteButton: "Demander un devis projet",
    emailButton: "Écrire au service commercial",
    targetMarkets: "Marchés concernés",
  },
  es: {
    productsEyebrow: "Soluciones recomendadas",
    productsHeading: "Productos para su proyecto",
    productDetails: "Ver ficha técnica",
    moq: "Pedido mínimo",
    leadTime: "Tiempo de producción",
    price: "Precio FOB orientativo",
    benefitsHeading: "Especificación antes del pedido",
    applicationsHeading: "Aplicaciones",
    processHeading: "Del requisito al envío",
    faqHeading: "Preguntas frecuentes",
    quoteButton: "Solicitar cotización",
    emailButton: "Enviar correo a ventas",
    targetMarkets: "Mercados objetivo",
  },
  ar: {
    productsEyebrow: "حلول موصى بها",
    productsHeading: "منتجات مناسبة لمشروعك",
    productDetails: "عرض المواصفات الفنية",
    moq: "الحد الأدنى للطلب",
    leadTime: "مدة الإنتاج",
    price: "سعر FOB استرشادي",
    benefitsHeading: "مواصفات واضحة قبل تأكيد الطلب",
    applicationsHeading: "مجالات الاستخدام",
    processHeading: "من المخطط إلى التوريد",
    faqHeading: "الأسئلة الشائعة",
    quoteButton: "طلب عرض سعر للمشروع",
    emailButton: "مراسلة فريق المبيعات",
    targetMarkets: "الأسواق المستهدفة",
  },
  de: {
    productsEyebrow: "Empfohlene Lösungen",
    productsHeading: "Produkte für Ihr Objekt",
    productDetails: "Technische Details",
    moq: "Mindestmenge",
    leadTime: "Produktionszeit",
    price: "FOB-Richtpreis",
    benefitsHeading: "Klare Spezifikation vor der Bestellung",
    applicationsHeading: "Einsatzbereiche",
    processHeading: "Vom Entwurf bis zur Lieferung",
    faqHeading: "Häufige Fragen",
    quoteButton: "Projektangebot anfordern",
    emailButton: "E-Mail an den Vertrieb",
    targetMarkets: "Zielmärkte",
  },
  pt: {
    productsEyebrow: "Soluções recomendadas",
    productsHeading: "Produtos para o seu projeto",
    productDetails: "Ver ficha técnica",
    moq: "Pedido mínimo",
    leadTime: "Prazo de produção",
    price: "Preço FOB indicativo",
    benefitsHeading: "Especificação antes da encomenda",
    applicationsHeading: "Aplicações",
    processHeading: "Do conceito à entrega",
    faqHeading: "Perguntas frequentes",
    quoteButton: "Pedir cotação do projeto",
    emailButton: "Enviar e-mail para vendas",
    targetMarkets: "Mercados prioritários",
  },
  ru: {
    productsEyebrow: "Рекомендуемые решения",
    productsHeading: "Продукция для вашего проекта",
    productDetails: "Технические данные",
    moq: "Минимальный заказ",
    leadTime: "Срок производства",
    price: "Ориентировочная цена FOB",
    benefitsHeading: "Согласование спецификации до заказа",
    applicationsHeading: "Области применения",
    processHeading: "От проекта до поставки",
    faqHeading: "Частые вопросы",
    quoteButton: "Запросить расчёт проекта",
    emailButton: "Написать в отдел продаж",
    targetMarkets: "Целевые рынки",
  },
  ja: {
    productsEyebrow: "おすすめ製品",
    productsHeading: "用途に合わせて選べる業務用カーペット",
    productDetails: "技術仕様を見る",
    moq: "最小注文数量",
    leadTime: "生産期間",
    price: "FOB参考価格",
    benefitsHeading: "発注前に確認するポイント",
    applicationsHeading: "主な用途",
    processHeading: "ご相談から納品まで",
    faqHeading: "よくある質問",
    quoteButton: "プロジェクト見積もりを依頼",
    emailButton: "営業担当へメール",
    targetMarkets: "対象市場",
  },
  ko: {
    productsEyebrow: "추천 제품",
    productsHeading: "프로젝트 용도에 맞는 상업용 카펫",
    productDetails: "기술 사양 보기",
    moq: "최소 주문 수량",
    leadTime: "생산 기간",
    price: "FOB 참고 가격",
    benefitsHeading: "발주 전에 확인해야 할 사항",
    applicationsHeading: "주요 적용 공간",
    processHeading: "상담부터 납품까지",
    faqHeading: "자주 묻는 질문",
    quoteButton: "프로젝트 견적 요청",
    emailButton: "영업팀에 이메일 보내기",
    targetMarkets: "대상 시장",
  },
};

export const localizedLandings: LocalizedLanding[] = [
  {
    locale: "fr",
    slug: "moquette-hotel-sur-mesure",
    path: "/fr/moquette-hotel-sur-mesure",
    direction: "ltr",
    openGraphLocale: "fr_FR",
    metadataTitle: "Moquette d'hôtel sur mesure | VISHOME",
    metadataDescription: "Moquette Axminster, moquette nylon imprimée et revêtement mural sur mesure pour hôtels, couloirs et salles de banquet. Échantillons, plans de rouleaux et devis export.",
    keywords: ["moquette hôtel", "moquette hôtelière sur mesure", "moquette couloir hôtel", "fabricant moquette Axminster", "moquette mur à mur"],
    alternates: {
      en: "/hotel-carpet",
      fr: "/fr/moquette-hotel-sur-mesure",
      ar: "/ar/sajad-fanadi-mukhasas",
      de: "/de/hotel-teppichboden",
      ru: "/ru/hotelnyy-kovrolin",
      "x-default": "/hotel-carpet",
    },
    eyebrow: "Fabrication directe pour projets hôteliers",
    title: "Moquette d'hôtel sur mesure pour chambres, couloirs et espaces publics",
    introduction: "VISHOME accompagne les hôtels, architectes, entreprises d'aménagement et distributeurs avec des moquettes Axminster, tuftées et imprimées adaptées au trafic, au budget et au calendrier du chantier. Nous préparons les échantillons, les coloris, les plans de rouleaux et les documents techniques avant la production.",
    targetMarkets: "France, République démocratique du Congo, Sénégal, Congo, Bénin et Afrique francophone",
    primaryProductId: "luxury-hotel-broadloom",
    heroAlt: "Moquette hôtelière Axminster sur mesure installée dans un couloir d'hôtel de luxe",
    quoteProduct: "Moquette d'hôtel sur mesure - marché francophone",
    emailSubject: "Demande de devis - moquette d'hôtel sur mesure",
    stats: [
      { value: "100 m²", label: "MOQ selon la solution" },
      { value: "4 m", label: "Largeur de rouleau disponible" },
      { value: "15-30 jours", label: "Production selon construction" },
      { value: "FOB / CIF / DAP", label: "Options logistiques" },
    ],
    productsIntro: "Le choix dépend de la zone, du niveau de trafic, du rendu attendu et du budget. Les spécifications finales sont confirmées après examen du plan et de l'usage.",
    productCards: [
      { id: "luxury-hotel-broadloom", name: "Moquette Axminster 80/20 laine-nylon", description: "Construction tissée haut de gamme pour hôtels cinq étoiles, couloirs, salons et salles de bal." },
      { id: "3d-printed-hotel-carpet", name: "Moquette nylon imprimée HD", description: "Motifs détaillés, couleurs personnalisées et mise en production plus rapide pour chambres et espaces publics." },
      { id: "custom-luxury-hotel-room-carpet", name: "Moquette sur mesure pour chambres", description: "Programme flexible à partir de 100 m² pour chambres, suites et rénovations hôtelières." },
    ],
    benefits: [
      { title: "Plan de zonage", description: "La construction, le poids de velours et le support sont choisis séparément pour chambres, couloirs, halls et salles de banquet." },
      { title: "Validation couleur", description: "Nous préparons un échantillon ou un strike-off afin de contrôler le motif, les couleurs et la texture avant la production en série." },
      { title: "Documents techniques", description: "Les exigences de classement feu, d'antistatisme et de trafic sont vérifiées produit par produit avant engagement." },
      { title: "Préparation export", description: "Les rouleaux, repères de pose, emballages et documents d'expédition sont organisés selon le phasage du chantier." },
    ],
    applications: ["Chambres et suites", "Couloirs d'hôtel", "Halls et réceptions", "Salles de banquet", "Restaurants et casinos", "Rénovations par phases"],
    process: [
      { title: "1. Cahier des charges", description: "Envoyez les plans, surfaces, zones, calendrier, références visuelles et normes requises." },
      { title: "2. Sélection", description: "Nous proposons la construction, le matériau, le grammage et une estimation FOB adaptée au projet." },
      { title: "3. Échantillon", description: "Le motif et la couleur sont approuvés sur échantillon avant le lancement de la production." },
      { title: "4. Production et expédition", description: "La fabrication, le contrôle qualité, l'emballage et les documents export suivent le planning confirmé." },
    ],
    faqs: [
      { question: "Quelle moquette choisir pour un couloir très fréquenté ?", answer: "Une construction commerciale en nylon ou Axminster avec un support stable est généralement recommandée. Le choix final dépend du trafic, du nettoyage, du classement feu et du budget." },
      { question: "Pouvez-vous reproduire le motif de notre architecte ?", answer: "Oui. Nous pouvons adapter un fichier de conception, préparer des coloris et produire un échantillon pour validation. Les droits d'utilisation du motif doivent appartenir au client." },
      { question: "Quel est le minimum de commande ?", answer: "Selon la construction, le minimum commence à 100 m² pour certains programmes sur mesure, 300 m² pour la moquette imprimée et 500 m² pour l'Axminster 80/20." },
      { question: "Livrez-vous en Afrique francophone ?", answer: "Oui. Nous préparons des offres FOB, CIF ou DAP selon la destination, le volume et les conditions locales. Le coût et le délai sont calculés au moment du devis." },
    ],
    finalTitle: "Recevez une recommandation adaptée à votre hôtel",
    finalText: "Indiquez le pays, les surfaces par zone, le type d'hôtel, le calendrier et les normes attendues. Notre équipe vous répondra avec une sélection, le MOQ, le délai et une estimation de prix.",
  },
  {
    locale: "fr",
    slug: "dalles-moquette-commerciales",
    path: "/fr/dalles-moquette-commerciales",
    direction: "ltr",
    openGraphLocale: "fr_FR",
    metadataTitle: "Dalles de moquette commerciales 50x50 | Fournisseur VISHOME",
    metadataDescription: "Dalles de moquette 50x50 en nylon pour bureaux, hôtels et espaces à fort trafic. Supports bitume ou PE sans PVC, échantillons et devis export.",
    keywords: ["dalles de moquette", "dalle moquette 50x50", "moquette bureau", "dalles moquette commerciales", "fournisseur dalle moquette"],
    alternates: {
      en: "/products/carpet-tiles",
      fr: "/fr/dalles-moquette-commerciales",
      es: "/es/losetas-alfombra-comerciales",
      ar: "/ar/balat-sajad-tijari",
      ru: "/ru/products/carpet-tiles/nylon-office-carpet-tile",
      "x-default": "/products/carpet-tiles",
    },
    eyebrow: "Dalles modulaires pour projets professionnels",
    title: "Dalles de moquette commerciales pour bureaux, hôtels et zones à fort trafic",
    introduction: "Nos dalles modulaires 50x50 cm sont conçues pour faciliter la pose, l'accès au plancher technique et le remplacement localisé. VISHOME propose des fibres nylon, des supports bitume ou PE sans PVC et des coloris adaptés aux bureaux, hôtels et bâtiments publics.",
    targetMarkets: "France, Belgique, Afrique francophone et projets tertiaires internationaux",
    primaryProductId: "commercial-nylon-tiles",
    heroAlt: "Dalles de moquette commerciales en nylon installées dans un bureau moderne",
    quoteProduct: "Dalles de moquette commerciales - marché francophone",
    emailSubject: "Demande de devis - dalles de moquette commerciales",
    stats: [
      { value: "50x50 cm", label: "Format modulaire courant" },
      { value: "Classe 33", label: "Options trafic commercial" },
      { value: "10-25 jours", label: "Selon modèle et quantité" },
      { value: "Bitume / PE", label: "Options de support" },
    ],
    productsIntro: "Comparez la fibre, le support, la réaction au feu, l'acoustique et la facilité de maintenance plutôt que le prix au mètre carré seul.",
    productCards: [
      { id: "commercial-nylon-tiles", name: "Dalles nylon commerciales", description: "Dalles 50x50 cm en nylon 6.6 pour bureaux, hôtels et zones de circulation soutenue." },
      { id: "luxury-hotel-carpet-tile-50x50cm", name: "Dalles 50x50 pour hôtels", description: "Solution modulaire haut de gamme pour chambres, couloirs légers et espaces professionnels." },
      { id: "ecocore-pe-backing-carpet-tiles", name: "Dalles EcoCore à support PE", description: "Alternative sans PVC avec support PE pour projets recherchant une composition de support différente." },
    ],
    benefits: [
      { title: "Remplacement localisé", description: "Une dalle endommagée peut être remplacée sans déposer toute la surface, ce qui réduit les interruptions d'exploitation." },
      { title: "Plan de calepinage", description: "Pose monolithique, quart de tour ou ashlar selon le motif, la forme de la pièce et la direction visuelle souhaitée." },
      { title: "Support adapté", description: "Bitume, PVC ou PE selon les contraintes de stabilité, de coût, de recyclabilité et de plancher technique." },
      { title: "Contrôle par lot", description: "Les références de couleur et de production sont suivies pour limiter les écarts entre livraisons et zones du chantier." },
    ],
    applications: ["Bureaux et sièges sociaux", "Hôtels et résidences", "Salles de réunion", "Commerces", "Établissements d'enseignement", "Planchers techniques"],
    process: [
      { title: "1. Surface et trafic", description: "Précisez les mètres carrés, le type de trafic, le support de sol et la méthode de nettoyage." },
      { title: "2. Échantillons", description: "Sélectionnez la fibre, le support, le coloris et le motif à partir d'échantillons physiques." },
      { title: "3. Quantités", description: "Nous calculons la quantité de projet, la réserve de maintenance et le conditionnement par carton." },
      { title: "4. Livraison", description: "La production et l'expédition sont planifiées par lot afin de préserver la cohérence du chantier." },
    ],
    faqs: [
      { question: "Nylon ou polypropylène : que choisir ?", answer: "Le nylon est généralement privilégié pour le trafic soutenu et la résilience. Le polypropylène peut convenir aux projets sensibles au budget avec un trafic modéré." },
      { question: "Quel support choisir ?", answer: "Le bitume offre une solution commerciale éprouvée. Le support PE peut répondre à certains objectifs sans PVC. La décision dépend du sol, du climat, des normes et du budget." },
      { question: "Faut-il prévoir des dalles de réserve ?", answer: "Oui. Une réserve de maintenance est recommandée pour les remplacements futurs. Le pourcentage dépend du plan, des découpes et de la politique d'entretien." },
      { question: "Pouvez-vous fournir les fiches techniques ?", answer: "Oui. Les fiches et documents disponibles sont transmis pour le modèle sélectionné. Les normes exigées doivent être précisées avant la commande." },
    ],
    finalTitle: "Spécifiez vos dalles de moquette avant de comparer les prix",
    finalText: "Envoyez la surface, le pays, le trafic, le format, le support souhaité et la date de livraison. Nous vous proposerons une sélection technique et commerciale cohérente.",
  },
  {
    locale: "fr",
    slug: "tapis-recuperation-or",
    path: "/fr/tapis-recuperation-or",
    direction: "ltr",
    openGraphLocale: "fr_FR",
    metadataTitle: "Tapis de récupération d'or | VISHOME",
    metadataDescription: "Tapis PVC miners moss pour sluice box, rampes de lavage, concentrateurs et récupération d'or alluvionnaire. Rouleaux 1x15 m, épaisseurs 10/15/20 mm.",
    keywords: ["tapis récupération or", "tapis rampe de lavage or", "miners moss", "tapis sluice box", "moquette pour lavage d'or"],
    alternates: {
      en: "/products/public-area/gold-mining-carpet-mat",
      fr: "/fr/tapis-recuperation-or",
      es: "/es/alfombra-mineria-oro",
      ru: "/ru/products/public-area/gold-mining-carpet-mat",
      "x-default": "/products/public-area/gold-mining-carpet-mat",
    },
    eyebrow: "Tapis PVC pour équipements de lavage",
    title: "Tapis de récupération d'or pour sluice box et rampes de lavage",
    introduction: "Le tapis VISHOME miners moss possède une structure PVC en boucles et nervures destinée à retenir les particules lourdes dans les rampes de lavage. Il convient aux chercheurs d'or, distributeurs d'équipements, dragues, trommels, concentrateurs et installations de lavage alluvionnaire.",
    targetMarkets: "RDC, Congo, Sénégal, Mali, Burkina Faso, Guinée et réseaux miniers francophones",
    primaryProductId: "gold-mining-carpet-mat",
    heroAlt: "Tapis PVC miners moss installé dans une rampe de lavage pour récupération d'or",
    quoteProduct: "Tapis de récupération d'or miners moss - marché francophone",
    emailSubject: "Demande de devis - tapis de récupération d'or",
    stats: [
      { value: "1 x 15 m", label: "Rouleau standard" },
      { value: "10 / 15 / 20 mm", label: "Épaisseurs disponibles" },
      { value: "100 rouleaux", label: "MOQ usine" },
      { value: "15-25 jours", label: "Délai de production" },
    ],
    productsIntro: "La rétention dépend de l'ensemble du système : débit d'eau, pente, classification du matériau, riffles et épaisseur du tapis. Nous fournissons le tapis, mais aucun taux de récupération fixe ne peut être garanti sans essai sur votre installation.",
    productCards: [
      { id: "gold-mining-carpet-mat", name: "Tapis miners moss pour sluice box", description: "Rouleau PVC nervuré pour rampes de lavage, dragues, trommels, concentrateurs et séparateurs." },
    ],
    benefits: [
      { title: "Trois épaisseurs", description: "10 mm pour équipements légers, 15 mm pour usage polyvalent et 20 mm pour des systèmes nécessitant une structure plus profonde." },
      { title: "Découpe et dimensions", description: "Le rouleau standard mesure 1 x 15 m. Des dimensions, couleurs, supports et emballages OEM peuvent être étudiés." },
      { title: "Nettoyage réutilisable", description: "La structure PVC peut être retirée, rincée et remise en service selon le protocole de l'exploitant." },
      { title: "Approvisionnement B2B", description: "Production en volume pour fabricants de sluice box, distributeurs miniers et exploitants avec contrôle de lot." },
    ],
    applications: ["Sluice box", "Rampes de lavage", "Dagues et dragues", "Trommels", "Concentrateurs", "Lavage d'or alluvionnaire"],
    process: [
      { title: "1. Décrire l'équipement", description: "Indiquez la largeur du canal, le débit, la pente, le type de riffles et la granulométrie." },
      { title: "2. Choisir l'épaisseur", description: "Nous recommandons une option 10, 15 ou 20 mm selon la configuration communiquée." },
      { title: "3. Tester", description: "Un échantillon permet de vérifier la compatibilité mécanique avant une commande en volume." },
      { title: "4. Produire et expédier", description: "Les rouleaux sont contrôlés, emballés et expédiés selon les conditions FOB, CIF ou DAP convenues." },
    ],
    faqs: [
      { question: "Ce tapis garantit-il un taux de récupération précis ?", answer: "Non. Le résultat dépend du minerai, de la classification, du débit, de la pente et des riffles. Le tapis doit être testé dans votre système complet." },
      { question: "Quelle épaisseur choisir ?", answer: "10 mm convient aux rampes légères, 15 mm est polyvalent et 20 mm offre une structure plus profonde. La recommandation finale nécessite les paramètres de votre équipement." },
      { question: "Peut-on commander une largeur personnalisée ?", answer: "Oui, des dimensions et emballages personnalisés peuvent être étudiés selon la quantité. Le format standard est un rouleau de 1 x 15 m." },
      { question: "Livrez-vous en Afrique ?", answer: "Oui. Nous calculons les options FOB, CIF ou DAP selon le port, le pays, le volume et les conditions de transport du moment." },
    ],
    finalTitle: "Envoyez les dimensions de votre rampe de lavage",
    finalText: "Précisez la largeur, la longueur, l'épaisseur souhaitée, la quantité et le pays de destination. Nous vous répondrons avec l'option adaptée, le MOQ, le délai et le coût logistique disponible.",
  },
  {
    locale: "es",
    slug: "alfombra-mineria-oro",
    path: "/es/alfombra-mineria-oro",
    direction: "ltr",
    openGraphLocale: "es_PE",
    metadataTitle: "Alfombra para minería de oro y canaleta sluice | VISHOME",
    metadataDescription: "Alfombra PVC miners moss para canaletas, lavado aluvial y recuperación de oro. Rollos de 1x15 m, espesores de 10/15/20 mm y suministro mayorista.",
    keywords: ["alfombra para minería de oro", "alfombra para canaleta de oro", "miners moss", "tapete para lavar oro", "alfombra sluice box"],
    alternates: {
      en: "/products/public-area/gold-mining-carpet-mat",
      es: "/es/alfombra-mineria-oro",
      fr: "/fr/tapis-recuperation-or",
      ru: "/ru/products/public-area/gold-mining-carpet-mat",
      "x-default": "/products/public-area/gold-mining-carpet-mat",
    },
    eyebrow: "Suministro directo para equipos de lavado",
    title: "Alfombra para minería de oro, canaletas y recuperación aluvial",
    introduction: "La alfombra miners moss de VISHOME utiliza una estructura de bucles y nervaduras de PVC para retener partículas pesadas dentro de canaletas y plantas de lavado. Está dirigida a mineros, fabricantes de equipos, distribuidores y operaciones de oro aluvial que necesitan rollos uniformes y suministro por volumen.",
    targetMarkets: "Perú, Bolivia, Colombia, México, Chile y distribuidores mineros de habla hispana",
    primaryProductId: "gold-mining-carpet-mat",
    heroAlt: "Alfombra PVC miners moss para canaleta y recuperación de oro aluvial",
    quoteProduct: "Alfombra para minería de oro - mercado hispanohablante",
    emailSubject: "Solicitud de cotización - alfombra para minería de oro",
    stats: [
      { value: "1 x 15 m", label: "Rollo estándar" },
      { value: "10 / 15 / 20 mm", label: "Espesores disponibles" },
      { value: "100 rollos", label: "Pedido mínimo" },
      { value: "15-25 días", label: "Producción estimada" },
    ],
    productsIntro: "El rendimiento depende del mineral, el caudal, la pendiente, la clasificación y el sistema de rifles. La alfombra debe evaluarse como parte de la canaleta completa y no se ofrece una tasa de recuperación universal.",
    productCards: [
      { id: "gold-mining-carpet-mat", name: "Alfombra miners moss para canaleta", description: "Rollo de PVC para canaletas, dragas, trommels, concentradores y plantas de lavado de oro." },
    ],
    benefits: [
      { title: "Opciones de espesor", description: "10 mm para equipos ligeros, 15 mm para uso general y 20 mm para configuraciones que requieren mayor profundidad." },
      { title: "Formato para distribución", description: "Rollo estándar de 1 x 15 m con opciones de color, medida, respaldo y embalaje OEM según volumen." },
      { title: "Mantenimiento sencillo", description: "La estructura de PVC puede retirarse y lavarse conforme al procedimiento de recuperación de cada operación." },
      { title: "Control de producción", description: "Suministro por lote para distribuidores, fabricantes de canaletas y proyectos que requieren consistencia dimensional." },
    ],
    applications: ["Canaletas sluice", "Plantas de lavado", "Dragas", "Trommels", "Concentradores", "Minería aluvial"],
    process: [
      { title: "1. Datos de la canaleta", description: "Comparta ancho, largo, caudal, pendiente, tipo de rifles y material procesado." },
      { title: "2. Selección", description: "Recomendamos espesor, formato y cantidad según la configuración comunicada." },
      { title: "3. Muestra", description: "La muestra permite comprobar ajuste y comportamiento antes de una compra de volumen." },
      { title: "4. Producción", description: "Confirmamos lote, embalaje, plazo y alternativa logística FOB, CIF o DAP." },
    ],
    faqs: [
      { question: "¿Cuál espesor debo usar?", answer: "Depende del caudal y del diseño de la canaleta. 10 mm se usa en equipos ligeros, 15 mm es una opción general y 20 mm ofrece una estructura más profunda." },
      { question: "¿Garantiza un porcentaje de recuperación?", answer: "No. La recuperación depende de todo el sistema y del material procesado. Recomendamos realizar una prueba con su configuración real." },
      { question: "¿Pueden cotizar un contenedor completo?", answer: "Sí. Indique cantidad, espesor, puerto o ciudad de destino y condiciones preferidas. Prepararemos capacidad, embalaje y costo logístico actualizado." },
      { question: "¿Ofrecen medidas personalizadas?", answer: "Sí, pueden evaluarse anchos, largos, colores, respaldo y embalaje OEM. El formato estándar es 1 x 15 m." },
    ],
    finalTitle: "Solicite precio para su canaleta o distribución minera",
    finalText: "Envíe medidas, espesor, cantidad, país y destino. Le responderemos con precio FOB, pedido mínimo, plazo de producción y opciones de transporte.",
  },
  {
    locale: "es",
    slug: "losetas-alfombra-comerciales",
    path: "/es/losetas-alfombra-comerciales",
    direction: "ltr",
    openGraphLocale: "es_ES",
    metadataTitle: "Losetas de alfombra comerciales 50x50 | Proveedor VISHOME",
    metadataDescription: "Losetas de alfombra de nylon para oficinas, hoteles y alto tráfico. Formato 50x50, respaldos bitumen o PE, muestras y cotización para proyectos.",
    keywords: ["losetas de alfombra", "alfombra modular 50x50", "alfombra para oficina", "losetas comerciales", "proveedor carpet tiles"],
    alternates: {
      en: "/products/carpet-tiles",
      es: "/es/losetas-alfombra-comerciales",
      fr: "/fr/dalles-moquette-commerciales",
      ar: "/ar/balat-sajad-tijari",
      ru: "/ru/products/carpet-tiles/nylon-office-carpet-tile",
      "x-default": "/products/carpet-tiles",
    },
    eyebrow: "Pavimento modular para proyectos B2B",
    title: "Losetas de alfombra comerciales para oficinas, hoteles y alto tráfico",
    introduction: "Las losetas modulares permiten instalar por zonas, acceder a pisos técnicos y reemplazar piezas dañadas sin retirar toda la superficie. VISHOME suministra opciones de nylon con respaldo bituminoso o PE para oficinas, hoteles, comercios y edificios profesionales.",
    targetMarkets: "España, México, Colombia, Perú, Chile y distribuidores de América Latina",
    primaryProductId: "commercial-nylon-tiles",
    heroAlt: "Losetas de alfombra comerciales 50x50 instaladas en oficina moderna",
    quoteProduct: "Losetas de alfombra comerciales - mercado hispanohablante",
    emailSubject: "Solicitud de cotización - losetas de alfombra comerciales",
    stats: [
      { value: "50x50 cm", label: "Formato modular" },
      { value: "Clase 33", label: "Opciones de alto tráfico" },
      { value: "10-25 días", label: "Según modelo y cantidad" },
      { value: "Bitumen / PE", label: "Respaldos disponibles" },
    ],
    productsIntro: "Para comparar correctamente deben revisarse fibra, densidad, respaldo, reacción al fuego, acústica y costo de mantenimiento, no solamente el precio inicial.",
    productCards: [
      { id: "commercial-nylon-tiles", name: "Loseta comercial de nylon", description: "Nylon 6.6 en formato 50x50 para circulación intensa, oficinas y proyectos hoteleros." },
      { id: "ecocore-pe-backing-carpet-tiles", name: "Loseta EcoCore con respaldo PE", description: "Alternativa sin PVC para proyectos que especifican respaldo de polietileno." },
      { id: "nylon-office-carpet-tile", name: "Loseta de nylon para oficina", description: "Solución modular para oficinas, salas de reunión y espacios corporativos." },
    ],
    benefits: [
      { title: "Mantenimiento por zonas", description: "Las piezas con manchas o desgaste pueden sustituirse localmente sin interrumpir todo el espacio." },
      { title: "Diseño modular", description: "Instalación monolítica, en cuarto de vuelta o desplazada según patrón y dirección visual." },
      { title: "Respaldo adecuado", description: "La elección entre bitumen y PE depende del piso, el clima, la estabilidad y los objetivos del proyecto." },
      { title: "Reserva de mantenimiento", description: "Calculamos cortes y unidades adicionales para facilitar reparaciones futuras con el mismo lote." },
    ],
    applications: ["Oficinas", "Hoteles", "Coworking", "Salas de reunión", "Comercios", "Pisos técnicos"],
    process: [
      { title: "1. Definir el uso", description: "Comparta superficie, tráfico, base del piso, método de limpieza y norma requerida." },
      { title: "2. Elegir muestra", description: "Seleccione fibra, respaldo, color y patrón mediante muestras físicas." },
      { title: "3. Calcular cantidades", description: "Se consideran área neta, cortes, patrón y reserva de mantenimiento." },
      { title: "4. Producir por lote", description: "La producción y el envío se organizan por lote para mantener consistencia de color." },
    ],
    faqs: [
      { question: "¿Nylon o polipropileno?", answer: "El nylon ofrece mejor resiliencia para tráfico intenso. El polipropileno puede ser adecuado para presupuestos ajustados y uso moderado." },
      { question: "¿Qué respaldo conviene?", answer: "El bitumen es una solución comercial común. El PE puede utilizarse cuando el proyecto solicita una opción sin PVC. Deben revisarse suelo y clima." },
      { question: "¿Puedo pedir muestras?", answer: "Sí. Confirme color, respaldo, cantidad y dirección de entrega para preparar la opción de muestra disponible." },
      { question: "¿Incluyen documentación técnica?", answer: "Se entregan los documentos disponibles para el producto seleccionado. Indique previamente la norma de fuego o requisito específico del proyecto." },
    ],
    finalTitle: "Compare una especificación completa, no solo el precio",
    finalText: "Indique metros cuadrados, país, tráfico, respaldo, color y fecha objetivo. Prepararemos una selección con MOQ, plazo y precio de proyecto.",
  },
  {
    locale: "ar",
    slug: "sajad-fanadi-mukhasas",
    path: "/ar/sajad-fanadi-mukhasas",
    direction: "rtl",
    openGraphLocale: "ar_AE",
    metadataTitle: "سجاد فنادق مخصص للممرات والقاعات | مصنع VISHOME",
    metadataDescription: "سجاد أكسمينستر وسجاد نايلون مطبوع للفنادق والممرات وقاعات الولائم. تصميم مخصص، عينات، مخططات رولات وعروض توريد للمشاريع.",
    keywords: ["سجاد فنادق", "سجاد ممرات الفنادق", "سجاد قاعات الولائم", "سجاد أكسمينستر", "مصنع سجاد فندقي"],
    alternates: {
      en: "/hotel-carpet",
      ar: "/ar/sajad-fanadi-mukhasas",
      fr: "/fr/moquette-hotel-sur-mesure",
      de: "/de/hotel-teppichboden",
      ru: "/ru/hotelnyy-kovrolin",
      "x-default": "/hotel-carpet",
    },
    eyebrow: "توريد مباشر لمشاريع الضيافة",
    title: "سجاد فنادق مخصص للغرف والممرات وقاعات الولائم",
    introduction: "تدعم VISHOME مشاريع الفنادق وشركات التصميم والمقاولين والموزعين بخيارات أكسمينستر، والسجاد المطبوع عالي الدقة، والسجاد المصمم حسب المشروع. يتم اعتماد التصميم والألوان والمواصفات الفنية وخطة الرولات قبل بدء الإنتاج.",
    targetMarkets: "الإمارات، السعودية، العراق، عُمان، الكويت، قطر وأسواق الخليج",
    primaryProductId: "3d-printed-banquet-hall-carpet",
    heroAlt: "سجاد فندقي مطبوع ومخصص داخل قاعة ولائم فاخرة",
    quoteProduct: "سجاد فنادق وقاعات مخصص - السوق العربي",
    emailSubject: "طلب عرض سعر - سجاد فنادق مخصص",
    stats: [
      { value: "100 م²", label: "حد أدنى لبعض الحلول" },
      { value: "4 م", label: "عرض الرول المتاح" },
      { value: "15-30 يومًا", label: "حسب نوع التصنيع" },
      { value: "FOB / CIF / DAP", label: "خيارات الشحن" },
    ],
    productsIntro: "يتم اختيار نوع الخامة والبنية والوزن والظهر وفق منطقة الاستخدام وحركة المرور ومتطلبات الحريق والميزانية، ثم تثبيت المواصفات النهائية في عرض المشروع.",
    productCards: [
      { id: "3d-printed-banquet-hall-carpet", name: "سجاد مطبوع لقاعات الولائم", description: "تصميمات عالية الدقة وألوان مخصصة لقاعات المناسبات والمؤتمرات والفنادق." },
      { id: "luxury-hotel-broadloom", name: "سجاد أكسمينستر 80/20", description: "سجاد منسوج فاخر من الصوف والنايلون للممرات والردهات والفنادق الراقية." },
      { id: "custom-luxury-hotel-room-carpet", name: "سجاد غرف فندقية حسب الطلب", description: "برنامج مرن للغرف والأجنحة والتجديدات يبدأ من 100 متر مربع لبعض المواصفات." },
    ],
    benefits: [
      { title: "تحديد كل منطقة", description: "تتم مواصفة الغرف والممرات والردهات وقاعات الولائم بشكل منفصل وفق الحركة والصيانة." },
      { title: "اعتماد اللون والتصميم", description: "يمكن إعداد عينة للتأكد من النقشة والألوان والملمس قبل الإنتاج الكامل." },
      { title: "توثيق فني", description: "تُراجع متطلبات مقاومة الحريق والكهرباء الساكنة والاستخدام التجاري حسب المنتج المختار." },
      { title: "تجهيز للتصدير", description: "تنظيم الرولات والملصقات والتعبئة ومستندات الشحن وفق مراحل المشروع." },
    ],
    applications: ["غرف وأجنحة الفنادق", "ممرات الفنادق", "الردهات والاستقبال", "قاعات الولائم", "المطاعم والنوادي", "مشاريع التجديد"],
    process: [
      { title: "1. متطلبات المشروع", description: "أرسل المخططات والمساحات والمناطق والجدول الزمني والصور المرجعية والمعايير المطلوبة." },
      { title: "2. الاختيار الفني", description: "نقترح الخامة والبنية والوزن والعرض والسعر المبدئي المناسب." },
      { title: "3. اعتماد العينة", description: "يتم تأكيد اللون والتصميم والمواصفة من خلال العينة قبل الإنتاج." },
      { title: "4. الإنتاج والتوريد", description: "يبدأ الإنتاج والفحص والتعبئة والشحن وفق الجدول المتفق عليه." },
    ],
    faqs: [
      { question: "ما النوع المناسب لممرات الفنادق؟", answer: "غالبًا يُستخدم نايلون تجاري كثيف أو أكسمينستر ثابت الأبعاد. القرار النهائي يعتمد على الحركة والتنظيف ومتطلبات الحريق والميزانية." },
      { question: "هل يمكن تنفيذ تصميم خاص بالفندق؟", answer: "نعم. يمكن تعديل ملف التصميم والألوان وإعداد عينة للاعتماد، بشرط أن يمتلك العميل حق استخدام التصميم." },
      { question: "ما الحد الأدنى للطلب؟", answer: "يبدأ من 100 م² لبعض برامج الغرف، و200 م² لبعض سجاد القاعات، و300 م² للسجاد المطبوع، و500 م² لأكسمينستر 80/20." },
      { question: "هل تتوفر شهادات مقاومة الحريق؟", answer: "تتوفر مستندات حسب المنتج والمواصفة. يجب تحديد المعيار المطلوب قبل الطلب حتى نطابق الحل المناسب." },
    ],
    finalTitle: "احصل على توصية مناسبة لمشروع الفندق",
    finalText: "أرسل الدولة والمساحات حسب المنطقة ونوع الفندق وموعد التسليم والمعايير المطلوبة. سنرسل المنتج المقترح والحد الأدنى والمدة والسعر المبدئي.",
  },
  {
    locale: "ar",
    slug: "balat-sajad-tijari",
    path: "/ar/balat-sajad-tijari",
    direction: "rtl",
    openGraphLocale: "ar_AE",
    metadataTitle: "بلاط سجاد تجاري 50x50 للمكاتب والفنادق | VISHOME",
    metadataDescription: "بلاط سجاد نايلون تجاري للمكاتب والفنادق والمناطق عالية الحركة. مقاس 50x50 وخيارات ظهر بيتومين أو PE وعينات للمشاريع.",
    keywords: ["بلاط سجاد", "سجاد مكاتب 50x50", "بلاط موكيت تجاري", "سجاد مكاتب", "مصنع بلاط سجاد"],
    alternates: {
      en: "/products/carpet-tiles",
      ar: "/ar/balat-sajad-tijari",
      fr: "/fr/dalles-moquette-commerciales",
      es: "/es/losetas-alfombra-comerciales",
      ru: "/ru/products/carpet-tiles/nylon-office-carpet-tile",
      "x-default": "/products/carpet-tiles",
    },
    eyebrow: "أرضيات وحدات للمشاريع التجارية",
    title: "بلاط سجاد تجاري للمكاتب والفنادق والمناطق عالية الحركة",
    introduction: "يوفر بلاط السجاد سهولة التركيب فوق الأرضيات التقنية وإمكانية استبدال القطع المتضررة دون تغيير المساحة بالكامل. تقدم VISHOME خيارات نايلون بمقاس 50x50 سم مع ظهر بيتومين أو PE للمكاتب والفنادق والمباني التجارية.",
    targetMarkets: "الإمارات، العراق، السعودية، عُمان، الكويت وقطر",
    primaryProductId: "luxury-hotel-carpet-tile-50x50cm",
    heroAlt: "بلاط سجاد تجاري 50x50 داخل مكتب حديث",
    quoteProduct: "بلاط سجاد تجاري - السوق العربي",
    emailSubject: "طلب عرض سعر - بلاط سجاد تجاري",
    stats: [
      { value: "50x50 سم", label: "مقاس وحدات شائع" },
      { value: "Class 33", label: "خيارات للحركة العالية" },
      { value: "10-25 يومًا", label: "حسب الموديل والكمية" },
      { value: "Bitumen / PE", label: "خيارات الظهر" },
    ],
    productsIntro: "المقارنة الصحيحة تشمل نوع الألياف والكثافة والظهر ومقاومة الحريق والأداء الصوتي والصيانة، وليس سعر المتر فقط.",
    productCards: [
      { id: "luxury-hotel-carpet-tile-50x50cm", name: "بلاط سجاد فاخر 50x50", description: "حل وحدات للفنادق والمكاتب والمساحات المهنية مع خيارات ألوان متعددة." },
      { id: "commercial-nylon-tiles", name: "بلاط نايلون تجاري", description: "نايلون 6.6 للمكاتب والفنادق والمناطق التي تتطلب مرونة عالية." },
      { id: "nylon-office-carpet-tile", name: "بلاط سجاد للمكاتب", description: "تصميم عملي لغرف الاجتماعات والمكاتب والمساحات الإدارية." },
    ],
    benefits: [
      { title: "صيانة موضعية", description: "يمكن استبدال القطع المتضررة أو المتسخة دون إزالة الأرضية بالكامل." },
      { title: "مرونة التصميم", description: "تركيب باتجاه واحد أو ربع دورة أو بنمط متدرج حسب التصميم المطلوب." },
      { title: "اختيار الظهر", description: "يتم اختيار البيتومين أو PE وفق الأرضية والمناخ والثبات ومتطلبات المشروع." },
      { title: "احتياطي للصيانة", description: "تُحسب كمية إضافية من نفس دفعة الإنتاج لاستبدالات المستقبل." },
    ],
    applications: ["المكاتب", "الفنادق", "غرف الاجتماعات", "مساحات العمل المشتركة", "المتاجر", "الأرضيات التقنية"],
    process: [
      { title: "1. تحديد الاستخدام", description: "أرسل المساحة وحركة المرور ونوع الأرضية وطريقة التنظيف والمعيار المطلوب." },
      { title: "2. اختيار العينة", description: "حدد الألياف والظهر واللون والنمط من العينات المتاحة." },
      { title: "3. حساب الكمية", description: "نحسب المساحة والقصّ ونمط التركيب واحتياطي الصيانة." },
      { title: "4. الإنتاج بالشحنة", description: "يتم الإنتاج والتعبئة حسب الدفعة للحفاظ على اتساق اللون." },
    ],
    faqs: [
      { question: "هل النايلون أفضل من البولي بروبلين؟", answer: "النايلون أكثر مرونة عادةً للحركة العالية. يمكن استخدام البولي بروبلين في المشاريع الاقتصادية ذات الحركة المتوسطة." },
      { question: "ما نوع الظهر المناسب؟", answer: "البيتومين خيار تجاري شائع، بينما يوفر PE خيارًا بدون PVC لبعض المشاريع. يعتمد الاختيار على الأرضية والمناخ." },
      { question: "هل يمكن طلب عينات؟", answer: "نعم. أرسل اللون ونوع الظهر والكمية والدولة حتى نحدد خيار العينة والشحن." },
      { question: "هل توفرون البيانات الفنية؟", answer: "نعم، نوفر المستندات المتاحة للموديل المختار. يجب تحديد معيار الحريق أو المتطلبات الخاصة قبل الطلب." },
    ],
    finalTitle: "حدد مواصفة بلاط السجاد قبل مقارنة الأسعار",
    finalText: "أرسل المساحة والدولة والحركة ونوع الظهر واللون وموعد التوريد. سنقترح خيارًا مع الحد الأدنى والمدة والسعر.",
  },
  {
    locale: "de",
    slug: "hotel-teppichboden",
    path: "/de/hotel-teppichboden",
    direction: "ltr",
    openGraphLocale: "de_DE",
    metadataTitle: "Hotel-Teppichboden nach Maß | Axminster & Druckteppich VISHOME",
    metadataDescription: "Maßgefertigter Hotel-Teppichboden für Zimmer, Flure, Lobby und Bankettsaal. Axminster, HD-Druck und Natur-Sisal mit Mustern, Rollenplanung und Exportangebot.",
    keywords: ["Hotel Teppichboden", "Teppichboden Hotel Flur", "Axminster Teppich", "Hotelteppich nach Maß", "Sisal Teppich Gewerbe"],
    alternates: {
      en: "/hotel-carpet",
      de: "/de/hotel-teppichboden",
      fr: "/fr/moquette-hotel-sur-mesure",
      ar: "/ar/sajad-fanadi-mukhasas",
      ru: "/ru/hotelnyy-kovrolin",
      "x-default": "/hotel-carpet",
    },
    eyebrow: "Objektbeläge direkt vom Hersteller",
    title: "Hotel-Teppichboden nach Maß für Zimmer, Flure und öffentliche Bereiche",
    introduction: "VISHOME liefert Axminster-, bedruckte Nylon- und Naturfaserlösungen für Hotels, Innenausbauer, Architekturbüros und Objektpartner. Konstruktion, Muster, Rollenbreite, Brandschutzanforderung und Verlegeplanung werden vor der Produktion projektbezogen abgestimmt.",
    targetMarkets: "Deutschland, Österreich, Schweiz und internationale DACH-Projekte",
    primaryProductId: "luxury-hotel-broadloom",
    heroAlt: "Maßgefertigter Axminster Hotel Teppichboden in einem hochwertigen Hotelflur",
    quoteProduct: "Hotel-Teppichboden nach Maß - DACH",
    emailSubject: "Projektanfrage - Hotel-Teppichboden nach Maß",
    stats: [
      { value: "ab 100 m²", label: "Je nach Produktprogramm" },
      { value: "4 m", label: "Verfügbare Rollenbreite" },
      { value: "15-30 Tage", label: "Je nach Konstruktion" },
      { value: "FOB / CIF / DAP", label: "Lieferoptionen" },
    ],
    productsIntro: "Die Produktauswahl richtet sich nach Nutzungszone, Beanspruchung, Reinigungsverfahren, Brandschutzanforderung und Gestaltung. Verbindlich ist die bestätigte Projektspezifikation.",
    productCards: [
      { id: "luxury-hotel-broadloom", name: "Axminster 80/20 Hotelteppich", description: "Gewebte Woll-Nylon-Konstruktion für hochwertige Flure, Suiten, Lobby und Ballsaal." },
      { id: "3d-printed-hotel-carpet", name: "HD-bedruckter Nylon-Teppichboden", description: "Individuelle Muster und kurze Einrichtungszeiten für Zimmer, Flure und Gastronomie." },
      { id: "natural-sisal-carpet", name: "Natur-Sisal für Objektbereiche", description: "Flachgewebte Naturfaseroptik für Empfang, Lounge und ausgewählte gewerbliche Innenräume." },
    ],
    benefits: [
      { title: "Zonengerechte Auslegung", description: "Zimmer, Flure, Lobby und Veranstaltungsflächen werden nach Beanspruchung und Pflege getrennt spezifiziert." },
      { title: "Musterfreigabe", description: "Farben, Rapport und Haptik werden mit Muster oder Strike-off vor Serienproduktion geprüft." },
      { title: "Technische Nachweise", description: "Brandschutz, Nutzungsklasse und antistatische Anforderungen werden für das gewählte Produkt abgeglichen." },
      { title: "Rollen- und Versandplanung", description: "Rollenlängen, Kennzeichnung und Verpackung werden auf Bauabschnitte und Exportweg abgestimmt." },
    ],
    applications: ["Hotelzimmer und Suiten", "Hotelflure", "Lobby und Empfang", "Bankett- und Tagungsräume", "Restaurants", "Sanierung im laufenden Betrieb"],
    process: [
      { title: "1. Projektunterlagen", description: "Grundrisse, Flächen, Nutzungszonen, Termin, Designreferenzen und Normen übermitteln." },
      { title: "2. Produktauswahl", description: "Wir schlagen Konstruktion, Material, Gewicht, Breite und Budgetrahmen vor." },
      { title: "3. Bemusterung", description: "Muster und Farben werden vor Produktionsfreigabe bestätigt." },
      { title: "4. Produktion und Versand", description: "Qualitätskontrolle, Kennzeichnung, Verpackung und Export erfolgen nach bestätigtem Terminplan." },
    ],
    faqs: [
      { question: "Welcher Teppich eignet sich für stark beanspruchte Hotelflure?", answer: "Je nach Gestaltung sind dichter Nylon-Teppichboden oder Axminster geeignet. Nutzungsklasse, Reinigung und Brandschutz müssen gemeinsam betrachtet werden." },
      { question: "Können eigene Muster umgesetzt werden?", answer: "Ja. Kundendesigns können angepasst und bemustert werden, sofern die Nutzungsrechte beim Auftraggeber liegen." },
      { question: "Welche Mindestmenge gilt?", answer: "Je nach Programm beginnt sie bei 100 m² für bestimmte Sonderanfertigungen, 300 m² für HD-Druck und 500 m² für Axminster 80/20." },
      { question: "Sind Brandschutznachweise verfügbar?", answer: "Die verfügbaren Nachweise sind produktabhängig. Bitte nennen Sie vorab die geforderte Norm, damit die passende Ausführung ausgewählt wird." },
    ],
    finalTitle: "Lassen Sie Ihr Hotelprojekt technisch prüfen",
    finalText: "Senden Sie Flächen je Zone, Objektstandard, Lieferland, Termin und geforderte Nachweise. Sie erhalten Produktempfehlung, Mindestmenge, Produktionszeit und Richtpreis.",
  },
  {
    locale: "de",
    slug: "gewerbliche-teppichfliesen",
    path: "/de/gewerbliche-teppichfliesen",
    direction: "ltr",
    openGraphLocale: "de_DE",
    metadataTitle: "Gewerbliche Teppichfliesen für Büro und Objekt | VISHOME",
    metadataDescription: "Gewerbliche Teppichfliesen für Büros, Flure und Objektprojekte. 50x50 cm, Nylon, Bitumen- oder PVC-freie PE-Rückenkonstruktion, Muster und Projektangebot.",
    keywords: ["gewerbliche Teppichfliesen", "Teppichfliesen Büro", "Teppichfliesen Objekt", "Teppichfliesen 50x50", "Teppichfliesen Hersteller"],
    alternates: {
      en: "/products/carpet-tiles",
      de: "/de/gewerbliche-teppichfliesen",
      fr: "/fr/dalles-moquette-commerciales",
      es: "/es/losetas-alfombra-comerciales",
      ar: "/ar/balat-sajad-tijari",
      ru: "/ru/products/carpet-tiles/nylon-office-carpet-tile",
      "x-default": "/products/carpet-tiles",
    },
    eyebrow: "Modulare Bodenbeläge für Büro und Objekt",
    title: "Gewerbliche Teppichfliesen für Büros, Flure und Objektprojekte",
    introduction: "VISHOME liefert gewerbliche Teppichfliesen für Innenausbauer, Architekturbüros, Händler und Projektteams. Die passende Spezifikation wird vor dem Angebot nach Nutzung, Untergrund, Beanspruchung, Rückenkonstruktion, Musterfreigabe und erforderlichen Unterlagen abgestimmt.",
    targetMarkets: "Deutschland, Österreich, Schweiz und internationale DACH-Projekte",
    primaryProductId: "nylon-office-carpet-tile",
    heroAlt: "Gewerbliche Nylon-Teppichfliesen in einer modernen Büroumgebung",
    quoteProduct: "Gewerbliche Teppichfliesen - DACH",
    emailSubject: "Projektanfrage - Gewerbliche Teppichfliesen",
    stats: [
      { value: "50 × 50 cm", label: "Gängiges Teppichfliesenformat" },
      { value: "Nylon / PP", label: "Je nach Konstruktion" },
      { value: "Bitumen / PE", label: "Rückenkonstruktionen nach Projekt" },
      { value: "Muster vor Freigabe", label: "Für Farbe und Aufbau" },
    ],
    productsIntro: "Vergleichen Sie nicht nur den Quadratmeterpreis. Für ein belastbares Objektangebot müssen Faser, Poleinsatzgewicht, Rücken, Nutzung, Stuhlrollen, Untergrund, Verlegeart, Ersatzfliesen und technische Unterlagen zusammenpassen.",
    productCards: [
      { id: "nylon-office-carpet-tile", name: "Nylon-Teppichfliesen für Büros", description: "Modulare Lösung für Büros, Flure und Besprechungsräume mit Schwerpunkt auf Nutzung, Austauschbarkeit und Projektplanung." },
      { id: "ecocore-pe-backing-carpet-tiles", name: "PVC-freie PE-Rückenkonstruktion", description: "Teppichfliesenoption für Projekte mit Anforderungen an Materialauswahl, modulare Nutzung und verfügbare Dokumente." },
      { id: "pp-bitumen-backed-office-carpet-tiles", name: "PP-Teppichfliesen mit Bitumenrücken", description: "Praktische 50x50-cm-Option für Büro- und Objektflächen, bei denen Rückenkonstruktion und Verlegeannahmen schriftlich abgestimmt werden." },
    ],
    benefits: [
      { title: "Projektgerechte Rückenkonstruktion", description: "Bitumen, PVC-freies PE oder andere Systeme werden nach Untergrund, Stuhlrollen, Austauschbarkeit, Komfort und Dokumentationsbedarf verglichen." },
      { title: "Musterfreigabe vor Serie", description: "Farbe, Textur, Richtung, Kante und Rückenaufbau werden mit einem physischen Muster geprüft, bevor eine Serienproduktion freigegeben wird." },
      { title: "Untergrund und Verlegung", description: "Beton, Doppelboden, Altbelagsreste, Feuchte, Klebstoff und spätere Austauschbarkeit gehören vor der Bestellung in die Projektabstimmung." },
      { title: "Unterlagen für die Prüfung", description: "Nennen Sie Anforderungen zu Brandverhalten, VOC, Nutzung, Verpackung und Termin frühzeitig, damit die verfügbare Dokumentation zum gewählten Produkt geprüft werden kann." },
    ],
    applications: ["Büroflächen", "Besprechungsräume", "Flure", "Coworking-Bereiche", "Bildungseinrichtungen", "Einzelhandel und Objektumbau"],
    process: [
      { title: "1. Projektumfang senden", description: "Fläche, Land, Nutzungszone, Untergrund, Termin, gewünschte Farbe und erforderliche Unterlagen angeben." },
      { title: "2. Aufbau vergleichen", description: "Faser, Poleinsatzgewicht, Format, Rücken und Verlegeannahme werden für die tatsächliche Nutzung abgeglichen." },
      { title: "3. Muster bestätigen", description: "Muster, Farbe, Richtung und verfügbare technische Unterlagen werden vor Produktionsfreigabe schriftlich bestätigt." },
      { title: "4. Angebot und Ersatzbestand", description: "Menge, Verschnitt, Ersatzfliesen, Verpackung, Lieferweg und schriftliche Angebotsgrundlage werden für das Projekt zusammengeführt." },
    ],
    faqs: [
      { question: "Welche Teppichfliesen eignen sich für Büros mit Stuhlrollen?", answer: "Die Eignung hängt von Faser, Polaufbau, Rücken, Nutzung, Stuhlrollen und Verlegesystem ab. Nennen Sie die tatsächliche Zone, damit keine Empfehlung nur nach einem Produktfoto erfolgt." },
      { question: "Ist Bitumen oder PVC-freies PE die bessere Rückenkonstruktion?", answer: "Keine Rückenkonstruktion ist für jedes Projekt automatisch besser. Verglichen werden sollten Untergrund, Feuchte, Stabilität, Komfort, Austauschbarkeit, gewünschte Dokumente und die freigegebene Verlegeart." },
      { question: "Können Muster für Deutschland, Österreich oder die Schweiz angefordert werden?", answer: "Ja. Senden Sie Produktwunsch, Farbe, Rückenkonstruktion, Projektfläche und Lieferort. Verfügbare Mustergröße und Versandoption werden vorab bestätigt." },
      { question: "Welche Unterlagen sollten vor dem Kauf angefordert werden?", answer: "Bitten Sie um die Unterlagen, die Ihr Projekt tatsächlich verlangt, zum Beispiel technische Daten, verfügbare Nachweise zum Brandverhalten oder zu Emissionen sowie Angaben zur Verlegeannahme. Die Unterlagen müssen zum exakt angebotenen Produkt passen." },
    ],
    finalTitle: "Teppichfliesen für Ihr DACH-Projekt technisch vergleichen",
    finalText: "Senden Sie Fläche, Land, Nutzungszone, Untergrund, Farbe, Rückenkonstruktion, Termin und benötigte Unterlagen. VISHOME stimmt Muster, verfügbare Dokumente, Menge, Ersatzbestand und Angebotsbasis mit dem gewählten Produkt ab.",
  },
  {
    locale: "pt",
    slug: "tapetes-personalizados-hotel",
    path: "/pt/tapetes-personalizados-hotel",
    direction: "ltr",
    openGraphLocale: "pt_AO",
    metadataTitle: "Tapetes personalizados para hotéis e lobbies | VISHOME",
    metadataDescription: "Tapetes esculpidos em lã e alcatifa estampada personalizada para hotéis, lobbies, quartos e espaços comerciais. Dimensões, cores e cotação para projetos.",
    keywords: ["tapetes personalizados hotel", "tapete para lobby", "alcatifa hotel", "tapete de lã personalizado", "carpete para hotel"],
    alternates: {
      en: "/products/public-area/custom-sculpted-wool-lobby-rug",
      pt: "/pt/tapetes-personalizados-hotel",
      "x-default": "/products/public-area/custom-sculpted-wool-lobby-rug",
    },
    eyebrow: "Produção por medida para interiores profissionais",
    title: "Tapetes personalizados para hotéis, lobbies e espaços de receção",
    introduction: "A VISHOME desenvolve tapetes soltos esculpidos e alcatifa de parede a parede para hotéis, empresas de design e projetos comerciais. Dimensão, composição, cor, desenho, base e requisitos técnicos são confirmados antes da produção para evitar decisões baseadas apenas numa imagem de referência.",
    targetMarkets: "Angola, Moçambique, Cabo Verde, Portugal e projetos de língua portuguesa",
    primaryProductId: "custom-sculpted-wool-lobby-rug",
    heroAlt: "Tapete de lã esculpido e personalizado num lobby comercial de alto padrão",
    quoteProduct: "Tapetes personalizados para hotéis - mercado lusófono",
    emailSubject: "Pedido de cotação - tapetes personalizados para hotel",
    stats: [
      { value: "10 peças", label: "MOQ do tapete de lobby" },
      { value: "100 m²", label: "MOQ de algumas alcatifas" },
      { value: "À medida", label: "Dimensões e cores" },
      { value: "FOB / CIF / DAP", label: "Opções de transporte" },
    ],
    productsIntro: "O tapete solto e a alcatifa de parede a parede têm funções diferentes. A seleção deve considerar dimensão, tráfego, limpeza, instalação e norma exigida pelo projeto.",
    productCards: [
      { id: "custom-sculpted-wool-lobby-rug", name: "Tapete esculpido para lobby", description: "Tapete decorativo por medida para receções, lounges, clubes e showrooms premium." },
      { id: "custom-floral-printed-hotel-carpet", name: "Alcatifa floral estampada", description: "Desenho personalizado para corredores, quartos, salas de banquete e espaços comerciais." },
      { id: "custom-luxury-hotel-room-carpet", name: "Alcatifa para quartos de hotel", description: "Programa por projeto para quartos, suites, corredores e renovações de hotel." },
    ],
    benefits: [
      { title: "Dimensão confirmada", description: "Plantas e medidas finais definem forma, orientação do desenho, bordas e embalagem." },
      { title: "Amostra de cor", description: "A cor e a textura são avaliadas em amostra antes da aprovação da produção." },
      { title: "Composição transparente", description: "Fibra, construção, base e eventuais requisitos de reação ao fogo são confirmados na ficha do projeto." },
      { title: "Apoio à exportação", description: "Preparação de embalagem, documentos e opção logística conforme volume e destino." },
    ],
    applications: ["Lobbies de hotel", "Receções corporativas", "Lounges executivos", "Quartos e suites", "Clubes privados", "Showrooms"],
    process: [
      { title: "1. Conceito", description: "Envie desenho, dimensões, fotografia de referência, local de uso e quantidade." },
      { title: "2. Especificação", description: "Definimos material, construção, cor, base, preço e prazo indicativo." },
      { title: "3. Amostra", description: "Amostra ou desenho de produção é aprovado antes do fabrico em série." },
      { title: "4. Produção e entrega", description: "Inspeção, embalagem e transporte seguem a especificação e o destino confirmados." },
    ],
    faqs: [
      { question: "O tapete é sempre 100% lã?", answer: "Não se deve assumir a composição apenas pela aparência. A composição exata é confirmada por escrito antes da encomenda, conforme desempenho, orçamento e requisito do projeto." },
      { question: "É possível produzir o nosso desenho?", answer: "Sim. Podemos adaptar formas, cores e padrões, desde que o cliente tenha direito de utilização do desenho enviado." },
      { question: "Qual é o pedido mínimo?", answer: "O tapete esculpido de lobby tem MOQ de 10 peças. Algumas alcatifas personalizadas começam a partir de 100 m², conforme construção." },
      { question: "Entregam em Angola e Moçambique?", answer: "Sim. Cotamos FOB, CIF ou DAP conforme cidade, porto, volume e condições de transporte disponíveis na data da proposta." },
    ],
    finalTitle: "Transforme a referência visual numa especificação real",
    finalText: "Envie dimensões, quantidade, uso, país, prazo e imagem de referência. A nossa equipa responderá com material proposto, MOQ, amostra, produção e cotação.",
  },
  {
    locale: "ru",
    slug: "hotelnyy-kovrolin",
    path: "/ru/hotelnyy-kovrolin",
    direction: "ltr",
    openGraphLocale: "ru_RU",
    metadataTitle: "Гостиничный ковролин на заказ | VISHOME",
    metadataDescription: "Гостиничный ковролин для номеров, коридоров, лобби и банкетных залов. Axminster, HD-печать, индивидуальный рисунок и расчёт поставки в страны СНГ.",
    keywords: ["гостиничный ковролин", "ковролин для отеля", "ковролин для коридора", "Axminster ковролин", "ковролин на заказ"],
    alternates: {
      en: "/hotel-carpet",
      ru: "/ru/hotelnyy-kovrolin",
      fr: "/fr/moquette-hotel-sur-mesure",
      ar: "/ar/sajad-fanadi-mukhasas",
      de: "/de/hotel-teppichboden",
      "x-default": "/hotel-carpet",
    },
    eyebrow: "Прямые поставки для гостиничных проектов",
    title: "Гостиничный ковролин на заказ для номеров, коридоров и общественных зон",
    introduction: "VISHOME поставляет ковролин Axminster, печатный нейлоновый ковролин и индивидуальные решения для гостиниц, дизайнеров, подрядчиков и дистрибьюторов. Рисунок, цвет, конструкция, ширина рулона и технические требования согласовываются до запуска производства.",
    targetMarkets: "Россия, Казахстан, Узбекистан, Туркменистан, Кыргызстан и русскоязычные проекты СНГ",
    primaryProductId: "luxury-hotel-broadloom",
    heroAlt: "Гостиничный ковролин Axminster с индивидуальным рисунком в коридоре отеля",
    quoteProduct: "Гостиничный ковролин на заказ - русскоязычный рынок",
    emailSubject: "Запрос расчёта - гостиничный ковролин",
    stats: [
      { value: "от 100 м²", label: "Для отдельных программ" },
      { value: "4 м", label: "Доступная ширина рулона" },
      { value: "15-30 дней", label: "В зависимости от конструкции" },
      { value: "FOB / CIF / DAP", label: "Варианты поставки" },
    ],
    productsIntro: "Конструкция выбирается по зоне применения, нагрузке, способу уборки, требованиям по пожарной безопасности и бюджету. Итоговые параметры фиксируются в спецификации проекта.",
    productCards: [
      { id: "luxury-hotel-broadloom", name: "Axminster 80/20 для гостиниц", description: "Тканый ковролин из шерсти и нейлона для премиальных коридоров, лобби и залов." },
      { id: "3d-printed-hotel-carpet", name: "Печатный нейлоновый ковролин", description: "Индивидуальные рисунки и насыщенные цвета для номеров, коридоров и ресторанов." },
      { id: "glitter-hotel-corridor-broadloom-carpet", name: "Ковролин для гостиничных коридоров", description: "Коммерческий рулонный ковролин с выразительным рисунком для коридоров и лифтовых холлов." },
    ],
    benefits: [
      { title: "Разделение по зонам", description: "Номера, коридоры, лобби и банкетные залы специфицируются отдельно по нагрузке и уходу." },
      { title: "Согласование образца", description: "Цвет, рисунок и фактура проверяются по образцу или strike-off до серийного производства." },
      { title: "Технические документы", description: "Класс пожарной безопасности и другие требования сверяются для выбранного продукта до заказа." },
      { title: "Планирование рулонов", description: "Длина, маркировка, упаковка и очередность поставки согласуются с этапами монтажа." },
    ],
    applications: ["Гостиничные номера", "Коридоры", "Лобби и ресепшен", "Банкетные залы", "Рестораны", "Поэтапная реконструкция"],
    process: [
      { title: "1. Исходные данные", description: "Пришлите планы, площади по зонам, сроки, референсы и требуемые стандарты." },
      { title: "2. Подбор", description: "Мы предложим конструкцию, материал, вес ворса, ширину и ориентировочный бюджет." },
      { title: "3. Образец", description: "Рисунок и цвет утверждаются до начала производства партии." },
      { title: "4. Производство и поставка", description: "Контроль качества, маркировка, упаковка и экспорт выполняются по согласованному графику." },
    ],
    faqs: [
      { question: "Какой ковролин подходит для гостиничного коридора?", answer: "Обычно выбирают плотный коммерческий нейлон или Axminster. Необходимо учитывать интенсивность движения, уборку, пожарные требования и бюджет." },
      { question: "Можно ли изготовить рисунок по проекту дизайнера?", answer: "Да. Мы адаптируем файл, подбираем цвета и изготавливаем образец, если заказчик имеет право использовать переданный дизайн." },
      { question: "Какая минимальная партия?", answer: "От 100 м² для некоторых индивидуальных программ, 300 м² для печатного ковролина и 500 м² для Axminster 80/20." },
      { question: "Возможна ли поставка DAP в страны СНГ?", answer: "Да, возможность и стоимость DAP рассчитываются по городу, объёму и актуальному маршруту. Также доступны условия FOB и CIF." },
    ],
    finalTitle: "Получите подбор ковролина для вашего объекта",
    finalText: "Укажите страну, площади по зонам, категорию гостиницы, сроки и необходимые нормы. Мы подготовим рекомендацию, минимальный заказ, срок и ориентировочную стоимость.",
  },
  {
    locale: "ja",
    slug: "custom-commercial-carpet",
    path: "/ja/custom-commercial-carpet",
    direction: "ltr",
    openGraphLocale: "ja_JP",
    metadataTitle: "業務用オーダーカーペット・タイルカーペット | VISHOME",
    metadataDescription: "ホテル、バス、ホール、店舗向けの業務用オーダーカーペット。カスタム柄、4m幅ロール、50x50cmタイル、サンプル確認、輸出見積もりに対応します。",
    keywords: ["業務用カーペット", "オーダーカーペット", "カスタム印刷カーペット", "タイルカーペット 50x50", "ホテル カーペット", "バス カーペット"],
    alternates: {
      en: "/commercial-carpet-manufacturer",
      ja: "/ja/custom-commercial-carpet",
      ko: "/ko/commercial-carpet-tile",
      "x-default": "/commercial-carpet-manufacturer",
    },
    eyebrow: "日本向け業務用カーペットの工場直送",
    title: "用途に合わせた 業務用オーダーカーペット",
    introduction: "VISHOMEは、ホテル、観光バス、イベントホール、店舗、オフィスなどの法人プロジェクト向けに、オーダー柄のロールカーペットと50x50cmタイルカーペットを供給します。図面、使用場所、必要面積、清掃方法を確認し、素材、厚み、柄、ロール割り、サンプル、輸送条件を発注前に整理します。",
    targetMarkets: "日本全国の内装会社、ホテル、交通事業者、イベント運営会社、輸入販売会社",
    primaryProductId: "custom-luxury-hotel-room-carpet",
    heroAlt: "日本向け商業施設に施工されたカスタムデザインの業務用ロールカーペット",
    quoteProduct: "日本向け業務用オーダーカーペット",
    emailSubject: "お見積もり依頼 - 日本向け業務用カーペット",
    stats: [
      { value: "100 m²から", label: "一部オーダー仕様のMOQ" },
      { value: "4 m", label: "ロール幅の選択肢" },
      { value: "50x50 cm", label: "タイルカーペット規格" },
      { value: "10-25日", label: "仕様別の生産目安" },
    ],
    productsIntro: "必要面積、柄の自由度、汚れやすさ、交換方法、施工形状によって最適な製品は異なります。価格だけでなく、標準MOQ、ロールの歩留まり、サンプル、メンテナンス条件を含めて比較します。",
    productCards: [
      { id: "custom-luxury-hotel-room-carpet", name: "小規模プロジェクト向けオーダーカーペット", description: "100m²から検討できる仕様で、ホテル、店舗、車両内装などの寸法とデザインに合わせて確認します。" },
      { id: "3d-printed-hotel-carpet", name: "HDカスタム印刷ナイロンカーペット", description: "4m幅ロールと細かなオリジナル柄に対応する、ホテル・ホール向けの商業用印刷カーペットです。" },
      { id: "commercial-nylon-tiles", name: "50x50cm ナイロンタイルカーペット", description: "オフィス、通路、店舗で部分交換しやすい、耐久性重視のモジュール式床材です。" },
    ],
    benefits: [
      { title: "図面と歩留まりの確認", description: "床の幅と長さ、柄方向、継ぎ目、裁断方法を確認し、実際に必要なロール数量を計算します。" },
      { title: "在庫柄とオーダー柄の比較", description: "少量案件は在庫柄が合理的な場合があります。オーダー柄は標準MOQ、版下、余尺、追加費用を事前に明示します。" },
      { title: "防汚・防水条件の分離", description: "防汚性、防水性、カスタム印刷は同じ仕様とは限りません。用途ごとに対応可能な組み合わせを確認します。" },
      { title: "サンプルと書類", description: "選定製品について品質サンプル、利用可能な試験資料、梱包・輸出書類を発注前に確認します。" },
    ],
    applications: ["ホテル客室・廊下", "観光バス・車両内装", "イベントホール", "店舗・ショールーム", "オフィス・会議室", "階段・変形スペース"],
    process: [
      { title: "1. 用途と寸法", description: "図面、面積、設置場所、数量、希望納期、参考画像をお送りください。" },
      { title: "2. 仕様提案", description: "素材、厚み、柄、ロール幅、タイル仕様、MOQ、参考価格を整理します。" },
      { title: "3. サンプル確認", description: "品質サンプルまたは柄サンプルで色、手触り、厚み、清掃条件を確認します。" },
      { title: "4. 生産・輸送", description: "承認仕様に基づいて生産し、検品、梱包、輸送書類を準備します。" },
    ],
    faqs: [
      { question: "希望する柄を印刷できますか？", answer: "はい。使用権のあるデザインデータから色と柄を調整できます。標準MOQ未満の場合は、在庫柄または小ロット対応費用を含めて個別に確認します。" },
      { question: "100m²未満でも注文できますか？", answer: "製品と在庫状況によります。オーダー生産はロール幅による余尺や設定費用が発生するため、在庫柄、品質サンプル、標準MOQを比較して回答します。" },
      { question: "防水仕様とオリジナル柄を同時に選べますか？", answer: "すべての製品で両立できるわけではありません。防水、防汚、印刷、厚み、裏材を別々に確認し、対応可能な仕様のみをご提案します。" },
      { question: "日本向けの防炎資料はありますか？", answer: "選定製品で利用可能な試験資料を提示します。ただし、日本国内で必要な認定、表示、輸入手続きへの適合は、用途と案件条件に基づき輸入者側でも確認が必要です。" },
    ],
    finalTitle: "図面と用途から実際の必要数量を計算します",
    finalText: "設置場所、寸法、面積、希望柄、厚み、清掃条件、納期、配送先をお知らせください。標準MOQ、サンプル、ロール割り、参考価格をまとめて回答します。",
  },
  {
    locale: "ko",
    slug: "commercial-carpet-tile",
    path: "/ko/commercial-carpet-tile",
    direction: "ltr",
    openGraphLocale: "ko_KR",
    metadataTitle: "상업용 카펫 타일 50x50 및 호텔 카펫 | VISHOME",
    metadataDescription: "한국 오피스, 호텔, 인테리어 프로젝트용 50x50cm 나일론 카펫 타일과 맞춤형 롤 카펫. 방염 자료, 샘플, MOQ, 운송 견적을 확인하세요.",
    keywords: ["카펫 타일", "상업용 카펫", "50x50 카펫 타일", "나일론 카펫 타일", "사무실 카펫", "호텔 카펫"],
    alternates: {
      en: "/products/carpet-tiles",
      ko: "/ko/commercial-carpet-tile",
      ja: "/ja/custom-commercial-carpet",
      fr: "/fr/dalles-moquette-commerciales",
      es: "/es/losetas-alfombra-comerciales",
      ar: "/ar/balat-sajad-tijari",
      ru: "/ru/products/carpet-tiles/nylon-office-carpet-tile",
      "x-default": "/products/carpet-tiles",
    },
    eyebrow: "한국 상업 공간 프로젝트를 위한 공장 직송",
    title: "한국 오피스·호텔용 50x50cm 카펫 타일",
    introduction: "VISHOME은 한국의 인테리어 회사, 시공사, 호텔, 오피스 및 유통업체를 위해 나일론 카펫 타일과 맞춤형 롤 카펫을 공급합니다. 사용 면적, 통행량, 방염 요구, 바닥 구조, 디자인, 예산을 확인한 후 섬유, 백킹, 생산 로트, 시험 자료와 운송 조건을 정리합니다.",
    targetMarkets: "대한민국의 인테리어 회사, 오피스, 호텔, 상업 시설, 카펫 유통업체",
    primaryProductId: "commercial-nylon-tiles",
    heroAlt: "한국 상업용 오피스 프로젝트에 설치된 50x50cm 나일론 카펫 타일",
    quoteProduct: "한국 상업용 카펫 타일 및 호텔 카펫",
    emailSubject: "견적 요청 - 한국 상업용 카펫 타일",
    stats: [
      { value: "50x50 cm", label: "표준 모듈 규격" },
      { value: "200 m²", label: "나일론 타일 기준 MOQ" },
      { value: "Class 33", label: "고통행 상업용 옵션" },
      { value: "10-25일", label: "제품별 생산 기간" },
    ],
    productsIntro: "상업용 카펫은 섬유와 디자인뿐 아니라 방염 등급, 백킹, 통행량, 유지관리, 생산 로트를 함께 비교해야 합니다. 최종 사양과 제공 가능한 시험 자료는 선택한 모델별로 확인합니다.",
    productCards: [
      { id: "commercial-nylon-tiles", name: "나일론 6.6 상업용 카펫 타일", description: "50x50cm 규격, Class 33 통행 성능과 부분 교체 편의성을 갖춘 오피스 및 상업 공간용 제품입니다." },
      { id: "ecocore-pe-backing-carpet-tiles", name: "PVC-Free PE 백킹 카펫 타일", description: "친환경 자재 방향과 모듈 시공을 함께 검토하는 오피스, 교육 시설 및 프로젝트용 옵션입니다." },
      { id: "3d-printed-hotel-carpet", name: "맞춤형 프린트 호텔 롤 카펫", description: "호텔 객실, 복도, 로비를 위한 4m 폭 나일론 롤 카펫으로 맞춤 패턴과 컬러를 지원합니다." },
    ],
    benefits: [
      { title: "방염 자료 사전 확인", description: "선택한 제품의 기존 시험 자료와 사양을 주문 전에 제공합니다. 한국 현지 인증 및 시험 필요 여부는 프로젝트별로 별도 확인합니다." },
      { title: "섬유와 백킹 선택", description: "나일론, 합성섬유, 비투멘 또는 PE 백킹을 통행량, 바닥 구조, 예산에 맞춰 비교합니다." },
      { title: "생산 로트 관리", description: "색상 차이를 줄이기 위해 프로젝트 수량과 유지보수용 여분을 동일 생산 로트로 계획합니다." },
      { title: "한국 도착 운송 견적", description: "수량과 목적지를 기준으로 FOB, CIF 또는 가능한 DAP 조건과 포장 정보를 계산합니다." },
    ],
    applications: ["기업 오피스", "호텔 객실과 복도", "회의실", "상업 매장", "교육 시설", "인테리어 공사 프로젝트"],
    process: [
      { title: "1. 프로젝트 정보", description: "면적, 사용 공간, 통행량, 도면, 납기, 요구 시험 기준을 보내주세요." },
      { title: "2. 제품과 가격", description: "섬유, 백킹, 디자인, MOQ, FOB 참고 가격과 생산 기간을 제안합니다." },
      { title: "3. 샘플과 자료", description: "색상 샘플, 기술 사양서 및 선택 제품에 제공 가능한 시험 자료를 확인합니다." },
      { title: "4. 생산과 선적", description: "승인된 사양에 따라 생산, 품질 검사, 포장 및 수출 서류를 준비합니다." },
    ],
    faqs: [
      { question: "한국 방염 기준을 통과할 수 있나요?", answer: "제품별 기존 시험 등급과 자료를 먼저 제공합니다. 한국에서 요구되는 추가 시험, 인증, 표시 기준은 사용 장소와 수입 조건에 따라 달라지므로 현지 기관 또는 수입자가 최종 확인해야 합니다." },
      { question: "나일론 카펫 타일의 ㎡당 가격은 얼마인가요?", answer: "현재 제품 페이지의 FOB 참고 범위는 모델, 디자인, 백킹, 수량에 따라 달라집니다. 정확한 가격은 총 면적과 선택 사양을 확인한 후 제시합니다." },
      { question: "샘플과 카탈로그를 받을 수 있나요?", answer: "가능합니다. 필요한 색상, 섬유, 백킹, 배송지를 알려주시면 제공 가능한 샘플 크기와 운송비를 확인합니다." },
      { question: "한국까지 배송할 수 있나요?", answer: "가능합니다. 항구 또는 현장 주소, 수량, 포장 부피에 따라 FOB, CIF 또는 가능한 DAP 조건을 계산합니다." },
    ],
    finalTitle: "면적과 방염 요구를 보내주시면 정확한 사양을 제안합니다",
    finalText: "총 면적, 설치 공간, 통행량, 원하는 디자인, 백킹, 방염 기준, 납기와 한국 배송지를 알려주세요. MOQ, 샘플, 시험 자료, 생산 기간과 견적을 함께 답변드립니다.",
  },
];

export function getLocalizedLanding(locale: LandingLocale, slug: string) {
  return localizedLandings.find((page) => page.locale === locale && page.slug === slug);
}
