import type { CountryApplicationPage } from "@/lib/country-application-pages";
import { contentGrowthAssets, illustrationCaption } from "@/lib/content-growth-assets";

export const philippinesEntertainmentPage: CountryApplicationPage = {
  market: "ph",
  slug: "entertainment-venue-carpet",
  path: "/markets/ph/entertainment-venue-carpet",
  countryHubPath: "/ph/commercial-carpet-supplier-philippines",
  updatedDate: "2026-10-08",
  language: "en",
  hreflang: "en-PH",
  openGraphLocale: "en_PH",
  countryName: "Philippines",
  countryNameLocal: "Philippines",
  applicationName: "Cinema and Entertainment Carpet",
  title: "Carpet for Cinema and Entertainment Projects in the Philippines",
  metadataTitle: "Cinema & Entertainment Carpet Philippines | Vcarpets",
  metadataDescription: "Source custom cinema carpet for Philippine projects. Review venue zones, paid samples, pattern repeats and FOB Tianjin Port quotation requirements.",
  directAnswer: "Vcarpets supplies custom cinema and theater carpet and accepts Philippine B2B project inquiries. Patterns and colours can be customised. Paid sample requests for the Philippines are accepted; the appropriate sample type, availability, fees and preparation time are confirmed for each project. Bulk quotations are FOB Tianjin Port, with construction, roll width, quantity and schedule agreed in writing.",
  marketNote: "Prepare Philippine entertainment flooring by venue zone and import route. For Metro Manila, Cebu or another destination, identify the actual receiving city or port, appointed importer or forwarder, local installation partner and required site date. A production-ready date in China is distinct from arrival in the Philippines and completion of installation. This page covers patterned entertainment interiors; hotel rooms and corridors have a separate procurement page.",
  applicationRisks: [
    "A single total area can miss auditorium seating, aisle turns, stairs and lobby transitions. Separate the zones before comparing proposals.",
    "Colour approval alone leaves backing, roll format, pattern repeat and technical acceptance unresolved. Confirm the nominated construction with the sample.",
    "If storage, cleaning or substrate conditions involve moisture, the local installer should assess the site and attachment system before ordering.",
    "Graphics do not replace exit signage, step markings or lighting. Venue safety details need an independent local project review.",
  ],
  buyerChecklist: ["Measured area by zone and drawing revision", "Pattern reference, repeat and direction", "Construction and backing confirmation", "Local installer and required documents", "Receiving city or port and forwarder", "Sample approval and site milestones"],
  decisionRows: [
    { zone: "Auditorium", issue: "Seating, circulation and cleaning access", recommendation: "Send the seating plan, area, installation window and required documents; review the exact construction and attachment system." },
    { zone: "Arrival and waiting area", issue: "Full-floor pattern appearance", recommendation: "Provide dimensions, principal sightlines, artwork and lighting references; approve colour and pattern scale with a physical sample." },
    { zone: "Circulation routes", issue: "Seams, turns and flooring transitions", recommendation: "Show aisles, doorways and proposed direction. Agree joins and cutting allowances with the installer." },
    { zone: "Concession areas", issue: "Spills and cleaning routine", recommendation: "Describe exposure and maintenance; assess whether carpet is suitable or another flooring is required." },
    { zone: "Steps and level changes", issue: "Nosing and safe installation detail", recommendation: "Provide step drawings and the venue specification; obtain the responsible local team's review." },
  ],
  quoteInputs: [
    "Company, business email, venue type and estimated square metres by zone.",
    "Actual receiving city or port in the Philippines and buyer-appointed forwarder arrangement.",
    "Current floor-plan revision, design reference, required documents and any undecided specifications.",
    "Sample purpose, requested approval date and desired site arrival or installation date.",
    "Request a written FOB Tianjin Port quotation stating construction, quantity basis, packing and production-ready timing.",
  ],
  localTerms: ["entertainment venue carpet Philippines", "cinema carpet supplier Philippines", "theater carpet Philippines", "printed broadloom Philippines"],
  heroImage: contentGrowthAssets.P08.src,
  heroImageAlt: contentGrowthAssets.P08.alt,
  heroImageCaption: illustrationCaption,
  heroProductId: "cinema-theater-carpet",
  productIds: ["cinema-theater-carpet"],
  guideLinks: [
    { href: "/blog/printed-broadloom-pattern-repeat-seam-planning", label: "Pattern repeat and seam planning", description: "Review roll direction, joins and quantity before approving artwork." },
    { href: "/products/printed-carpet", label: "Printed carpet range", description: "Compare existing product routes when a project-specific graphic is central to the brief." },
    { href: "/products/carpet-tiles", label: "Commercial carpet tiles", description: "Compare a modular format where selective replacement or phased refurbishment matters." },
    { href: "/markets/ph/hotel-carpet-philippines", label: "Philippines hotel carpet procurement", description: "Use the separate hotel page for guestrooms and hotel corridors." },
    { href: "/ph/commercial-carpet-supplier-philippines", label: "Philippines commercial carpet supplier", description: "Return to the wider commercial product shortlist." },
    { href: "/blog/commercial-carpet-sample-approval-checklist", label: "Physical sample approval checklist", description: "Keep colour, construction, backing and approval records together." },
  ],
  procurementSections: [
    { title: "Paid Samples and Approval Before a Project Order", paragraphs: [
      "Vcarpets accepts paid sample requests for Philippine buyers. Tell us whether you need a material review, colour review or custom printed pattern approval. The team confirms which sample format can be prepared, development and courier charges, and preparation time before payment or dispatch. Acceptance of a request does not mean every sample type is held in stock.",
      "Review colour and pattern scale under representative venue lighting. Record the selected fibre, pile, backing, artwork revision and repeat with the approval. A small colour sample may not show a full motif; agree what the sample will approve before it is produced. For phased work, define pattern continuity and separately retained replacement stock.",
    ] },
    { title: "FOB Tianjin Port: Separate Export and Local Delivery", paragraphs: [
      "Bulk quotations are FOB Tianjin Port. Request roll count, packing dimensions, gross weight, marking requirements and the production-ready schedule so your appointed freight partner can assess the onward route. Onward freight, Philippine clearance, duties, taxes and local delivery are outside the FOB product quotation and should be confirmed with your appointed partners.",
      "Identify any transfer from the receiving port to the venue and protect the carpet during unloading and storage. This page does not offer local stock, a Philippine warehouse or local installation. Do not fix a reopening date from an unconfirmed transport estimate.",
    ] },
    { title: "Local Installation and Document Review", paragraphs: [
      "Before ordering, have the local installer assess the subfloor, moisture conditions, attachment compatibility, storage and acclimation requirements for the nominated carpet. Keep rolls protected during receiving and follow the selected product and adhesive instructions.",
      "Fire performance, moisture tolerance and acoustic results are not established by a product photograph. Send the venue or consultant's actual test method and document requirements. Available reports must match the quoted construction; local acceptance remains with the responsible Philippine project team.",
    ] },
  ],
  faq: [
    { question: "Can Philippine businesses request a cinema carpet quotation?", answer: "Yes. Vcarpets accepts Philippine B2B inquiries and supplies custom cinema and theater carpet. Send venue type, area, destination, design reference and date. Exact material, backing, width, MOQ and timing are confirmed for the nominated configuration." },
    { question: "Can you send paid samples to the Philippines?", answer: "Yes. Paid sample requests are accepted. State the review purpose and design reference; available sample format, sample or development fees, courier charges and preparation time are confirmed per project before dispatch." },
    { question: "Can the pattern and colours be customised?", answer: "Yes. Send artwork or a reference and the floor plan. Confirm repeat, direction, sample approval and the selected construction before bulk release." },
    { question: "Does FOB include delivery to Manila or Cebu?", answer: "No. Bulk quotations are FOB Tianjin Port. The buyer's appointed partners confirm onward freight, Philippine import clearance, charges and local delivery." },
    { question: "Do you guarantee local fire approval?", answer: "Provide the required test method and documents. Product reports must match the nominated construction and be reviewed by the project team; this page makes no blanket local compliance promise." },
    { question: "How should I decide the quantity?", answer: "Start with measured areas by zone, then review confirmed roll width, repeat, direction, seams and cuts with the installer. Record replacement stock separately from installation allowance." },
    { question: "Can I inquire before the design is final?", answer: "Yes. Label the drawing and artwork as preliminary and identify undecided items. Final pricing and scheduling require construction, quantity and approval steps to be confirmed." },
  ],
};
