export type RuB2BPage = {
  slug: string;
  eyebrow: string;
  title: string;
  seoTitle: string;
  description: string;
  intro: string;
  buyerFocus: string;
  primaryProductId: string;
  productIds: string[];
  englishPath: string;
  applications: string[];
  benefits: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
};

const coreBenefits = [
  { title: "Прямое производство", description: "Одна команда сопровождает спецификацию, образцы, производство, контроль и экспортную упаковку." },
  { title: "Проектная кастомизация", description: "Можно согласовать цвет, рисунок, размер, материал и основу под требования коммерческого объекта." },
  { title: "Документы для закупки", description: "До расчета можно запросить технические параметры, упаковочные данные и план поставки по вашему проекту." },
];

const commonFaqs = [
  { question: "Можно ли получить образец до заказа?", answer: "Да. Укажите продукт, цвет или референс, площадь проекта и город доставки. Команда продаж подтвердит доступный формат образца и дальнейшие шаги." },
  { question: "Подходит ли поставка для крупного коммерческого проекта?", answer: "Да. Для расчета нужны тип объекта, площадь, спецификация, требуемая дата и город доставки. После этого можно согласовать производство и логистику." },
  { question: "Можно ли изменить цвет и рисунок?", answer: "Для проектных заказов можно обсудить цвет, рисунок, материал, основу и формат. Точная возможность зависит от выбранной конструкции и утвержденного образца." },
  { question: "Какой MOQ и срок производства?", answer: "MOQ разделен на Sample, Trial Order и Project MOQ. Точное значение и срок зависят от продукта, площади, конструкции и очереди производства, поэтому подтверждаются после получения спецификации." },
  { question: "Можно ли организовать поставку в Россию?", answer: "Да, укажите город, объем, желаемую дату и предпочтительный способ поставки. Команда подготовит коммерческий расчет после проверки маршрута и упаковочных данных." },
  { question: "Можно ли отправить план или дизайн проекта?", answer: "Да. В форме можно описать задачу и приложить план, фотографию или референс. Форматы и размер файлов подтверждаются при отправке запроса." },
];

export const ruB2BPages: RuB2BPage[] = [
  {
    slug: "kovrolin-dlya-gostinits",
    eyebrow: "Гостиничные проекты",
    title: "Ковролин для гостиниц на заказ от производителя",
    seoTitle: "Ковролин для гостиниц на заказ | Производитель VISHOME",
    description: "Производство гостиничного ковролина для номеров, коридоров, лобби и банкетных залов. Образцы, индивидуальный дизайн и поставки из Китая в Россию.",
    intro: "VISHOME помогает гостиницам, дизайнерам и подрядчикам согласовать коммерческий ковролин по назначению, рисунку, материалу, основе и площади проекта.",
    buyerFocus: "Для гостиничных закупщиков и подрядчиков, которым нужен единый поставщик для номеров, коридоров, лобби и общественных зон.",
    primaryProductId: "luxury-hotel-broadloom",
    productIds: ["luxury-hotel-broadloom", "3d-printed-hotel-carpet", "custom-luxury-hotel-room-carpet"],
    englishPath: "/hotel-carpet",
    applications: ["Номера", "Коридоры", "Лобби", "Рестораны", "Банкетные залы", "Конференц-залы"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kovrovaya-plitka",
    eyebrow: "Модульное коммерческое покрытие",
    title: "Ковровая плитка для офисов и коммерческих помещений",
    seoTitle: "Ковровая плитка оптом для офиса | Производитель VISHOME",
    description: "Коммерческая ковровая плитка 50×50 для офисов, отелей и общественных помещений. Проектная спецификация, образцы и оптовые поставки из Китая.",
    intro: "Модульная плитка помогает поэтапно укладывать покрытие, заменять отдельные зоны и согласовывать цветовые схемы для офисных и гостиничных проектов.",
    buyerFocus: "Для импортеров, офисных подрядчиков, дизайнеров и закупщиков, которым важны модульность, ремонтопригодность и повторяемая спецификация.",
    primaryProductId: "nylon-office-carpet-tile",
    productIds: ["nylon-office-carpet-tile", "commercial-nylon-tiles", "ecocore-pe-backing-carpet-tiles"],
    englishPath: "/products/carpet-tiles",
    applications: ["Открытые офисы", "Коридоры", "Отели", "Лифтовые холлы", "Коммерческие центры", "Учебные помещения"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "ofisnyy-kovrolin",
    eyebrow: "Офисные проекты",
    title: "Офисный ковролин для бизнес-центров и рабочих пространств",
    seoTitle: "Офисный ковролин оптом | Коммерческий поставщик VISHOME",
    description: "Офисный ковролин и ковровая плитка для бизнес-центров, переговорных и зон с высокой проходимостью. Расчет по проекту и поставка из Китая.",
    intro: "Подберите конструкцию коммерческого ковролина под интенсивность движения, схему помещения, требования к обслуживанию и бюджет проекта.",
    buyerFocus: "Для офисных девелоперов, fit-out подрядчиков, архитекторов и дистрибьюторов коммерческих напольных покрытий.",
    primaryProductId: "commercial-nylon-tiles",
    productIds: ["commercial-nylon-tiles", "nylon-office-carpet-tile", "gray-line-nylon-office-hotel-carpet-tiles"],
    englishPath: "/commercial-carpet-tiles",
    applications: ["Бизнес-центры", "Open space", "Переговорные", "Ресепшн", "Коридоры", "Коворкинги"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kommercheskiy-kovrolin",
    eyebrow: "B2B поставки",
    title: "Коммерческий ковролин для общественных помещений",
    seoTitle: "Коммерческий ковролин от производителя | VISHOME",
    description: "Коммерческий ковролин для гостиниц, офисов, коридоров и общественных помещений. Производство, образцы и проектный расчет напрямую с фабрики.",
    intro: "VISHOME поставляет рулонный ковролин и ковровую плитку для коммерческих объектов с согласованием характеристик, количества, упаковки и графика поставки.",
    buyerFocus: "Для закупщиков, строительных компаний, импортеров и каналов дистрибуции, которым нужен производитель для разных типов коммерческих объектов.",
    primaryProductId: "public-area-heavy-duty",
    productIds: ["public-area-heavy-duty", "luxury-hotel-broadloom", "commercial-nylon-tiles"],
    englishPath: "/commercial-carpet-manufacturer",
    applications: ["Гостиницы", "Офисы", "Торговые центры", "Коридоры", "Рестораны", "Общественные здания"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "aksmisterskiy-kovrolin",
    eyebrow: "Тканый гостиничный ковролин",
    title: "Аксминстерский ковролин для гостиничных проектов",
    seoTitle: "Аксминстерский ковролин для гостиниц | VISHOME",
    description: "Аксминстерский ковролин для гостиниц, коридоров, лобби и банкетных залов. Проектный дизайн, образцы и поставка из Китая.",
    intro: "Аксминстерская конструкция подходит для гостиничных зон, где важны сложный рисунок, проектная цветовая схема и стабильная спецификация покрытия.",
    buyerFocus: "Для гостиничных закупщиков, дизайнеров и подрядчиков, которым нужен тканый ковролин под утвержденную концепцию интерьера.",
    primaryProductId: "luxury-hotel-broadloom",
    productIds: ["luxury-hotel-broadloom", "custom-luxury-hotel-room-carpet", "3d-printed-banquet-hall-carpet"],
    englishPath: "/products/wall-to-wall/luxury-hotel-broadloom",
    applications: ["Лобби", "Коридоры", "Банкетные залы", "Номера", "Рестораны", "Клубные зоны"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "pechatnyy-kovrolin",
    eyebrow: "Индивидуальная печать",
    title: "Печатный ковролин на заказ для коммерческих интерьеров",
    seoTitle: "Печатный ковролин на заказ для гостиниц | VISHOME",
    description: "Печатный коммерческий ковролин по индивидуальному рисунку для гостиниц, коридоров и залов. Цветопробы, образцы и проектные поставки.",
    intro: "Цифровая печать помогает перенести проектный рисунок и цветовую палитру на ковролин для гостиничных и общественных пространств.",
    buyerFocus: "Для дизайнеров, гостиничных операторов и проектных компаний, которым требуется индивидуальный рисунок и согласование цвета по образцу.",
    primaryProductId: "3d-printed-hotel-carpet",
    productIds: ["3d-printed-hotel-carpet", "custom-floral-printed-hotel-carpet", "3d-printed-banquet-hall-carpet"],
    englishPath: "/products/wall-to-wall/3d-printed-hotel-carpet",
    applications: ["Коридоры", "Банкетные залы", "Рестораны", "Номера", "Казино", "Конференц-залы"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "sherstyanoy-kovrolin",
    eyebrow: "Шерстяные проектные покрытия",
    title: "Шерстяной ковролин и ковры для гостиничных интерьеров",
    seoTitle: "Шерстяной ковролин на заказ для гостиниц | VISHOME",
    description: "Шерстяной ковролин и скульптурные ковры для лобби, номеров и премиальных коммерческих интерьеров. Образцы и проектный расчет.",
    intro: "Шерстяные и смесовые конструкции рассматриваются для премиальных зон, где важны тактильность, внешний вид и индивидуальное оформление.",
    buyerFocus: "Для дизайнеров, гостиниц и проектных закупщиков, выбирающих премиальные покрытия для лобби, номеров и представительских зон.",
    primaryProductId: "custom-sculpted-wool-lobby-rug",
    productIds: ["custom-sculpted-wool-lobby-rug", "luxury-hotel-broadloom", "custom-luxury-hotel-room-carpet"],
    englishPath: "/products/public-area/custom-sculpted-wool-lobby-rug",
    applications: ["Лобби", "Лаунж-зоны", "Номера", "Бутик-отели", "Представительские офисы", "Рестораны"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kovrolin-dlya-koridorov",
    eyebrow: "Высокая проходимость",
    title: "Ковролин для гостиничных и коммерческих коридоров",
    seoTitle: "Ковролин для коридоров высокой проходимости | VISHOME",
    description: "Коммерческий ковролин для гостиничных и офисных коридоров. Подбор конструкции, рисунка, основы и проектной поставки.",
    intro: "Для коридоров необходимо согласовать интенсивность движения, ширину рулона, рисунок, стыки, уборку и запас материала до заказа.",
    buyerFocus: "Для гостиниц, бизнес-центров и подрядчиков, которым нужно покрытие для постоянного движения людей и тележек.",
    primaryProductId: "glitter-hotel-corridor-broadloom-carpet",
    productIds: ["glitter-hotel-corridor-broadloom-carpet", "public-area-heavy-duty", "3d-printed-hotel-carpet"],
    englishPath: "/products/wall-to-wall/glitter-hotel-corridor-broadloom-carpet",
    applications: ["Гостиничные коридоры", "Офисные коридоры", "Лифтовые холлы", "Переходы", "Общественные зоны"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kovrolin-dlya-banketnykh-zalov",
    eyebrow: "Банкетные и event-пространства",
    title: "Ковролин для банкетных залов на заказ",
    seoTitle: "Ковролин для банкетного зала на заказ | VISHOME",
    description: "Печатный и проектный ковролин для банкетных залов, конференций и гостиничных event-зон. Дизайн, образцы и расчет площади.",
    intro: "Ковролин для банкетного зала согласовывается по рисунку, плану помещения, размещению мебели, движению тележек и графику монтажа.",
    buyerFocus: "Для гостиниц, конференц-центров и подрядчиков, которым нужен выразительный рисунок и коммерческая конструкция для больших залов.",
    primaryProductId: "3d-printed-banquet-hall-carpet",
    productIds: ["3d-printed-banquet-hall-carpet", "luxury-hotel-broadloom", "3d-printed-hotel-carpet"],
    englishPath: "/products/wall-to-wall/3d-printed-banquet-hall-carpet",
    applications: ["Банкетные залы", "Ballroom", "Конференции", "Event-зоны", "Фойе", "Рестораны"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kovrolin-dlya-restoranov",
    eyebrow: "Рестораны и hospitality",
    title: "Коммерческий ковролин для ресторанов",
    seoTitle: "Ковролин для ресторанов и гостиничных зон | VISHOME",
    description: "Ковролин для ресторанов, гостиничных dining-зон и приватных залов. Индивидуальный дизайн, образцы и проектная поставка.",
    intro: "Для ресторана важно совместить дизайн, акустический комфорт, интенсивность движения и план обслуживания покрытия.",
    buyerFocus: "Для ресторанных групп, гостиниц и дизайнеров, которым требуется проектное покрытие для dining-зон и приватных залов.",
    primaryProductId: "custom-floral-printed-hotel-carpet",
    productIds: ["custom-floral-printed-hotel-carpet", "3d-printed-hotel-carpet", "luxury-hotel-broadloom"],
    englishPath: "/products/wall-to-wall/custom-floral-printed-hotel-carpet",
    applications: ["Рестораны", "Приватные залы", "Гостиничные dining-зоны", "Лаунжи", "Фойе", "Клубы"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kovrolin-dlya-kazino",
    eyebrow: "Казино и развлекательные комплексы",
    title: "Ковролин для казино и игровых залов",
    seoTitle: "Ковролин для казино на заказ | Коммерческий VISHOME",
    description: "Индивидуальный печатный ковролин для казино, игровых залов и развлекательных комплексов. Рисунок, образцы и проектный расчет.",
    intro: "Ковролин для казино проектируется с учетом крупных рисунков, зонирования, непрерывного движения и визуальной навигации внутри пространства.",
    buyerFocus: "Для операторов казино, дизайнеров и подрядчиков, которым нужна индивидуальная графика для больших коммерческих площадей.",
    primaryProductId: "3d-printed-hotel-carpet",
    productIds: ["3d-printed-hotel-carpet", "glitter-hotel-corridor-broadloom-carpet", "3d-printed-banquet-hall-carpet"],
    englishPath: "/products/wall-to-wall/3d-printed-hotel-carpet",
    applications: ["Игровые залы", "Казино", "VIP-зоны", "Коридоры", "Фойе", "Развлекательные комплексы"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "kovrolin-dlya-konferents-zalov",
    eyebrow: "Конференц-залы",
    title: "Ковролин для конференц-залов и деловых центров",
    seoTitle: "Ковролин для конференц-зала | Проектный VISHOME",
    description: "Коммерческий ковролин и ковровая плитка для конференц-залов, переговорных и деловых центров. Подбор и расчет по проекту.",
    intro: "Для конференц-залов можно сравнить рулонный ковролин и модульную плитку по акустике, плану помещения, обслуживанию и замене отдельных зон.",
    buyerFocus: "Для бизнес-центров, гостиниц и подрядчиков, которым нужно покрытие для встреч, мероприятий и трансформируемых залов.",
    primaryProductId: "3d-printed-banquet-hall-carpet",
    productIds: ["3d-printed-banquet-hall-carpet", "commercial-nylon-tiles", "luxury-hotel-broadloom"],
    englishPath: "/products/wall-to-wall/3d-printed-banquet-hall-carpet",
    applications: ["Конференц-залы", "Переговорные", "Бизнес-центры", "Учебные залы", "Фойе", "Многофункциональные помещения"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "dlya-importerov-i-distributorov",
    eyebrow: "Для импортеров и дистрибьюторов",
    title: "Коммерческий ковролин для импортеров и дистрибьюторов",
    seoTitle: "Поставщик коммерческого ковролина для импортеров | VISHOME",
    description: "Производитель коммерческого ковролина и ковровой плитки для импортеров и дистрибьюторов в России. Каталог, образцы и проектные поставки.",
    intro: "Соберите ассортимент под ваш канал: офисная ковровая плитка, гостиничный ковролин, покрытия для коридоров и проектные конструкции.",
    buyerFocus: "Для компаний, которым нужны стабильная спецификация, экспортная упаковка, повторные заказы и понятный процесс согласования образцов.",
    primaryProductId: "commercial-nylon-tiles",
    productIds: ["commercial-nylon-tiles", "luxury-hotel-broadloom", "public-area-heavy-duty"],
    englishPath: "/commercial-carpet-manufacturer",
    applications: ["Дистрибуция", "Проектные поставки", "Офисный сегмент", "Гостиничный сегмент", "Общественные помещения"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "dlya-dizaynerov-i-arkhitektorov",
    eyebrow: "Для дизайнеров и архитекторов",
    title: "Коммерческий ковролин по дизайну проекта",
    seoTitle: "Ковролин на заказ для дизайнеров и архитекторов | VISHOME",
    description: "Проектный ковролин по референсу, цвету и назначению для архитекторов и дизайнеров. Подбор конструкции, образцы и техническая поддержка.",
    intro: "Передайте референс, визуализацию или план помещения, чтобы обсудить рисунок, материал, формат и технические ограничения покрытия.",
    buyerFocus: "Для архитекторов и дизайнеров, которым нужно перевести концепцию интерьера в согласованную спецификацию ковролина.",
    primaryProductId: "3d-printed-hotel-carpet",
    productIds: ["3d-printed-hotel-carpet", "custom-floral-printed-hotel-carpet", "custom-sculpted-wool-lobby-rug"],
    englishPath: "/solutions/hotel-hospitality",
    applications: ["Лобби", "Коридоры", "Номера", "Рестораны", "Банкетные залы", "Бутик-отели"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "dlya-gostinichnykh-proektov",
    eyebrow: "Для гостиничных проектов",
    title: "Поставка ковролина для гостиничного проекта",
    seoTitle: "Ковролин для гостиничного проекта | Расчет и образцы VISHOME",
    description: "Комплексная поставка ковролина для гостиничных номеров, коридоров, лобби и общественных зон. Подбор продукта и расчет по площади.",
    intro: "Согласуйте продукт по зонам гостиницы, получите образцы и подготовьте единую заявку для производства и поставки.",
    buyerFocus: "Для генподрядчиков, гостиничных операторов и проектных закупщиков, работающих с графиком открытия и несколькими зонами объекта.",
    primaryProductId: "custom-luxury-hotel-room-carpet",
    productIds: ["custom-luxury-hotel-room-carpet", "luxury-hotel-broadloom", "3d-printed-hotel-carpet"],
    englishPath: "/hotel-carpet",
    applications: ["Гостиничные номера", "Коридоры", "Лобби", "Рестораны", "Конференц-залы", "Лифтовые холлы"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "dlya-stroitelnykh-kompaniy",
    eyebrow: "Для строительных компаний",
    title: "Коммерческий ковролин для строительных и fit-out компаний",
    seoTitle: "Ковролин для строительных компаний и fit-out проектов | VISHOME",
    description: "Коммерческий ковролин и ковровая плитка для строительных компаний. Спецификация, количество, упаковка и поставка под график проекта.",
    intro: "Передайте площадь, план, тип основания и дату поставки, чтобы согласовать продуктовую спецификацию и следующий шаг по расчету.",
    buyerFocus: "Для строительных компаний, fit-out подрядчиков и закупщиков, которым нужно контролировать сроки, объемы, зоны и документы поставки.",
    primaryProductId: "public-area-heavy-duty",
    productIds: ["public-area-heavy-duty", "ecocore-pe-backing-carpet-tiles", "commercial-nylon-tiles"],
    englishPath: "/solutions",
    applications: ["Офисы", "Гостиницы", "Общественные здания", "Коридоры", "Реконструкция", "Новые объекты"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
  {
    slug: "optovye-postavki-kovrolina",
    eyebrow: "Оптовые поставки из Китая",
    title: "Оптовые поставки коммерческого ковролина из Китая",
    seoTitle: "Ковролин из Китая оптом | Производитель VISHOME",
    description: "Оптовые поставки коммерческого ковролина и ковровой плитки из Китая для России. Расчет проекта, образцы, упаковка и экспортная коммуникация.",
    intro: "Запросите подбор продукции, оптовый расчет и образцы для вашего рынка. Итоговые условия подтверждаются после проверки спецификации, объема и маршрута.",
    buyerFocus: "Для оптовых покупателей, региональных поставщиков и компаний, которые сравнивают китайского производителя с локальными каналами закупки.",
    primaryProductId: "commercial-nylon-tiles",
    productIds: ["commercial-nylon-tiles", "luxury-hotel-broadloom", "public-area-heavy-duty"],
    englishPath: "/commercial-carpet-manufacturer",
    applications: ["Оптовые склады", "Дистрибуция", "Гостиничные проекты", "Офисные проекты", "Строительные поставки"],
    benefits: coreBenefits,
    faqs: commonFaqs,
  },
];

export const ruB2BPageMap = Object.fromEntries(ruB2BPages.map((page) => [page.slug, page])) as Record<string, RuB2BPage>;
